### ISSUE TITLE
[UPDATED] Unable to login

### ISSUE THREAD

**Issue by ruzzetto** [nuxsmin/sysPass#1018]
Hello,
just finished a fresh installation of syspass. I create a test user with a simple password but (waiting for LDAP configuration) with these credentials I'm unable to login. System return me "Wrong login" red banner.

How can i fix it?

[UPDATE]: Probably I'm confusing account vs users... I'm sorry
Regards

**Comment by GGOUSSEAUD** [comment]
Accounts are to store your password with. Users are entities by which you do actions on web or through API.

**Comment by ruzzetto** [comment]
ok thanks, I'm going to implement LDAP integration. In this case they will be "users", right?

**Comment by nuxsmin** [comment]
Right ;)

LDAP users will be created automatically after their first login.

**Comment by ruzzetto** [comment]
Ok thanks. I created, just for testing, an "user" and after logged in it requires to insert master key..... why?

**Comment by nuxsmin** [comment]
B

**Comment by nuxsmin** [comment]
@ruzzetto because it needs to be encrypted with the user's data and it won't be required until next user's password change. 

Be aware that accounts' password are stored encrypted so they need to be decrypted every time you need to display it.

You could use a temporary master password for this purpose, so users won't need to know the real master password.

Please take a look to the doc on Https://doc.syspass.org

Regards
