### ISSUE TITLE
sysPass Setup in a windows enviroment using xampp-win32-5.6.3-0-VC11

### ISSUE THREAD

**Issue by Swiftzn** [nuxsmin/sysPass#103]
I have been trying to get syspass working for quite a while with Xampp on windows

i manged to get it installed after figuring out what to type where
now the problem i get is when i go to the page to try use syspass it looks like this after login

http://screencast.com/t/WAH1Terw4v

this isn't exactly the same for 
1.  i can't get the install language to be english so i had to translate the page
2. i have errors complaining about 
![syspass](https://cloud.githubusercontent.com/assets/6462867/7201202/fc6bb5ee-e504-11e4-8971-92228c537df4.PNG)

**Comment by nuxsmin** [comment]
Hi, don't worry about that messages, that is because the php running version is newer than sysPass was coded for (backwards compatibility).

All you need is to disable development logging mode in php.ini because it throws a lot of messages about deprecated functions that break JavaScript responses.

**Comment by Swiftzn** [comment]
any reason why i can't get paste the attached image above, can't use syspass as it doesn't load properly

**Comment by nuxsmin** [comment]
Please try to modify php config for logging. JavaScript could be broken because it so t does not load properly.

**Comment by Swiftzn** [comment]
I have set my PHP to log errors here is the last error i got after disabling developmetn logging

[17-Apr-2015 13:22:20 Europe/Berlin] PHP Warning:  file_get_contents(lang.tmp): failed to open stream: No such file or directory in C:\xampp\htdocs\xampp\index.php on line 2

**Comment by nuxsmin** [comment]
Ohh, no I've just told that you need to modify logging verbosity to avoid these messages, because it breaks some response headers.

**Comment by Swiftzn** [comment]
Below are my error config from my php.ini


>error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
>display_errors=Off
>display_startup_errors=On
>log_errors=On
>ignore_repeated_errors=Off

**Comment by nuxsmin** [comment]
Ok, let me do some tests on that environment.

**Comment by nuxsmin** [comment]
Successfully installed on xampp-win32-5.6.3-0-VC11.

Some points:

* After set display_errors to off you need to restart apache. 
* JavaScript need to be requested again because it's cached to improve browser requests, so you would need to refetch it by pressing CTRL+F5 to avoid php messages in previous cached response.

Let me know if it works

**Comment by Swiftzn** [comment]
wow feel so noob it's working now

**Comment by nuxsmin** [comment]
Great!!. I hope you find it useful ;)

**Comment by Swiftzn** [comment]
last problem i am having is i have set language to english but it still displays in spanish

**Comment by nuxsmin** [comment]
Still trying to find out what could happen....

**Comment by nuxsmin** [comment]
Hi there!!

I have some bad news, I didn't have success to get language working on XAMPP, there can be some issues with gettext and windows locales implementation. The only two solutions that can work is by implementing php-gettext class in the application or converting gettext strings to arrays. I think it can be accomplished for 1.2 release, because time I need to spent on it.

My suggestion is to create a linux virtual machine, because PHP+Apache+MySQL works better on a linux environment and you will get rid about locales, security and some annoying issues. XAMPP is great but it's targeted for development environments, not for production ones: http://stackoverflow.com/questions/675188/lamp-xampp-for-production -- https://www.apachefriends.org/index.html#300

You have some howtos about linux setup at http://wiki.syspass.org

Kind regards
