### ISSUE TITLE
Password limitations (syspass 2.1.16)

### ISSUE THREAD

**Issue by D3luxee** [nuxsmin/sysPass#1038]
Hello,
Currently im testing syspass to evaluate the usability for my team, after some issues with the user passwords #879 i've decided to push it to the limits.

I've tested the max length of a alpha numeric password and was bound to 117 characters, if i type more the password fields get set to "false".
The 117 characters limit itself is not that worse but the user should get the noticed about this limit and the field should not truncate itself to the value "false".
This could cause password loss because the user wont notice that his password was set to false.

Passwords with special characters also worked up to 117 characters.

Then i was using a more complex password with extended ascii and special chars, if i use such a password and set the length to 117 characters syspass does save it but if i view or copy it to the clipboard it will be some base64 encoded string. 

Test data:

117 Chars alpha numeric:
`rBASR5ffShXNxjqGhDhhenDKW9ZMLR4nPML26rJWw5D4PRcYm8v9RdbN84YX42tn4gZZDd43QBWmN3Gof3xVvoTA6G9AL6RUdvakXmpS9baXcttFhkHCj`

117 extended ascii:
`sî«@ÞÕ&/fg@PôKd¢m¼Ô='Ùr5Ãv¬ÔÿæªÍÙÆÐYhj%\¹zÄL¥Û#Õiã@ï>ß÷á»Ó{ÏÆs6=\å½F§6Rä³%),È¢&x¬F¦ÝRZ<R#Îú·ÈU:øÄßv²5ÎMfóZ¯ýSíP>ö¨{´"`

I could not find any documentation about the official password complexity limitations of syspass. What kind of passwords can syspass manage and what not.

Regards,
D3luxee

**Comment by nuxsmin** [comment]
Hello, I'm glad to know you're evaluating sysPass.

Regarding the password length limit, please let me find out why is it being cut off at 117 chars length. It could be caused by the JavaScript RSA encryption, since this process is performed before sending the password over the network. There would be some limitations when storing it in the database, since the data type of the table field is set to `varbinary(1000)` and the password is encrypted using AES 256 with a payload composed by HMAC and other cryptographic stuff to ensure its security.

I'll be back shortly, in the meantime, did you check out v3?. It will get soon the stable stage, so it's worth to perform some tests (alongside the unit tests) to get some feedback about it.

Thanks for the feedback!

Regards

**Comment by D3luxee** [comment]
Hi,
No i did not test v3, i just wanted the latest stable version because we wanted to use it in our productive environment.

I will setup some v3 testing environment and check this behavior there.

**Comment by nuxsmin** [comment]
Hello, it seems that there is an issue in the RSA library (3rd party) on the PHP side, since the encrypted data is sent to the server and then, when performing the decryption step, it fails and saves the base64 encoded data sent from the client, so it's actually storing the RSA encrypted password.

**Comment by nuxsmin** [comment]
Well, some commits ago I've implemented a client side warning about those passwords that exceed 117 characters long, since client side function does not support such length though server side does.

Thanks for the feedback!
