### ISSUE TITLE
New added users get no invitation mails

### ISSUE THREAD

**Issue by shamis-illya** [nuxsmin/sysPass#106]
Hi,

at last I've successfully managed to install latest SysPass version at my Gentoo ManagedServer.
Now I'm kind confused, because I can add new user, but the user get no notification per mail, that there was an account created for him. The user will only become email, if I check the "Password Change" option.

In Log I can see following message after adding new user:
E-Mail is sent to
To: 
CC: syspass@mydomain.com

Would you please check what is wrong here? I've definitely entered the mail address during creation process. 

And just by the way: why does new user get's following notification - "false master password" ?
As far as I know, there can only by either one unique master-password for all the users (and it shouldn't be asked from "normal user", but only from SysPass-Admin) or each user gets his own master-password for encrypting his own credentials in DB.

**Comment by nuxsmin** [comment]
Hi,
users won't receive email notifications unless he's required to make a password change on next login, so he will receive that email when he logs in with his current password.

That email notification it's only for warning purposes to sysPass administrators that have access to the notifications email account.

About master password you can take a look to sysPass wiki http://wiki.syspass.org/syspass/faq-en#is_there_a_master_password_for_each_accountuser ...BTW there is only one unique master password, that need to be reentered when it changes or when users change their own authentication password. In next release there will be a temporary master password that users can make use of to enter when prompted, so there won't be the need to give the real master password. Actually I have a "beta" patch to do this on current version, so if you need it I can send it.

**Comment by shamis-illya** [comment]
But the email looks kinda strange, see this:

"An inquiry for changing of its user's password was begun.
For the end of this process, go please to the URL: 
https://mydomain.tld/syspass/index.php? a=passreset&h=8e5439cd5bc013729e6005f880eea5&t=1431765316
If you have not released this operation, ignore please this message"

I've just translated the text of the mail from German to English with Google-Translator. 

I just miss the logic, but why doesn't the user simply get the nofication about his newly created account and password in system?  

Well and as to the master-password: why should any ordinary SysPass user (neither “Account Admin”, nor “Application Admin”) be asked for master-password, as soon as he wants to change his own accounts password? Don't you think that it simply compromises the whole system, because you encrypt all of the password in DB with that unique master-password? 

Application master-password should only be known and entered by application admin. And if you would like, then you could also implement kinda "secret place" in the whole DB for each user, giving him the possibility to enter his own master-password, for his own (unshared) data.

**Comment by nuxsmin** [comment]
Hi, the password reset email is sent when the user or app admins requests for its password change.

About master password, you're partially right, but sysPass was originally designed as a enterprise password manager, which means that all the accounts must be accessed by some users profiles, so need to share that secret and then the master password must be the same. If each user would have its own master password accounts' passwords would be only readable by each one that have the same pass.

Another kind of problem is how to store a shared password, which involve security risks, so I decided that it will be encrypted  with each user password and a known salt and compared against a hash so it avoids to be permanently stored with a known encryption key. This is an approach because the best one is by using PKI, but this involves more complexity for users.

All suggestions are welcome ;-)
