### ISSUE TITLE
Ldap automatic sync

### ISSUE THREAD

**Issue by M1k13** [nuxsmin/sysPass#1062]
syspass 2.1.16.18061901

Ldap automatic sync:

Hey, im trying out syspass and it looks great I have only one question. Does syspass automatic sync with Ldap or do you have to import Ldap users manual every time you add new user in to the Ldap DB? If it does'nt is there a way to configure it so it does sync auto.

**Comment by nuxsmin** [comment]
Hi, you don't actually need to import any LDAP user, sysPass will do it for every new user that logs in. the newly created user will get into the user group and profile set in LDAP configuration.

You can also import LDAP users manually in order to assign them a group and profile before their first log in.

Regards

**Comment by M1k13** [comment]
Hey,

Thank you for your fast reply. I’m gonna try this out!

Have a great day,
