### ISSUE TITLE
v3 empty Clients is seen for all

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1076]
In latest git commit of v3, when a simple account in a group can see their passwords from their group, but in "Select Client" dropdown he can see all other Client who have no account associated.

To reproduce : 
- have an account with limited right like "View password" only
- be in a user group
- add a Clients for this account and add some password with this Clients name in primary group
- add an other Clients name and don't assign password to this new Clients
- login in with simple account and in main page, open dialog "Select Client" to see other Clients name create before
- add an account to the new Clients name with admin
- simple account will not see new Client name in dialog

It is not necessarily a very embarrassing bug, but depending on the context in which people use it, it can cause sensitive information to leak.

**Comment by nuxsmin** [comment]
Hello, you're right though in v3 a global client option was implemented, the old behavior was left, so everyone can see a non global client until it's assigned to an account. I think it could be improved by filtering out non global clients but it was kept because legacy users. I'll give a thought about how to not make a breaking change.

Thanks for the feedback!

Regards.

**Comment by pierrehenrymuller** [comment]
Ok I understand, I'll let you see the best between these two cases.
