### ISSUE TITLE
Accessing syspass after config.xml lost

### ISSUE THREAD

**Issue by mwelch-ptc** [nuxsmin/sysPass#1085]
**sysPass Version**
2.1

**Describe the question**
We're still trying to figure out how, but our config.xml was somehow lost. Our database is fine, but all data in that file is gone. 

When I restored syspass with a new config.xml and manually put the database connection details in the config.xml file, syspass seems to be able to connect to the DB fine, but neither our admin user or any of our ldap users can login. When we try to login with a username/password, we are presented with a new dialog asking for our username, password, and "previous password". There is no previous password for the admin user. Regardless, once we try to input values at this stage it fails with the error "Wrong Master Password" and the new dialog asks for User, Password, and "Master Password".

Is there anything we can do here? It would be catastrophic to lose all of the accounts stored in this system. I thought that backing up our database would be sufficient for disaster recovery. I was apparently incorrect.

**Comment by nuxsmin** [comment]
Hello, sysPass is asking for the master password because the encrypted data cannot be decrypted using a derived key from user's data and a salt (stored in config file). Do you know the master password?.

A configuration backup should be stored in the database, but there isn't any function implemented to get it. It's stored in JSON format and need to be converted into XML.

Regards

**Comment by mwelch-ptc** [comment]
Thank you!!! This got us up and running! 

Not terribly important, but converting the config back to XML in a way that syspass would accept was a bit trial and error. Is there a reason it's backed up in the database as JSON? No big deal as this isnt' something I would expect anyone to need to do on a regular basis. Just curious. Thanks again for your help.

**Comment by nuxsmin** [comment]
I'm to know it's running fine. 

The JSON format was chosen because a matter of size, since XML is more verbose and anyway it's converted into PHP code when it's read, so JSON can also be converted into a PHP object in the same way. You may be wondering why the configuration is saved in XML, because it's quite handy to work with its node structure and attributes, and it seems more readable and concise than other formats.

Regards
