### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#1121]
Hi @nuxsmin ,
please fix this mini issue ("dysplay"):
![grafik](https://user-images.githubusercontent.com/5631071/48947683-3b792b00-ef32-11e8-9460-64a5db66d530.png)

I opened this ticket because i also want to ask you if you receive notifications if i change something in POEditor project. Do you get informed if i add some comment?
regards, Mario

**Comment by nuxsmin** [comment]
Hi!, sure, I'll fix it shortly.

> Do you get informed if i add some comment?

Yes, it sends me an email, but unfortunately comments on translations doesn't work as expected, since every comment is added to the `.po` file as a translation's comment, so this feature is to addd some context to the original string...

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Solved in latest commit.
