### ISSUE TITLE
SysPass restores the same account infinite times

### ISSUE THREAD

**Issue by javierlm** [nuxsmin/sysPass#1146]
**sysPass Version**
sysPass 3.0-rc3

**Describe the bug**
When an account is restored after is deleted, you can restore it again infinite times.

**To Reproduce**
1. Delete an account.
2. Go to Items and Customizations.
3. Select Accounts (H).
4. Restore the account previously deleted.
5. Repeat the last step multiple times.
6. Go to the main page, and search for the specific account.
7. Account is listed multiple times.

**NOTE:** In this example, the account called **Adam Bowen** is restored many times.

**Expected behavior**
Accounts must be restored once.

**Screenshots**
![syspass_restoring_error](https://user-images.githubusercontent.com/34691743/49227980-49232a80-f3e2-11e8-8fb3-afce77d3e7ec.png)

**Additional context**
Problem is reproducible with any account with permissions to access this menu.

**Comment by nuxsmin** [comment]
Hello, this behavior is a discussion point about what we expect from deleted items, since it isn't like a "recycle basket", because it saves the state of an account in an exact point in the past, so you could recover that state whenever you want.

I've tagged this issue as discussion in order to get some feedback from sysPass users

Regards

**Comment by vmario89** [comment]
Hi, think the history restoring think has some bug or problem in a pratical matter. Go to Accounts (H) and click on restore button. You will see that it duplicates each time clicking on "restore"
![grafik](https://user-images.githubusercontent.com/5631071/49234168-d58c1800-f3f7-11e8-90d2-7310fd20e321.png)
![grafik](https://user-images.githubusercontent.com/5631071/49234188-dcb32600-f3f7-11e8-82d9-6bb2c987f51e.png)
 clicking multiple times:
![grafik](https://user-images.githubusercontent.com/5631071/49234214-eccb0580-f3f7-11e8-80c3-c86a8962b454.png)

I checked it out. The account was not created the same amount - but it should?:
![grafik](https://user-images.githubusercontent.com/5631071/49234261-0409f300-f3f8-11e8-8097-1165e9931b82.png)


i think the general problem is that when restoring with the clock button ![grafik](https://user-images.githubusercontent.com/5631071/49235387-50563280-f3fa-11e8-8490-f97aa4c93bc7.png) you cannot see which state of the account you are going to restore because you dont have any details about it

It seems that the restoration has no influence to the history because there is no history row shown after using that. I tihnk when restoring an account it should add a history dataset to the account which is restored because you change the data from current state to some older historical state. Thats what "Accounts (H)" tells a user or at least lets me interprete it that way .

Or does the restore work the way it clones the account? In this case the cloned account should have some other naming if it already exists with same title. If yes there is no known setting how to handle.

At the moment neiter a new account is created nor another account is modified :-/

Maybe some documentation for this is required to understand the way to work with this in a good way. It also references on duplicating existing accounts (copy account)
![grafik](https://user-images.githubusercontent.com/5631071/49235595-b8a51400-f3fa-11e8-88b6-69ec349db0ff.png)

**Comment by vmario89** [comment]
*edit*: i linked that issue https://github.com/nuxsmin/sysPass/issues/1147 because i think thats the reason to be confused about it invisible history

**Comment by nuxsmin** [comment]
Hi,

to add some light about accounts point-in-time restoration:

- You can get more details about the point to restore on the account itself (by selecting the point's date), since restoring from the accounts' history manager is "the fast" way to do it.
- If the point to restore is a **modification point**, it will **replace** the current account with the data from this point. A new history entry is added for this account.
- If the point to restore is a **deletion point**, it will **create** a new account with the data from this point.

Regards

**Comment by vmario89** [comment]
Hi Ruben, that is a good explanation for this feature helps me understanding. Definetely worth to put in the docs :)

**Comment by nuxsmin** [comment]
@vmario89 Hi Mario, I'm glad to know it's a bit more clear now :wink:
