### ISSUE TITLE
API Query

### ISSUE THREAD

**Issue by lucasdiaas** [nuxsmin/sysPass#1164]
Hey, I wanted to know if I can do an API Query from the browser in a similar way as I do with  OpenWeatherMap.
With their API I can type http://api.openweathermap.org/data/2.5/weather?q=London&appid=a0c61f6be618a8d35a41fe8e396f4952&units=metric and it returns me a JSON. Then I can work on it with Javascript.

Is there a similar way to do this with SysPass API?
Thanks!

![apiquery](https://user-images.githubusercontent.com/22860001/49944154-ef862a00-fed0-11e8-87d0-87c331623d8d.jpg)

**Comment by nuxsmin** [comment]
Hello, as pointed on documentation (https://doc.syspass.org/en/application/api.html), sysPass API relies on JSON-RPC v2 schema, so you need to provide a JSON payload within the request. I've written a Gist including some code to make the requests either PHP CLI or browser (using some extension to make requests): https://gist.github.com/nuxsmin/62338b33178544894cd7237c7fe170bd

Why JSON-RPC v2?: because some API methods would require larger data fields (like notes on account creation), so relying on plain GET requests would be painful...(URL encoding, max. query size, etc.)

Regards
