### ISSUE TITLE
Error while copying to clipboard

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#1179]
Hello.
Copying to clipboard function periodically fail with an error message. Works but need to click few times to copy.
Im testing with Chrome 71 browser, in demo it works fine. I checked the logs and when the problem occur this message are logged:

`2019-01-05 19:55:37 [EXCEPTION] [N/A] Context not initialized`
`2019-01-05 19:55:37 [ERROR] [SP\Core\Language::setLocales] Could not set locale`
`2019-01-05 19:55:37 [EXCEPTION] [N/A] Context not initialized`

I think that is something with my installation, can you help me?

bellow informations about the server:
sysPass Version: 3.0 (300.18122601) - Problem with 2.6 too.
Mysql: 5.5.60-MariaDB
PHP: 7.1.24
Apache/2.4.6
Centos 7
SELinux was disabled for test but no success.
It is not behind a proxy.

Attached the log file.
[syspass_log.txt](https://github.com/nuxsmin/sysPass/files/2729849/syspass_log.txt)

Also, there is some alternative to mcrypt with php 7.2 for sysPass?

**Comment by nuxsmin** [comment]
Hello, these context related exceptions are weird. I'll check it out.

Regarding mcrypt, it's never used since 2.0 when it was switched over OpenSSL. PHP 7.2 implements libsodium which is a stronger encryption but there are already many outdated installations, so switching over libsodium will be done later.

Regards

**Comment by nuxsmin** [comment]
Ohh, sorry I missed some parts of your issue description

> Copying to clipboard function periodically fail with an error message

It would be a normal behavior, since browsers' clipboard API has some restrictions about copying data to the clipboard. One of these restrictions is the max time to copy the data since the event was triggered, so since sysPass makes an AJAX request to the server for getting the password, if this request exceeds the max execution time, it will cancel the request.

This a known limitation of the current API, because it does not allow to copy data to clipboard from async requests (AJAX), so we need to do some tricks to get the desired behavior...

**Comment by nuxsmin** [comment]
Please see #739
