### ISSUE TITLE
Copy Password to Clipboard and Logging

### ISSUE THREAD

**Issue by gleisonbaioco** [nuxsmin/sysPass#118]
I'm trying the sysPass software (demo.syspass.org) and it seems to be a very interesting product.

I have observed an issue regarding logging. When I show a password the action is recorded correctly. But when I copy a password to clipboard the action is not recorded in the log.

Am I correct with my analysis? If so, do you plan to record the copy to clipboard action in the log?

**Comment by nuxsmin** [comment]
Hi Gleison,

You're right, actually, view pass event has not been logging because the copy-to-clipboard flash implementation which needs to trigger a "view pass" action every time that the mouse is over the clipboard button, so it was very annoying (has been working in the past) to see a lot of "view pass" records in the event log...

This has been solved int the next 1.2 release (will be a demo available soon).

Kind regards.
