### ISSUE TITLE
CAS SSO Authentication plugin

### ISSUE THREAD

**Issue by ThomFree** [nuxsmin/sysPass#1193]
Hi,

**Working on a new plugin for sysPass that will allow user to log in via a CAS server (Apereo).**
So I am trying to override the login page and redirect it to the CAS server.

If you have any advice ;)

**Comment by nuxsmin** [comment]
Umm , this plugin would be useful. Be aware that there isn't any event before login, so it wouldn't be possible. What about setting Auth http headers from the CAS server that would be read by sysPass?. Another key point is about user's login data, because they're used by sysPass in order to encrypt/decrypt the master password, so the CAS server will need to provide them.

Regards
