### ISSUE TITLE
Cannot create an account with a very long password

### ISSUE THREAD

**Issue by arnolem** [nuxsmin/sysPass#1217]
**sysPass Version**
3.0 (304.19012601) 

**Describe the bug**
When I create a new account with a very long password (we have password for server with 128 caracters), I have this error : Data length too big for encrypting

**To Reproduce**
1. Go to 'new account'
2. Use a a very very long password like : 7cw5giXA53eA5buh79759U3B1SC17w3TmfjXHBpS588S2Qjj4PtBg7H91jnY55hPK4Q1atfFknGj2driyDGW24vF459xRvc6eG2M9YwycU354fW9CWE9jBzGkJEVNm7T
3. Click to 'save'

**Expected behavior**
There is surely a good reason to limit the size but unfortunately, I really have long passwords and I can not register them. We should not limit the size of passwords in this form

**Screenshots**
![image](https://user-images.githubusercontent.com/2263103/52013318-01ea1080-24dd-11e9-9ee3-7091e5a8ae55.png)

**Platform (please complete the following information):**
 - Firefox

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply...

This limit is enforced by the RSA encryption, since every password field is encrypted before sending to the server (and encrypted with the master key on server-side), so it's not about a form length limit, but an encryption one: https://security.stackexchange.com/questions/33434/rsa-maximum-bytes-to-encrypt-comparison-to-aes-in-terms-of-security

I think a global option could be added to disable RSA, but it will lower the security when sending forms and even worst when no using SSL (HTTPS).

Regards

**Comment by arnolem** [comment]
Thanks,
Currently, I abandoned sysPass because of this. I have more than 100 accounts with a big password

**Comment by nuxsmin** [comment]
Thanks for the feedback!

Hopefully some kind of improvements could be done in the future.

**Comment by sebastian-bugajny** [comment]
Anything has changed since then. I hit on the same problem in version 3.1
