### ISSUE TITLE
Event log list is still incomplete

### ISSUE THREAD

**Issue by deajan** [nuxsmin/sysPass#1245]
**sysPass Version**
v3.0.5

When configuring security audit, there are predefined events than can be added to the list of events that will be logged.
It seems that some are missing (eg, ldap.*).
Shouldn't there be the full list of all possible events ?
![image](https://user-images.githubusercontent.com/4681318/52625375-249f0080-2eb1-11e9-9c98-7bb4120088c6.png)
Also, how about a standard list (like login, logout) that should be enabled by default ?

Best regards.

**Comment by deajan** [comment]
I also happen to have a lot of these logs now:
```
edit.plugin.unavailable	user XX.XX.XX.XX Plugin unavailable: Authenticator
```
This setup is a 2.1 to 3.0.5 upgrade, and I did not enable authenticator plugin.

**Comment by nuxsmin** [comment]
Hello Orsiris,

>  Shouldn't there be the full list of all possible events?

I'm not sure about how to implement the events list, since there are many events to be listed, so I'd rather publish a list of available events (https://doc.syspass.org/en/3.0/application/plugins.html#events)

> This setup is a 2.1 to 3.0.5 upgrade, and I did not enable authenticator plugin.

This kind of event is being logged because every time sysPass loads a page, it will check if an installed plugin is physically available (ie. the plugin's directory exist), if doesn't it will mark the plugin as unavailable. This behavior will change in next release.

Regards
