### ISSUE TITLE
How to export all the passwords to a CSV/XML file to import into another application

### ISSUE THREAD

**Issue by Breakingcustom** [nuxsmin/sysPass#125]
I see you can backup from the website, but I don't see an option to export everything to like a CSV/XML file.  Needing to import everything into another system.

**Comment by nuxsmin** [comment]
Hi, that feature is already implemented in the 1.2 release, but it actually is at beta stage. You can download it from github by selecting dev branch.

Despite it is a development version, it's fully functional.

**Comment by Breakingcustom** [comment]
Much thanks.

Tried to upgrade but get “Operation Not Permitted”.  Can’t login as root because the past sysadmin never left that password.

**Comment by nuxsmin** [comment]
I can figure out where is shown that message because there isn't any translation for that. 

For upgrading you need shell access (not necessarily root) to get the upgrade key in the config file, because you need to confirm the database modification.

Another idea can be to install a new sysPass by doing an application and db backup and then exporting to the other machine.
