### ISSUE TITLE
ldap import - assign user AD groups

### ISSUE THREAD

**Issue by Idriel** [nuxsmin/sysPass#1261]
Hi,

Is there some way how we can Import AD Users (in scheduled way) and that Imported User is assigned with imported Groups from AD.
 
Example: if the user are in let say AD Group: Test_Syspass, during the AD Sync "user" will be assigned to "Test_Syspass" group also. 

We are thinking in something like: 
Folder1 (is like root and then they can create passwords, cannot see Folder2) -> Access to AD Group1
Folder2 (is like root and then they can create passwords, cannot see Folder1)-> Access to AD Group2
If user is in AD Group1 and AD Group2 then they can see both Folders(Customers...)
...

**Comment by nuxsmin** [comment]
Hi,

this feature was discussed a time ago and I end up that it would be a pain when the users have  either multiple or nested groups, since which ones should be imported?. Although it would be useful, it could lead in many mistakes so its implementation was declined.

Anyway, you can use the API for performing a scheduled import for users and groups.

Thanks for the feedback!
