### ISSUE TITLE
Error Sending Syslogs

### ISSUE THREAD

**Issue by berni69** [nuxsmin/sysPass#1272]
After upgrade to the latest version from 2.1 I'm not able to load the application. Seems to be related with the syslog. I'm getting the following exception:

```
Call to undefined function Monolog\Handler\SyslogUdp\socket_create()
```
That's my config:

```
  <syslogEnabled>1</syslogEnabled>
  <syslogPort>514</syslogPort>
  <syslogRemoteEnabled>1</syslogRemoteEnabled>
  <syslogServer>logsserver01</syslogServer>
```
After disabling it the app starts working.

**Comment by nuxsmin** [comment]
Hello, it seems that something is wrong in your installation, since that error is related to a 3rd party package which works fine. Here you have an example on a live capture:

![Peek 26-04-2019 23-49](https://user-images.githubusercontent.com/1775774/56838443-46880c80-687e-11e9-8f1f-7b47d91865ca.gif)

Regards
