### ISSUE TITLE
Lasspass integration: auto-update/save password within lastpass

### ISSUE THREAD

**Issue by DDH112** [nuxsmin/sysPass#1295]
**sysPass Version**
3.0 (304.19012601) 

**Describe the bug**
Might be a feature request as well, but the lastpass plugin detects a password change, but is not able to save the new password from the password field. Is this something that can be fixed?

**Comment by nuxsmin** [comment]
Hello, do you mean about changing an account's password or when logging in?

Regards

**Comment by DDH112** [comment]
Both cases. I tried it on the demo instance as well. When logging in the password is syspass, but lastpass  registers the following:

fij8YhmUw/W1NkPFlORzan5W1OHf2csbfTjqzBol9TZj1ldEgvrX9hTFM3AfrY0li6BDG8z1vLC68wwtI0J3S7GZTxAKJxgZRtE0q9W/LRIQPshw82ET4F7k9MLEBovEfZq6xss4Wyy7pVV7VsNlK+7dZczp1gIDKAWEPLjJIzs=

**Comment by nuxsmin** [comment]
Unfortunately sysPass encrypts every password field before sending the data to the server, once there it will be decrypted and encrypted again with the current master password.

It means that you won't be able to save any real sysPass password using lastpass since you are really saving the RSA encrypted password instead.

Regards

**Comment by DDH112** [comment]
Too bad...

**Comment by nuxsmin** [comment]
From a security point of view, good :wink: 

Note that this isn't a behavior against password managers but a security feature instead.
