### ISSUE TITLE
LDAP improvements

### ISSUE THREAD

**Issue by slushz** [nuxsmin/sysPass#1309]
Hi!, i have just tried syspass and i think would be nice to have the following features:

- It would be great if the user can change his LDAP password through syspass.
- LDAP filtering improvements, for example, not import disabled user accounts 

Thank you and keep up the good work!

**Comment by nuxsmin** [comment]
Hi, I'm glad to know that you found sysPass useful.

Regarding your points:

* The LDAP change password wouldn't be implemented, since should be good at managing secrets but not changing data on 3rd party providers (ie. LDAP). It will also avoid many security issues when dealing with data on other systems.

* About filtering there's an option for importing using a custom filter, so so can  set any option for importing the users as you want.

Thanks for the feedback!

Regards.
