### ISSUE TITLE
why masterpassword?

### ISSUE THREAD

**Issue by magalo** [nuxsmin/sysPass#1341]
about masterpassword I have some questions because I did not understand it despite extensive search.
I have read almost all github resources and still didn't understand it.

1. is it correct that you have to give out the master password or a temp to all syspass users if you want to change your password yourself see
https://github.com/nuxsmin/sysPass/issues/358
so is it correct to give out the master password to all syspass users ? or should any user ask everytime  he woulkd like to change his passord for an admin ? and this admin has to give the users a masterpassword or a temporary password?

2. why no other service uses this kind of password management ? Not even a domain controller or banking software´or even github uses such a procedure. Is it still safe if I have to give the master password to the users so they can change their passwords? 

i looked at the image of the encryption method and think i can see why the master password is necessary in this construct, but if every syspass user then needs the master password and maybe writes on a note and puts it under the keyboard, all security is gone. So wouldn't it be better to get the master password by challenge response from a second server or use another method? 

would be great if the necessity of this procedure would be explained in more detail in the help.

Thanks for the great program

**Comment by nuxsmin** [comment]
Hello, the master password is used for encrypting every account password and some other data as custom fields or plugins' data.

This schema allows to any arbitrary master password  for encrypting data, other services do use a master password , but unlike sysPass they use a  central master password (strongly stored) so there is no need to ask for it. How would be ensured a central master password by admins with less or none security knowledge?.

I agree that a strong master password must be stored in a secure vault and then used by applications, but this schema involves to have a deep knowledge about security, and many resources than a single PHP application.

You shouldn't give the master password itself but a temporary one instead, which will expire by time. The master password or the temporary one is only needed whenever the user changes its own password or the master password is changed.

I hope this answers your questions.

Regards

**Comment by magalo** [comment]
hy, thanks for your fast response - i have another question to understand the security mechanism.
The main access to Syspass is via webbrowser .. so there is used https to transfer the data.
https needs a secure private key which must be stored on the webserver in a "secure" folder.
So if someone is able to change the private key - is  Syspass secure because of syspass internal encryption or is the whole server compromised ? 

And if this isn't the case it is perhaps possible to bind the masterkey to such a private ssl certificate key and password changes are possible without the a key derived from masterkey ?

Thanks in advance

**Comment by nuxsmin** [comment]
Hi, sysPass encryption is done by using its own master key and it isn't stored within the web server. Each user "has" an encrypted copy of the master key, which is encrypted by a derived key from the user's data and application hash (within config file). This data is stored in the database.

A compromised server is always dangerous, since network traffic can be sniffed (if privilege escalation is performed) , so any data can be leaked out.

About your second question, I'm not sure about it, could you explain it?

Regards

**Comment by magalo** [comment]
ok - i will try to explain it. syspass uses a own masterkey for encryption ... the masterkey isn't stored on the server itself for security reasons. but - to access the server you need a browser - so the user must use https to secure the connection to prevent that something can be sniffed via man in the middle. but.. if somebody has access via filesystem to the sysPass server the attacker is able to replace the sll certificate for https and the security is broken and an attacker is able to sniff the master passord ?
When this is correct - why don't integrate the master password into the server at the same place where the private ssl key is located.
The main adavantage to not intergrate the masterkey into the applciation/database is that an attacker can't access the database from an offline clone of the syspass system, right ?

Kind regards

**Comment by magalo** [comment]
perhaps there are software TPM implementatiosn like described here for experts (not me) to solve the key 
"problem"
https://www.usenix.org/system/files/conference/usenixsecurity16/sec16_paper_raj.pdf

**Comment by nuxsmin** [comment]
The master key is always on the server side, it never is sent to the client, so no, an attacker cannot sniff the master key. In order to keep it more secure, once the user logs in, that master key is decrypted and encrypted again in the user's session (server side), so it remains encrypted until it's needed to decrypt any data. The session will expire whenever user logs out or inactivity timeout is reached. The key used for encrypting the master key in the session is changed every 2 minutes, so it's encrypted again by this time.

Ideally the master key must live in an isolated vault, but it would add more complexity to the architecture that will prevent to some users to use this application, because it will require some other components to be installed in a secure way.

Regards

**Comment by magalo** [comment]
ok - Thanks four your explanations and thanks for this program

**Comment by nuxsmin** [comment]
Thanks for the feedback!
