### ISSUE TITLE
TeamPass to SysPass

### ISSUE THREAD

**Issue by jboissat** [nuxsmin/sysPass#1352]
Hello

I would like to know if there are any users who have already migrated from TeamPass to SysPass

If so how did you proceed

Thank you and good day

**Comment by nuxsmin** [comment]
Hello, I don't know if there is any way to export Teempass data, but I'm willing to code an option in sysPass for importing from XML or JSON formats.

Regards.

**Comment by jboissat** [comment]
Hello

sorry for my late response, yes there is a possibility with teampass to access with the API in JSON or else to make an export Excel

What do you prefer ?

Thank you

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply too...

The preferred format would be an structured (eg. XML) or a semi-structured one (eg. JSON), since many items will be related and they need to be fitted/converted to sysPass data schema. A CSV file would a pain with poor results after all...

Getting data from an API would painful too, because relations and how the API data is formed, that is whether a relation is displayed as an ID or a name...

Regards

**Comment by jboissat** [comment]
Ok, what information will you need attached the URL of the doc

https://teampass-api.readthedocs.io/

**Comment by nuxsmin** [comment]
Could you provide a real nested folder response? (please, do not include real data): https://teampass-api.readthedocs.io/api/nodes.html#folders

**Comment by pierrehenrymuller** [comment]
Before Syspass we were under teampass.
We started with an automation of password management from Ansible for the vast majority of entries to stop sync manually passwords between servers and password manager.

To avoid any loss of information, we opted for an export from teampass to a flat file and reimported only what was not manually automated. All other was regenerated from Ansible and apply directly to accounts in servers.

It took us a long time but many of us managed to do it without loss.
This also allowed us to find some bugs in first versions of Sypass 2 fixed since then thanks to Nuxsmin :)
If you want to interface in python to reinject your teampass data to syspass, we developed this API connector for Ansible. Just reuse it.
https://github.com/pierrehenrymuller/ansible-syspass-lookup

**Comment by jboissat** [comment]
> Could you provide a real nested folder response? (please, do not include real data): https://teampass-api.readthedocs.io/api/nodes.html#folders

ok I put this in place and I come back to you



> Before Syspass we were under teampass.
> We started with an automation of password management from Ansible for the vast majority of entries to stop sync manually passwords between servers and password manager.
> 
> To avoid any loss of information, we opted for an export from teampass to a flat file and reimported only what was not manually automated. All other was regenerated from Ansible and apply directly to accounts in servers.
> 
> It took us a long time but many of us managed to do it without loss.
> This also allowed us to find some bugs in first versions of Sypass 2 fixed since then thanks to Nuxsmin :)
> If you want to interface in python to reinject your teampass data to syspass, we developed this API connector for Ansible. Just reuse it.
> https://github.com/pierrehenrymuller/ansible-syspass-lookup

thank you i'm going to look

**Comment by jboissat** [comment]
@nuxsmin 

Here is the test tree for the API 

<img width="221" alt="folder apitest" src="https://user-images.githubusercontent.com/43809874/64080654-ec4cfb80-ccf6-11e9-8d60-59e78c9d9c30.PNG">

Here is the url for API access to this tree with the test user 

https://deltapass.groupe-delta.com/api/index.php/read/userpw/api.test?apikey=pbgKKgrnDZW9nsLm7HWH6zVHDqPxHNw5GqBZuxN

It's good for you ?

**Comment by nuxsmin** [comment]
@jboissat sure! Thank you! (please do not expose your API!, you can upload the JSON to any file service....)

**Comment by nuxsmin** [comment]
@jboissat It'll be really a pain, because folders are displayed as a string in `path` field...

![467](https://user-images.githubusercontent.com/1775774/64082514-879e9a80-cd10-11e9-8f6d-b57e3adc7722.jpg)

**Comment by jboissat** [comment]
Yes, it would be necessary to do a treatment on the string of character,

After the first ">" customer name After the second ">" category

**Comment by jboissat** [comment]
Hello

Your idea was to query the APIs via Powershell in order to format a CSV?

**Comment by nuxsmin** [comment]
@jboissat No, it would a painful way. It's good to parse the JSON, but please let me know how the path should be interpreted.

Thanks for the feedback!

**Comment by jboissat** [comment]
After the first ">" customer name 
After the second ">" category

For Exemple : 

customer name  = Client A
category = Bureautique

**Comment by jboissat** [comment]
Hello

Have you been able to look at the feasibility

Thank You

**Comment by jboissat** [comment]
Hello

Still determined to migrate from Teampass to SysPass, I'm testing through a powershell that calls APIs to generate a csv file formatted for SYSPASS

However when I try to import this file I have an error "Type MIME forbidden / application / vnd.ms-excel" or I authorized the MIME in "Parameter / account / file"

In Piece attached my test file

[result.zip](https://github.com/nuxsmin/sysPass/files/3642703/result.zip)

**Comment by jboissat** [comment]
Migration by export and manual entry

**Comment by nuxsmin** [comment]
Hello @jboissat 

I've been a bit busy during last weeks...

Anyway, these are good news though an automated method would have been more suitable.

Thanks for the feedback!

Regards
