### ISSUE TITLE
What are the asset files included in each release ?

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#1372]
I'd like to upgrade from sysPass 2.1 (in Debian 9) and when going to the release downloads I notice there are 3 files I can get:

* vendor.tar.gz
* Source code (zip)
* Source code (tar.gz)

Installation instructions still mention syspass.tar.gz which is not in those assets and upgrade documentation doesn't indicate which file(s) to get. I can't clone directly on the target server I wish to upgrade.

Which one(s) should I use to upgrade ?

**Comment by nuxsmin** [comment]
Hello, it depends on how are you running sysPass. If you're on an on-premise installation, it would be enough by downloading the latest package, replace the current files and run composer to get the dependencies. Otherwise, if you're running on a hosting site where composer isn't available, you will need to download the vendor package too.

Docker based installations would need to download the latest image and replace the running container.

There's a brief documentation about how to update using composer.

Kind regards

**Comment by MagicFab** [comment]
Thank, I still think the documentation about this could be improved but I know next to nothing about composer in Debian and still not sure what the exact steps to update would be.

**Comment by nuxsmin** [comment]
Done!
