### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#140]
What do you think about the latest 1.2RC5 release?. Do you have any issue?. Do you have any suggestion?.

It's very valued to take some feedback from you and it helps to push sysPass to stable.

Kind regards

**Comment by fwilly** [comment]
I have several suggestions:
   1. Usually I use KeePass. I like there especially that accounts can be structured into groups and subgroups. In order to achieve the same, but to retain the flexibility of SysPass, I would still suggest a grouping by taxonomy alongside customers and categories. That means, you can assign an unlimited number of tags to an account. In the view you can now select multiple tags to be included.
   2. The unfolding of optional actions annoys. Either one makes it easy to set whether you want it or not. Or is it configurable which actions are optional and which are not. I constantly need to copy the password or go directly to edit the account. The "view account" button (I see all informations) and the "view password" button I don't need.
   3. A short copy action for all columns would be nice. Now I must mark the customer and copy it to use it by paste it in an other program. Good would be a button, which is shown on hover, where can click to copy the value.
   4. The random colors of costumer in account list confuse me. Better would be I can define colors for costumer. Or a random color is set on creating a costumer.
   5. The "edit work flow" is not nice. Currently I must go to edit. Then edit anything on an account. After save I get the account in view mode. How can I go back to list of accounts now? Go back by browser isn't a good idea. Then I must new login and the previews filtered view is lost. I can only go back by navigation button. But this make a javascript go back in history. I'm now in edit mode again. Only when I use now the arrow I'm back in account list. There are multiple solutions:
      1. Inplace edit directly in account list.
      2. A "go back to account list" button on edit page.
      3. Automatically go back to previously view after save.

I think it is currently enough.

**Comment by nuxsmin** [comment]
Great...good points!!:

1. You are right, I have had it in mind but this release has taken too much time to get out, so I decided to leave it for the next one.
2. Actually there is no option to configure the unfolding actions. That behavior is done so because if you resize your screen on the x axis, you can view that there is no space available to unfold all the options. BTW I think so that an user preference would be nice to set which options to show.
3. It can be done easily ;)
4. Good point!
5. There is an action icon on the top navigation bar that links to the search accounts view. The back to view behavior is due to if you perform the account saving and didn't notice that it was updated (the popup disappears), you can think that it wasn't updated so you do it again. So if after updating it goes to the view page, you are sure that it was.

Thanks for your feedback ;)

**Comment by fwilly** [comment]
1. Thats would be great. An example to use would be accounts for different stages.
   * a tag DEV for FTP, CMS and HTTP Auth accounts for development
   * a tag TEST for FTP, CMS and HTTP Auth accounts for test and
   * a tag LIVE for FTP, CMS and HTTP Auth accounts for live
2. Is there a short way to expand it ever? A hack would be welcome too.
3. I'm waiting ;-)
5. And why disappears it? You could get the info, that nothing was changed.

**Comment by nuxsmin** [comment]
1. Development
2. It can be easily implemented as an user preference, meanwhile you can edit the search.inc file of the theme used (by default material-blue) and search for the <I> tags that contains a class called 'actions-optional' and remove that class (only 'actions-optional').
3. Development
4. Development
5. The default behavior of that pop-up is to disappear after 10 seconds, it can be fixed, but it could become annoying when others pop-ups are shown and also remains fixed (until you click on them, but it needs more user interaction). Let me think about how it can be improved. Why you don't like the current behavior to go back to view? It is safe to not to edit the account again and you should be able to go to the accounts list (clicking on the search icon) again without login and keeping the search filters, don't you?

**Comment by fwilly** [comment]
To 5.)
The view button is a good help, but it is not the expected way.
The "don't changed message" is not so important, that it must clicked to accept. It can how all other automatically removed in any seconds.
Additionally a possibility to display multiple messages at same time would be good.

**Comment by fwilly** [comment]
To 2.)
I have changed my view successfully.

**Comment by nuxsmin** [comment]
@fwilly 2.) it's now coded as a user preference

**Comment by basil-twisleton** [comment]
Hi,
I have just implemented syspass for the first time and I am very happy with it so far. I have a couple of suggestions so far.

###### Search Page ######
1. The sorting headers do not line up with the content on the search screen (can be seen on the demo site).
2. Put the Access Rights Icon on the same line as the rest of the information (takes up additional space on a new line)
3. Would it be possible to show a custom field on the search page? 
4. Allow a text custom field to be stored un-encrypted (and thus make it searchable and possible to show on the search results as per point 3)


###### Adding Accounts ######
1. There is only a small pop-up which quickly disappears to confirm the account is created. If it is missed this can lead to duplicate accounts.. (which I have done a couple of time so far) I would suggest having two options for saving. Save and Close (takes back to the Query Page) alongside Save and New (which clears all the fields). A simpler approach would be to always clear all fields after a successful save.
2. Make Custom Fields visible/mandatory for certain Customers or Categories.


###### User Security ######
1. Multiple groups (Primary and Secondary).. At the moment it appears that a user can have a single main group (assigned on the User config tab) and then on the Group config tab the user can be added to multiple other groups. The result is the user can see all passwords for the other groups but has no access to the passwords. I dont think this was intended behaviour as if I set my user to multiple groups I can see the Accounts in the list but View the details or access the Passwords.


###### Backups ######
1. Allow for automated daily backup of the system (with possible retention period)


Please let me know if you have any queries and I will happily provide more feedback

Thanks,
Basil

**Comment by TechBlessings** [comment]
On thing that I would find to be very useful is if I could assign multiple categories to each entry. Or, alternatively, we could create free-form tags for each entry.

**Comment by nuxsmin** [comment]
To @basil-twisleton :

###### Search Page

1. You are right but the purpose of those headers are not to be aligned with the content, because it can be added new sorting headers that don't match the content displayed.
2. There are more icons than the access rights like notes, wiki links, attachments that are very used.
3. Yes but a new definition is needed to allow unencrypted data and new search filters (I'm thinking on special filters, not more inputs)

##### Adding Accounts

1. Fixed in latest commit/release
2. It's a bit difficult because the data grid is the same template for users, groups, profiles, etc. Let me think about that, there are many changes that affects to this template for the next release (you can check the "dev" branch)

##### User Security

1. Fixed in latest commit/release

##### Backups

1. You can do it better with system commands (mysqldump and tar). Delegating backups to a PHP script is "ugly" when there are better choices. BTW I'll post a recover/backup HowTo

##### View Password

1. You are right, the focus needs to be at the text area to copy...Let me try to find out what can be happening, because this plugin is quite recent (a time ago Flash were used...).

Thanks a lot for the feedback!! ;)

**Comment by nuxsmin** [comment]
Hi @TechBlessings , yes accounts tags are on the roadmap for the next release.

**Comment by basil-twisleton** [comment]
@nuxsmin, 
Thanks for your quick response, I have some more items I will post shortly :)

###### Search Page ######
1. You are right but the purpose of those headers are not to be aligned with the content, because it can be added new sorting headers that don't match the content displayed.
2. That makes sense, I just have the other features disabled/not used so it looked odd to me. 
3. The primary driver for this similar is to the concept of Tags as requested by @TechBlessings 

###### Adding Accounts ######
1. Great
2. Great. I will take a look. 

###### User Security ######
1. Great

###### Backups ######
1. Sounds reasonable. I was not sure if it was just a mysql dump, or what else was include in the PHP script.  

###### View Password ######
1. Sounds great. Looking forward to the update.

**Comment by basil-twisleton** [comment]
Some more points/thoughts
###### Login Screen ######
1. Ability to remember my username. I have LDAP auth enabled and it would be nice to have it remember my username. 
2. Single Sign on. As a further to the first point, it would also nice to have the option to enable SSO, especially when using LDAP. If the SSO fails then prompt for a username and password.

###### Copy Password Action on Search Screen ######
1. When logged in as admin I can see the 'Copy Password' action on the right side of (next to delete etc
![adminhascopyaction](https://cloud.githubusercontent.com/assets/2098465/10686570/ad3af5c0-7965-11e5-936e-00b2449e8208.JPG)
However when logged in as user who is a member of the Main Group I do not have the action.
![usermissingcopyaction](https://cloud.githubusercontent.com/assets/2098465/10686577/baafc5c8-7965-11e5-9f08-1a72cb662bf1.JPG)
This is the defined profile for the user (all other settings are off
![profilesettings](https://cloud.githubusercontent.com/assets/2098465/10686592/e9f0cda0-7965-11e5-81ec-9fa9493c0270.JPG)

###### Account Creation Page ######
1. When entering the password the hover over eye icon for viewing the password shows what appears to be the encrypted version. This doesn't make much sense. My suggestion would be to either show the entered password, or remove the icon
![viewpasswordshowsencryptedversion](https://cloud.githubusercontent.com/assets/2098465/10687129/e9602020-796a-11e5-803f-f6304a19da18.jpg)
2. Enable Password comparison before save button is pressed to ensure they match. Additionally when leaving either password field, rather than just when the save button is pressed. 
3. For the Customer, It is possible to both select a value and type in the field below. It is not clear which is used, but it appears to create the new customer. It would be great to have a blank option in the 'Select Customer' box to allow setting it back to blank if a new Customer is created. 
4. There is no indication that the Customer and Category are mandatory fields. All other mandatory fields show red until filled in.

###### Typo in English Help ######
1. In Configuration > Mail > 'Enable requests by email' help. **haven't** is misspelled havenn't
2. In Configuration > Backup > 'backup' help window. **configuration** is misspelled configuracion

###### Pop-up Help Windows ######
1. On the configuration pages (Encryption, Backup etc) that have a clickable help button. The window will not disappear if navigating to a new tab. You have no manually close them

**Comment by basil-twisleton** [comment]
@nuxsmin 
I have some more text suggestions referenced by tag number shown on the translations wiki page you have created. Some are updates to case to provide more consistency with similar fields(eg Tag 40 to match style used in Tag 39), others are simple typos, and there are also some grammar suggestions to make it more readable.

I have created a CSV which has Tag ID, Orginal Text and Suggested Text for you to review if you would like to make any of the changes however I cant upload it to this issue. 
I get Error: Attaching documents requires write permission to this repository. 

Please let me know how I can get it to you?

Thanks,

Basil

**Comment by nuxsmin** [comment]
Sure, you can send it to nuxsmin@syspass.org

My primary language is not english, so translations couldn't be accurate...

**Comment by basil-twisleton** [comment]
@nuxsmin,

Not a problem. Thought I would give you a hand with them. I went through all items in the list and have just sent you the file. 

Feel free to post me a message if you would like me to take a look at any tags in the future. 

Thanks,

Basil

**Comment by nuxsmin** [comment]
@basil-twisleton , about the points:

###### Login Screen

1. Because sysPass is a security application that tries to minimize/avoid some security risks, I thought about that behavior a time ago but it would involve the use of cookies with some user data. That is possible by encrypting the data, but I need to think how to accomplish it in a secure way.

2. SSO is great, but requires third party integration like CAS or NTLM. I would leave it for the next release (1.3)

###### Copy Password Action on Search Screen

1. There is no reason to not show that icon. I've tested it with the same conditions and the icon is shown. I don't know what could be happening...

###### Account Creation Page

1. You are right, the icon turns unusable due to that behavior (the password is RSA encrypted before being sent), but I need to do that when the input lost the focus instead of when submitting the form, because there is some strange behavior when doing in that step. This behavior is more related to a programming requirement.

2. I know that all forms need to be checked at both sides (client and server), but with HTML5 there is no need to check some of them, so I decided to delegate all those checks in HTML5 and on the server. This kind of fields (password) need to be checked on the sever side (because of the last point) , when the password is unencrypted using the RSA key and then encrypted with the Master Password, 

3. Let me think about that behavior, because when saving the account, it checks if the new customer input is not blank in order to create a new one.

4. You are right, it should turn red if no selection is done, but I think it's an issue of the select driver, because it uses a javascript plugin to show in that nice view.

###### Typo in English Help

1 and 2 will be fixed according to your email

###### Pop-up Help Windows

1. Yes this kind of dialogs are not modal (sticky instead) because they show some help that would be helpful during the action that you will perform, so closing them (or showing as a pop-up) would miss you some important information. 

Thanks so much for your feedback and support :wink:

**Comment by nuxsmin** [comment]
@basil-twisleton, regarding a previous post:

######  Search Page

1. These additional sorting headers are not actually set, but in a future, they could be. Eg.: sorting by count of views, by number of files, by date of creation/modification, etc. 

###### Backups

1. mysqldump is not used because I want a backup tool that were system independent, so it uses internal mysql functions instead.

**Comment by fwilly** [comment]
Hello nuxsmin,
I come back to me proposal no 3 from 9. October. (Quick copy values of any column). In keypass I can double click on a value to copy it to clipboard.

**Comment by ste-wil** [comment]
Is it possible to have log or area for previous passwords. In the event of error

**Comment by sintbert** [comment]
Hi, very nice Program, i'm actually trying it out in my company.

Some suggestions:

1. Let me assign multiple groups to a user.
2. Would be nice to set a AD-Group as source for a Group and automatically assign it to AD-Users.
3. For a account let me add multiple groups and select for each individually if they will be able to edit it.
4. Same for users in accounts.
5. As already written, deactivate the customer-textfield when there is one selected.
6. Why do i need the masterpassword to create a new account when it is in AD? Would be nice to get around that. Like import all AD-Accounts with the required AD-Group in Settings.

Thanks and Great Work :)

**Comment by voyager529** [comment]
I have a UI request:
Text labels on the buttons.

When trying to walk people through things on the phone, it's a lot easier to say "click 'settings' on the top', rather than 'the gear-like thing' or 'the magnifying glass', especially because people will come up with different names for those items, which makes it even more complicated. I love syspass otherwise (moved to it from Teampass), but the UI needs text labels in order to be exceptional.

**Comment by nuxsmin** [comment]
Hello @voyager529 ,

you're right sysPass isn't mobile friendly at all, actually I've two choices: work on a mobile friendly theme, or build a mobile app (in mind since a time ago).
The mobile theme could be a pain, because there are too much data to show and not all the browsers show it in the same way.
The mobile app would be hard, but it could implement some cool features through sysPass API, but not all functionalities.
I think that the last one could be the right way...

**Comment by nuxsmin** [comment]
Hello @sintbert 

I'me very glad that you like sysPass :)

Regarding your points:

> Let me assign multiple groups to a user

That's done in the group page.
> Would be nice to set a AD-Group as source for a Group and automatically assign it to AD-Users.

It would be a nice feature.

> For a account let me add multiple groups and select for each individually if they will be able to edit it.

I have been thinking about it, but it would be a time consuming feature and I let it because I needed to put the focus on code improvements.

> Same for users in accounts.

Idem
>  As already written, deactivate the customer-textfield when there is one selected.

Sure, it will be so on the next release.

> Why do i need the masterpassword to create a new account when it is in AD? Would be nice to get around that. Like import all AD-Accounts with the required AD-Group in Settings.

The master password is always needed because every account password is encrypted with it, and it isn't stored anywhere, so every user has an encrypted master password copy that allows to retrieve it when accessing to sysPass.

Thanks for the feedback and sorry for the late response (I didn't notice about it...).

Kind regards

**Comment by Titus1024** [comment]
Hello, I've recently set up syspass in my environment and I'm very happy with it, I think you've done a great job. Very easy to set up and and even easier to use.

A feature request that I can think of is the ability to build a category at the granular level, it's somewhat there already but there are some entries that don't need say a password, username or an IP/URL, they only need notes or details, or they only need a password but not a username.

Also another feature request that comes to mind if to either show the copy to clipboard from the main view for the accounts or to have an option to switch between showing it all the time or not.

![example1](https://cloud.githubusercontent.com/assets/22060361/18325100/e9851264-750d-11e6-8dfa-1a7519ebfcf2.PNG)
![example2](https://cloud.githubusercontent.com/assets/22060361/18325149/16c4e5ba-750e-11e6-9d39-ecf64718a5f4.PNG)


I do have one question regarding the customers and the details, I have created a bunch of extra categories for the customers module to show things like the address, contact information etc. but where can I view all of that information other than going to customer management or is that currently the only place to view it?

**Comment by nuxsmin** [comment]
Hello @Titus1024 

I'm very glad that you like it and find it useful.

Regarding your points:

> A feature request that I can think of is the ability to build a category at the granular level, it's somewhat there already but there are some entries that don't need say a password, username or an IP/URL, they only need notes or details, or they only need a password but not a username.

I know that you said, but it will  take a lot of time to code and the main purpose of this app is to store systems passwords and there are a few fields that mostly fit with every account and if you need to store more data it can be performed (as you know) by using custom fields. You and many others may think about keepass or lastpass replacement, but I want to get an useful password manager to be useful for IT tasks. Next release will implement many features like sharing accounts (by link), direct wiki access (dokuwiki), secure locking (using Latch), etc.

> Also another feature request that comes to mind if to either show the copy to clipboard from the main view for the accounts or to have an option to switch between showing it all the time or not.

That feature is already implemented in user's preferences page.

> I do have one question regarding the customers and the details, I have created a bunch of extra categories for the customers module to show things like the address, contact information etc. but where can I view all of that information other than going to customer management or is that currently the only place to view it?

Unfortunately custom fields are not searchable because they are stored in a different way. But I think they could be changed on upcoming releases.

**Comment by nuxsmin** [comment]
@Titus1024 ...thanks for the feedback!

**Comment by Titus1024** [comment]
Thanks for getting back to me so soon!  Much appreciated.

> I do have one question regarding the customers and the details, I have created a bunch of extra categories for the customers module to show things like the address, contact information etc. but where can I view all of that information other than going to customer management or is that currently the only place to view it?
>
That feature is already implemented in user's preferences page.

I have not seen this feature, has it been recently added? I believe I'm on the most recent version.


>    I do have one question regarding the customers and the details, I have created a bunch of extra categories for the customers module to show things like the address, contact information etc. but where can I view all of that information other than going to customer management or is that currently the only place to view it?

> Unfortunately custom fields are not searchable because they are stored in a different way. But I think they could be changed on upcoming releases.
>

Thanks, good to know. But are there any alternate ways of viewing the information stored in the customers profiles currently? As the only way I know of is to edit the customer it self in order to see the details.

**Comment by Ibmurai** [comment]
Hi,

I really like sysPass, and I am introducing it at my work place.

**1)**
I have been testing, doing some importing from CSV, as we have ~500 accounts I need to import.

If an error occurs during CSV import, it will have imported everything up to the point in the CSV where it had a problem... This would not be a problem if I had some way of mass editing the data... A quick fix for this would be to do the import in a transaction and simply roll back on error...

**2)**
I need a way to mass edit! After importing 200 passwords I notice it got into the wrong group. I now need to either edit each one individually or delete each one individually and reimport. My "workaround" is to import, import, import, fail, nuke db, reproduce working imports, try again, import, fail, nuke db... This works when starting up using it. But it will be more difficult, when we have been using sysPass for a year, and we suddenly need to regroup 200 exisiting passwords!

**Comment by nuxsmin** [comment]
@Ibmurai That feature has been implemented in sysPass v2
@voyager529 sysPass v2 is now mobile friendly
@fwilly Most of your suggestions have been implemented in sysPass v2

**Comment by nuxsmin** [comment]
This issue would be merged into #422

**Comment by twotwenty** [comment]
@Ibmurai That feature has been implemented in sysPass v2
I face a similar problem 
after mass imports of data from different password sources I need to do cleanup 
is there a feature for mass edit  or suggestions ?
