### ISSUE TITLE
Make Category private

### ISSUE THREAD

**Issue by codingSquare786** [nuxsmin/sysPass#1414]
**Category private**

It's possible to implement a private category for the user/groups?

For example, in my organization, the different teams need to have a separate " category group " that shouldn't visible for other teams

Thanks

Andrea

**Comment by nuxsmin** [comment]
Hello, categories were implemented as a filtering behavior, so there isn't any planned feature to make them part of the ACLs. Please use user groups instead, since they can be restricted per account and they could be nested in future releases.

There is another drawback on categories, since they would be replaced by tags, since the latter were implemented in order to build enhanced search filters, which weren't possible using categories because a legacy implementation.

Regards.
