### ISSUE TITLE
Provide username in force password change

### ISSUE THREAD

**Issue by Pip3queak** [nuxsmin/sysPass#1417]
**Is your feature request related to a problem? Please describe.**
New users don't get notified when accounts are created for them. Administrators have to copy and paste password for them to use.

**Describe the solution you'd like**
Put the user's username into mail notification of "Force password change" option so that users know their username when they receive their email.

**Describe alternatives you've considered**
Perhaps automatically generate temporary password for user in the email which also describes how long the temporary master password lasts for. This way the administrator does not need to do this manually.

**Additional context**

**Comment by nuxsmin** [comment]
Hello, users would be notified when admins do force a password change, then you can set a temporary user's password in the meantime.

I think that an automatically generated random password on "Force password change", would be an useful feature, but if you do that you're wiping the current user's password and then he/she will need to issue a request for a temporary master password, since master password is encrypted using the user's data.

Temporary master password (among master password) is a critical part of the application, and it might be managed by other admins than users admins, so the latter shouldn't be able to issue a temporary master password...

Thanks for the feedback!
