### ISSUE TITLE
Backup and restore User, Groups and Profils?

### ISSUE THREAD

**Issue by fwilly** [nuxsmin/sysPass#143]
I have export accounts and categories as xml and successful import it again.
But how works backup and restore of User, Groups and Profils.
I have make a backup where a tar archive of files and a sql dump is saved into backup folder.

1. How can I restore it by GUI? If I copy the files to backup folder of new instance they will be not displayed.
2. Can I select which data should be restored?

**Comment by nuxsmin** [comment]
Hi, the XML export is the only data that can be restored through the GUI, the database and app backup can be restored easily from the CLI (console).

The files are not shown in others instances because they contains an unique hash that only is known by the instance that created them.

The sql backup can be restored using this command:

<code>mysql -p < file.sql</code>

Take care that the database can be deleted in the process.

The app can be restored by uncompressing it in any place.

**Comment by nuxsmin** [comment]
This makes me think to write some wiki howto to restore sysPass data....

**Comment by fwilly** [comment]
I have restored users, groups and profiles
as well as users to accounts and groups to accounts relation.
In a better solution a selective restore should be possible.
One way could be a complete restore in a second database and get the data for selection and restore from there.

**Comment by nuxsmin** [comment]
Great!

About selective restore, it would be a hard work and usually if you want to restore, you perform a complete restoration because you don't know what could be wrong.

If I would have some time (or anyone wants), I could code that feature, but know I'm working on making sysPass more usable and adding popular features (it doesn't mean that yours aren't, but it would be rarely used).

Thanks for the feedback ;)

**Comment by Goatmaster** [comment]
I have done a Backup of the database and the folder on the webserver. Now I tried to insert it into another host (server), I also imported the database but if I connect to the new webserver it only shows the default apache page. 
Is there anything else to do?
I installed exactly the same php-modules like in my original host system.

**Comment by nuxsmin** [comment]
Hi, don't forget that the backup file stores the same path that you have in the old syspass instance, so it would have been restored to the same path.

Also check out the browser URL
