### ISSUE TITLE
Assign DevOps group to sysPass group

### ISSUE THREAD

**Issue by amokl** [nuxsmin/sysPass#1464]
sysPass Version: 3.0

Hello,
is it possible to assign a DevOps group (Ldap) to a group in sysPass? It looks like that we have to assign every single user to a group in sysPass, but not a complete imported group to a created passwords group.
We are using another passsword server for now, but we would gladly switch to sysPass and thats a must have for us.

kind regards
Chris

**Comment by nuxsmin** [comment]
Hello,

sysPass LDAP integration is only for user authentication, so no object tracking is performed. Why?, because it would require an additional service to re-conciliate sysPass data with LDAP, and since PHP's nature, it will require to do it on every request or develop a method to manually sync the data. It's a bit complex and many other known apps don't rely on syncing data, but only authentication instead.

Regards
