### ISSUE TITLE
Dokuwiki Integration

### ISSUE THREAD

**Issue by cschonga** [nuxsmin/sysPass#1514]
Greetings!

We have installed syspass and DokuWiki as docker containers The Wiki links feature is enabled with the settings

Wiki Search URL
https://docs.site.com/doku.php?do=search&id=start&q=

Wiki Page URL
https://docs.site.com/doku.php?id=

How does the Account name prefix work? Is there a wildcard we can use so all accounts link to a wiki page?

Also, some of the documentation mentions Dokuwiki API integration. Is this a plugin or is there a config file somewhere to enable Dokuwiki integration? How does that differ from wiki links?

Thanks,
Curtis

**Comment by nuxsmin** [comment]
Hello,

Wiki links work by using a prefix, so you can set several account prefixes and it will add a wiki icon on those accounts which name matches with the given prefix.

The Wiki search URL is used to search for the account's client using the Wiki.

Regarding the DokuWiki integration, it was removed from sysPass because I was very busy to maintain such feature and it makes me spend some time testing the Dokuwiki API, that would be suitable to change over the time.

Regards
