### ISSUE TITLE
New install w/ DOCKER (compose) - unable to connect to DB during setup

### ISSUE THREAD

**Issue by NOTORIOUSVR** [nuxsmin/sysPass#1528]
**sysPass Version**
3.1.1

**Describe the bug**
After using docker compose - instructions here: https://syspass-doc.readthedocs.io/en/3.1/installing/docker.html

Unable to continue setup due to not being able to connect to DB - PW is correct but it seems like the root user login is going to the wrong IP address (see red error bar in screenshot) syspass-db IP is actually 172.20.0.2) no idea how to change that during install

**Screenshots**
https://imgur.com/Ti6rH2n

**Platform (please complete the following information):**
 - OS: CENTOS 7
 - Browser: Chrome

**Comment by nuxsmin** [comment]
Hello, the message states that a user connecting from 172.20.0.3 is denied, so its correct, since database users are created  using the host they will connect from and not the database host.

Anyway, I'll try to find out why it's denying such user.

Regards

**Comment by dmpanch** [comment]
Same here.

[docker-compose example](https://gist.github.com/dmpanch/65b5c578b8b1465d33bf571a6408a52c)
[mariadb log](https://gist.github.com/dmpanch/c5eeedd7f12f88520903e64ceef2071c)
[syspass log](https://gist.github.com/dmpanch/c0e31c91041bc9d358c1ad5c9e158de1)
[docker inspect internal network]

**Comment by nuxsmin** [comment]
Thanks for the feedback @dmpanch !

**Comment by dmpanch** [comment]
Faced one more time with same error, but after the last time containers already was in the same network.

Connection to the database with root user made it possible to find out that the  user's IP address and host values, from which he can connect to the database, is stored in the database.

`SELECT host, user, password FROM mysql.user;`

```
+---------------+------------------+-------------------------------------------+
| host          | user             | password                                  |
+---------------+------------------+-------------------------------------------+
| 192.168.224.3 | sp_5eb44ae608f68 | *472BD4D37BA4F949BE27BB6BDCB4E88AEA0F0B15 |
```

It turned out that after restarting the server, the container received a different IP address and could not connect to the database. Solution here is to specify the desired address pool for the network and the static IP address for the syspass container.

Network part:
```
networks:
    web:
        external: true
    internal:
        internal: true
        ipam:
            config:
                - subnet: 192.168.224.0/24
```
Syspass container part:
```
        networks:
            internal:
                ipv4_address: 192.168.224.3
```


Also, the password in the syspass config was not the one that was recorded in the database, I had to change it manually (if I understood correctly, it's auto-generated).
