### ISSUE TITLE
LDAP Integration: "Wrong Ldap password"

### ISSUE THREAD

**Issue by Exxou** [nuxsmin/sysPass#1557]
I've installed syspass using the docker-compose.yml. As I tried to connect to my Ldap, I get the errror that I entered the wrong password even though it's the right one. 

![grafik](https://user-images.githubusercontent.com/66356932/83612786-2ba8c100-a583-11ea-8819-7e8ee52447cf.png)

**Comment by aszhitarev** [comment]
Hello
You must to insert your actually password and try to import
do not press button save!
only insert and import

**Comment by nuxsmin** [comment]
Hello,

as pointed @aszhitarev after saving the LDAP settings, it will set the paswword to `***` within the UI (security purposes), so if you need to import users (not really needed because any user will be imported during login), you need to set the password in the box, but this time you don't need to press the "Save" button, because the password was already saved.

Regards
