### ISSUE TITLE
Unable to install on XAMPP Windows 

### ISSUE THREAD

**Issue by davidjimenez75** [nuxsmin/sysPass#1565]
**sysPass Version**
sysPass-3.1.2.20030701 (ZIP)

**Describe the bug**
Can't start the installation, 2 warnings about LC_MESSAGES on top.

``
Warning: Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' (this will throw an Error in a future version of PHP) in C:\IMASD\syspass.zonagrafica.com\lib\SP\Core\Language.php on line 186

Warning: setlocale() expects parameter 1 to be int, string given in C:\IMASD\syspass.zonagrafica.com\lib\SP\Core\Language.php on line 186
``

**To Reproduce**
1. Download the sysPass-3.1.2.20030701.zip
2. XAMPP v7.3.19
3. Add mcrypt 1.0.3 for Windows dll to xampp (php_mcrypt-1.0.3-7.3-ts-vc15-x64.zip)
4. Descompress and execute: composer install 
5. Open on browser install URL and show 2 warnings on top of header and installation can't proccess.

**Platform (please complete the following information):**
 - OS: Windows 
 - OS Version: 10
 - Browsers: Firefox + Chrome

**Additional context**
¿Incompatible with XAMPP Windows?

**Comment by nuxsmin** [comment]
Hello,

Unfortunately I haven't tested sysPass on XAMPP so I haven't any feedback about how it runs on this platform.

Regarding the `mcrypt` module, this isn't needed at all, since sysPass relies on OpenSSL for encryption, and unless you want to use an old sysPass instance data or import an old XML file, it can be skipped from installing.

The locale warning is because it expects to be defined within the PHP environment, but this warning can be skipped.

Regards.

**Comment by davidjimenez75** [comment]
Thanks, I have solved with this dirty hack

FILE: \lib\SP\Core\Language.php
```
    public static function setLocales($lang)
    {
        $lang .= '.utf8';           
        define('LC_MESSAGES',null); //TO-DO: avoids errors on installation on XAMPP Windows (v7.3.9)
        self::$localeStatus = setlocale(LC_MESSAGES, $lang);
```

**Comment by nuxsmin** [comment]
Thanks for the feedback @davidjimenez75 !!

You could set it better in `lib/Base.php` file, because once defined it can be used across all the app code  :wink:
