### ISSUE TITLE
master-password and ldap-users

### ISSUE THREAD

**Issue by goro22052** [nuxsmin/sysPass#1577]
I have the problem.
When ldap user entering the syspass he sees prompt enter login and password again and master-password.
But if the user entered login, password again and new master-password he sees "wrong master password."

**Comment by morevsky** [comment]
I confirm
Is there any solution to the problem?

**Comment by nuxsmin** [comment]
Hello,

that is not an issue, since once the user enters the login data, sysPass need to check if it has the correct master password within the user's data, if not, it will return asking for the master password. Why does it blank the fields?. Because a security reason, since it could be any automated mechanism trying to brute force the log in, so it's a good (an safe practice) to blank any wrong field.

Regards
