### ISSUE TITLE
Wrong Master Password set

### ISSUE THREAD

**Issue by Optimaximal** [nuxsmin/sysPass#1578]
I reset the master password using the System Configuration> Encryption interface as the one generated was lost (my bad), generated a new one using the UI and pasted the output into Notepad as a holding area.

Either Notepad has changed the encoding of the values so they don't match or, for some reason, the new master password was not saved correctly in the database.

How can I brute-force reset the master-password so that I  can log in and set a new one as the system admin account? I'm not in production yet, so the few passwords I have are held elsewhere in another password manager and can be junked.

**Comment by Optimaximal** [comment]
Ok, just testing things, I deleted the Master Password out of the SQL table in PHPMyAdmin. Obviously incorrectly, I assumed that if I It let me log in by pasting in the old master password, but now I cannot reset the master password - the fields are blank.

So I think i've found a bug there.

**Comment by nuxsmin** [comment]
Hello,

master password tests has been passed for each release (even for each push to the repository), so something went wrong when entering the new password. Do you know how many characters did it have?.

About resetting the master password (the hashed master password indeed) from the database, I think it isn't a bug, since harming the application core base would break it and there is no expectation about recovering without a backup.

Regards
