### ISSUE TITLE
Shell update script

### ISSUE THREAD

**Issue by CyrosX** [nuxsmin/sysPass#161]
Hello there!
This is not an issue but I didn't know where else to submit it.
I've made thise little shell script for updating sysPass.
Maybe someone can use it or optimize it :+1: 
You need to create the folder sp-update!

```
cd /var/www/html/sp-update/
wget https://api.github.com/repos/nuxsmin/sysPass/tarball/master -O new.tar.gz
tar -xzf new.tar.gz
rm new.tar
mv /var/www/html/sysPass /var/www/html/syspass-old
mv * /var/www/html/sysPass
cp -afvr /var/www/html/sysPass-old/config /var/www/html/sysPass
cp -afvr /var/www/html/sysPass-old/backup /var/www/html/sysPass
rm -R /var/www/html/sysPass-old
chmod +750 /var/www/html/sysPass/config
chown www-data:www-data -R /var/www/html/sysPass
chown www-data /var/www/html/sysPass/config
chown www-data /var/www/html/sysPass/backup
```

**Comment by nuxsmin** [comment]
Thanks so much for sharing it, I can write a short howto in the wiki to give some instructions about how to update sysPass by using this script.

Kind regards.

**Comment by basil-twisleton** [comment]
Hi @CyrosX,
I just used your script and it is very quick, I did find two issues though (bold lines below).
1. Missing .gz extension on the tar. 
2. Different case used on the backup folder syspass-old vs sysPass-old

_cd /var/www/html/sp-update/
wget https://api.github.com/repos/nuxsmin/sysPass/tarball/master -O new.tar.gz
tar -xzf new.tar.gz
***rm new.tar.gz***
***mv /var/www/html/sysPass /var/www/html/syspass-old***
mv * /var/www/html/sysPass
cp -afvr /var/www/html/sysPass-old/config /var/www/html/sysPass
cp -afvr /var/www/html/sysPass-old/backup /var/www/html/sysPass
rm -R /var/www/html/sysPass-old
chmod +750 /var/www/html/sysPass/config
chown www-data:www-data -R /var/www/html/sysPass
chown www-data /var/www/html/sysPass/config
chown www-data /var/www/html/sysPass/backup_


I would also suggest not automatically cleaning up the old version as part of the script. better to test the site for functionality first.

**Comment by nuxsmin** [comment]
Hi, I've just published it in the sysPass wiki http://wiki.syspass.org/en/contrib

What do you think?

**Comment by basil-twisleton** [comment]
Looks good, still the case typo in the mv line
mv /var/www/html/sysPass /var/www/html/syspass-old

Should read
mv /var/www/html/sysPass /var/www/html/sysPass-old

Otherwise all looks good :)

**Comment by CyrosX** [comment]
Thanks @basil-twisleton :) 
Maybe you're right with not deleting old-syspass.
Adding the option -i let's the user choose  what to do:

rm -ir /var/www/html/sysPass-old

Nice to see that it seems to be useful. :) @nuxsmin 
I was thinking about a script to check if there is a new version automatically, which could activate the update script, but I must do some more research about the links etc. github provides to make this possible.

**Comment by nuxsmin** [comment]
Hi, I've updated the script to make it a bit more secure by avoiding to delete the old folder and renaming it with an unique name by using an UNIX timestamp, so you can run it several times without any risk.

About checking for updates, it's pretty difficult from the command line, because you would need to check the current release from a PHP file and then compare it to github latest release by using a regex. This needs to be done with curl (not installed by default on some OS), because github API needs some special parameters.

**Comment by CyrosX** [comment]
I've found a mistake. It produces a folder in folder problem with the command: "mkdir ../sysPass".
You can leave it out. When using "mv ./* /var/html/www./sysPass" it creates a folder automatically.
And why is there a "read" command at the end?

**Comment by bitking** [comment]
Thanks a lot, gonna try the script soon.

Are you still looking into the update check? curl prerequisite is no problem for me.

**Comment by vmario89** [comment]
hey guys, from this issue is there any open action point? The only point i could extract from this issue would be on how to make some update-check if a new release is out there. in sysPass v3 you can see it visually if there is something new. Regarding to this, sysPass application could just write some key into config.xml which stores the <currentAvailableUpdateVersion> next to <configVersion>. This entry could be used for background tasks (so no need to cURL the string from github this way), for example automated application upgrade (if this would be good is another question).

**Comment by nuxsmin** [comment]
Thanks @vmario89 :wink:
