### ISSUE TITLE
Maximum size per file is 16MB

### ISSUE THREAD

**Issue by AbiertaMente** [nuxsmin/sysPass#1642]
**sysPass Version**
3.2 (320.20122001)

**Describe the question**
Maximum upload file size is hardcoded in app/modules/web/Controllers/ConfigAccountController.php:74
Even if changing php.ini max file size values, sysPass limits to 16Mb.
We are storing VPN clients in some accounts and some files can reach even 60mb. Why not use 

$max_upload_size = ini_get('upload_max_filesize');

or something similar and pass the "16M" as argument to __u command?

**Platform (please complete the following information):**
 - OS: [CentOS 7]

**Comment by nuxsmin** [comment]
Hello,

unfortunately it's a limit imposed by the database since `MEDIUMBLOB` type fields (https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html#data-types-storage-reqs-strings) have a maximum size of 16MB. It could be increased by using a `LONGBLOB` type field, but you need ti be aware that sysPass is not intended to store files and the database is not the best way to store such huge files.

Why are files stored in the database?: because it's an easy way to make them portable and it doesn't require any additional configuration (separated volume, directory hierarchy, metadata, etc.) and it could be more secure by storing them in a database dedicated host separated from the web host.

Regards
