### ISSUE TITLE
Feature - Enable requests by email

### ISSUE THREAD

**Issue by gleisonbaioco** [nuxsmin/sysPass#167]
Hi @nuxsmin 

How "Enable requests by email" feature works?

**Comment by nuxsmin** [comment]
Hi @gleisonbaioco 

this feature allows to those users that don't have any rights on the accounts to send a request to the account's owner and to the last editor. In order get it working, you need to enable "Global Account Search" and email notifications, because users need to be able to search for all accounts, even if they don't have any rights.

**Comment by gleisonbaioco** [comment]
Hi @nuxsmin 

Thank you for your explanation.

**Comment by nuxsmin** [comment]
You're welcome ;)
