### ISSUE TITLE
Security Fail

### ISSUE THREAD

**Issue by BerMan7328** [nuxsmin/sysPass#1747]
**sysPass Version**
3.2 (322.21031301)
Config: 322.21031301
App: 322.21031301
DB: 322.21031301

**Describe the bug**
In the config.xml file in /var/www/html/sysPass/app/config I can see sensitive data like DB password, ip, port  and user; ldap server  user, ip and password; and sensitive data of the email server to.

**To Reproduce**
cat config.xml

**Expected behavior**
Expect  sensitve data are hashed

**Platform (please complete the following information):**
Centos 7

**Comment by markwbrown** [comment]
chmod -R 750 /var/www/html/sysPass/app/config

**Comment by BerMan7328** [comment]
that doesn't solve the problem. Because the volume is in a container, a potential attacker could easily run docker container exec -u root and access the config's sensitive data.xml

**Comment by nuxsmin** [comment]
Hello @BerMan7328 

Unfortunately the services password need to be in clear text, that's so for whatever app you deploy because hashed passwords are that, a hashed string (only one direction algorithm, cannot be unhashed...), so the only way to connect to any service is using the "real" password, and not the hashed one.

Please take a look to any config file in our OS and you will see some passwords too.

The only way to protect the config file is by setting the proper permissions, and keeping as secure as possible your sysPass VM or container.

Thanks!
