### ISSUE TITLE
is the project still active?

### ISSUE THREAD

**Issue by pierrehenrymuller** [nuxsmin/sysPass#1752]
Hi Nuxsmin,

I see many issues and merges requests that accumulate.
Don't take this the wrong way, but I'm wondering if you can still devote time to the project?
Maybe you should open one or two maintainer roles for delegate?

We are going through a complicated period, I hope that it is not that which affects you.

**Comment by nuxsmin** [comment]
Hi Pierre-Henry!

Thanks for asking about the project and me. Hopefully, it's all okay, though some inactive time because the hard work and the need of a relaxing time from coding and stay with the family.

I've been working on next major version which will have some useful features, like CLI commands, some configuration from environment variables, SSO, and many others.

Regarding the maintainers, it's a bit complicated since there isn't much contributions here, so I'd like to delegate to anyone that has a slightly deep knowledge about the code, and some hands-on coding the app. 

Kind regards

**Comment by pierrehenrymuller** [comment]
I am satisfied, thank you for the message.
:D
