### ISSUE TITLE
sysPass 1.2 do not work with any Apache auth

### ISSUE THREAD

**Issue by TitovLab** [nuxsmin/sysPass#180]
Always use sysPass with Apache Kerberos auth.
Version 1.1 works like a charm.
Version 1.2 do not work at all if web-server have any auth (test with Kerberos and basic auth).
sysPass 1.2 show login page, but after log in show login page again without any errors.
Example Apache config:
<VirtualHost *:443>
DocumentRoot "/var/www/html/syspass.test.ru/www/"
ServerName syspass.test.ru:443
SSLEngine on
SSLOptions +StrictRequire
SSLProtocol all -SSLv2 -SSLv3 -TLSv1
SSLCipherSuite ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK
SSLCertificateFile /etc/pki/test.local.crt
SSLCertificateKeyFile /etc/pki/test.local.key
SSLVerifyClient none
SSLProxyEngine off
<Files ~ "\.(cgi|shtml|phtml|php|php3?)$">
    SSLOptions +StdEnvVars
</Files>
SetEnvIf User-Agent ".*MSIE.*" \
nokeepalive ssl-unclean-shutdown \
downgrade-1.0 force-response-1.0
<Directory /var/www/html/syspass.test.ru/www/>
    SSLRequireSSL
    AuthUserFile /etc/.htpasswd
    AuthName "Restricted Area"
    AuthType Basic
   Require valid-user
</Directory>
</VirtualHost>

Error in Apache log:
PHP Warning:  Cannot modify header information - headers already sent in /var/www/html/syspass.test.ru/www/inc/Minify.class.php on line 149, referer: https://syspass.test.ru/index.php

**Comment by nuxsmin** [comment]
Let me do some tests on an environment like that to see what is happening.

**Comment by nuxsmin** [comment]
Good news, it seems to be fixed...the app was checking the user id instead login when webserver auth was performed.

Can you check if it works?

**Comment by TitovLab** [comment]
No, latest commit and all sysPass 1.2 builds do not work if Apache use any auth.
sysPass 1.1 works fine.

**Comment by nuxsmin** [comment]
Hi, did you use the same username for webserver auth and sysPass?

**Comment by TitovLab** [comment]
Yes and no.
I tested sysPass 1.2 with Apache Kerberos auth and sysPass LDAP auth - so the username are the same.
And also I tested sysPass 1.2 with Apache Basic auth and sysPass MySQL auth - so the username was different.

**Comment by nuxsmin** [comment]
Ok, I've tested it with Apache Basic, and the username should be the same.

Apache Kerberos was not tested because it needs Kerberos aware environment and it needs some config.

PHP relies the auth to some internal variables like "PHP_AUTH_USER", "PHP_AUTH_PW" and "AUTH_TYPE" for Basic and Digest Auth, but with Kerberos the "REMOTE_USER" and "AUTH_TYPE" are the only variables set, so with Kerberos there would not be SSO, because sysPass need the user's password to unlock the master password.

I can tweak some features like SSO with Basic auth (actually only checks if the username is the same), but the other methods can't be used because the user's password is needed.

**Comment by TitovLab** [comment]
Thank you!
It is a pity, if Kerberos auth can not be used for SSO. Kerberos auth with SSO will be very useful, many web-applications use it (OTRS, WiKi and so on).

**Comment by nuxsmin** [comment]
You're right,  but, because the non-stored  master password behavior, the application need to know it in some way,  so the user's  password (and other  data) is used to store it in an encrypted way.

Let me think about an SSO feature without security risks.

Kind regards

**Comment by nuxsmin** [comment]
Related #101

**Comment by TitovLab** [comment]
One more thing: latest commit works with basic Apache auth if username for sysPass and Apache are the same.
sysPass 1.1 works if username for sysPass and Apache are same and different.
Question: will sysPass 1.2 work with different username for Apache auth and sysPass (question not about SSO)?

**Comment by nuxsmin** [comment]
Yes, it's so because it enforces the security, but I know that it would be better if you can control that behavior, but the sso behavior won't be achieved if the user needs to provide the master password.

**Comment by aenima-x** [comment]
Hello, doing this you still need to enter a syspass password? Or It trust in the Web server auth user and use that user for syspass?
Also, Is there a way that syspass dont asks for the master password on the first login?
thanks

**Comment by nuxsmin** [comment]
Hello @aenima-x

The web server authentication is used to get only the username because the user's password is needed to get the master password. You may think in that as an additional authentication filter.

The master password is needed to decrypt the accounts passwords. It only will be requested when the user changes its own password and when the admin changes the master password. You can provide a temporary master password to avoid to tell the real one.

**Comment by mikhailnov** [comment]
Sorry for writing here, but I can't understand: if an end user machine (Linux OS) has a valid Kerberos ticket, Apache httpd and Chromium/Firefox web browsers are configured for kerberos authentication, will the user be able to open syspass without entering neither login nor password?

**Comment by nuxsmin** [comment]
@mikhailnov Hello, as said in last comment, an unique and time-persistent data must be provided in order to encrypt the master key, so a Kerberos ticket won't provide such kind of data.

sysPass data are always encrypted and only unlocked when any user need them, so the master key is always needed to decrypt the stored data.

Regards

**Comment by netsliver** [comment]
Hello,

on version 3.1 I want to use an sso with kerberos, but I see that the code tries to have the variable PHP_AUTH_PW, can we make it optional?

Regards
