### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [nuxsmin/sysPass#1825]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@nickshadows) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by nuxsmin** [comment]
Hello @JamieSlome,

You're right, I'd be useful to create such `SECURITY.md` file in order to let you know how to send this kind of details, though right now I'm the only developer for this application and my email is set all over the code :)

In the meantime you can send it to nuxsmin_at_ syspass_dot_org.

Thanks for your contribution!!

**Comment by JamieSlome** [comment]
@nuxsmin - awesome, appreciate your response!

I have sent an e-mail to the address stated above 👍
