### ISSUE TITLE
Installing SysPass on Ubuntu 24.04

### ISSUE THREAD

**Issue by sikas89** [nuxsmin/sysPass#1931]
**sysPass Version**
Latest

**Describe the question**
I'm trying to install SysPass on Ubuntu 24.04 ..

> syspassadmin@syspass:/var/www/html/syspass/app$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

However, upon completing the installation, it doesn't work. First, I had to download **_PHP8.3_** not **_PHP 7.0_** as it is not available. I followed the steps, and had to also download other packages like **_7zip_** and **_7zip-rar_** to be able to run "**_php composer.phar install --no-dev_**" with no issues.

Upon completing, I faced the error: "**_Unable to write in file (/var/www/html/syspass/app/config/config.xml)_**" on the browser. I'm currently stuck and can't use the service.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - OS: Linux Ubuntu
 - OS Version: 24.04
 - Browser: Google Chrome

**Additional context**
N/A

**Comment by Sampersp** [comment]
Hi, how are you? The problem you are having is because in the path where you are, the folders have to have certain permissions and privileges.

the error: "Unable to write in file (/var/www/html/syspass/app/config/config.xml)"

It indicates exactly what it says, the user with whom you are doing the installation does not have sufficient permissions on the existing folder or subfolders.

What you have to do is the following:

- If you are using webmin to administer the Ubuntu server you are working with, just go to the path: /var/www/html/syspass/app/

Once located on the syspass folder, proceed to assign permission 0775 to the app subfolder. Once this is done, enter that folder and change the following permissions to the following folders:

- cache 0777
- config 0750 owner www-data:root (click on recursive) and finally make sure that the config.xml file has the permission 0644

With this, then proceed to reload the page and you can continue with the installation process.

Greetings!

**Comment by sikas89** [comment]
> Hi, how are you? The problem you are having is because in the path where you are, the folders have to have certain permissions and privileges.
> 
> the error: "Unable to write in file (/var/www/html/syspass/app/config/config.xml)"
> 
> It indicates exactly what it says, the user with whom you are doing the installation does not have sufficient permissions on the existing folder or subfolders.
> 
> What you have to do is the following:
> 
> * If you are using webmin to administer the Ubuntu server you are working with, just go to the path: /var/www/html/syspass/app/
> 
> Once located on the syspass folder, proceed to assign permission 0775 to the app subfolder. Once this is done, enter that folder and change the following permissions to the following folders:
> 
> * cache 0777
> * config 0750 owner www-data:root (click on recursive) and finally make sure that the config.xml file has the permission 0644
> 
> With this, then proceed to reload the page and you can continue with the installation process.
> 
> Greetings!

Thanks! I've been able to successfully finalize the installation of SysPass.
