### ISSUE TITLE
Event bindings, submitting search

### ISSUE THREAD

**Issue by alexanderbuhler** [nuxsmin/sysPass#198]
Hey there,

I found the event bindings on the search form to be quiet inconvenient. At first, the permanent search trigger on "keyup" often produces empty responses because it's flooding the api which is still processing the request from the last letter input. I had to make some dirty changes to it since I wasn't able to find the spot where event bindings happen.

After debugging in real time I got this:

```javascript
        $('#frmSearch select').on('change', function (e) {
            sysPassUtil.Common.clearSearch(1);
            sysPassUtil.Common.accSearch(0, e)
        });

        $('#frmSearch #btnClear').click(function (e) {
            sysPassUtil.Common.clearSearch();
            sysPassUtil.Common.accSearch(0, e);
        })

        $('#frmSearch input:text:visible:first').focus();
        $('#frmSearch #txtSearch').on('keyup', function (e) {
            sysPassUtil.Common.accSearch(1, e)
        });
        $('#frmSearch #rpp').on('change', function (e) {
            sysPassUtil.Common.accSearch(0, e);
        })
```

It's getting minified somewhere, right?

You should throttle search requests after keyup with like >500ms or even start search just after submit by Enter key. Which leads to the next problem: The search form element not having a <input type="submit" prevents using the Enter key as submit option.

So at this point, I was just adding the input type="submit" dynamically and then got another bug in my way. The 6-step (why on earth is post/page count bound to steps of 6??) post/page number on search page conflicts with the amount you can set in the user options => also 6-step but with a different offset.

Now, the #rpp is beeing reset to steps of 1 to enable search by enter key.

The workaround code looks like this:

```javascript
        sysPassUtil.Common.clearSearch();

	$('#frmSearch #txtSearch').unbind('keyup');
	$('#frmSearch #rpp').attr('step',1);

	$('#frmSearch').attr('onsubmit','').on('submit',function(e) {
		e.preventDefault();
		sysPassUtil.Common.accSearch(0);
	}).append('<input type="submit" style="display: none">');
```

I would really love to this this point improved, since this workaround only hooks at page load and is getting overwritten any time you trigger the search menu icon.

Regards
Alexander

**Comment by nuxsmin** [comment]
Hi there, nice to see an interesting analysis about that behavior.

It's right that this wouldn't be the best approach to perform continuous searching and can lead to some annoying issues like that, but I think that blank responses are because the security token is not retrieved as quickly as the request does, so I changed it in the development version (1.3) then it will be retrieved in a json object and not as a hidden input....

BTW, it's easy to implement some kind of switch to disable continuous searching.

About paging step, it's done so because in cards style view the rows are more visually consistent if they have 3 cards per row (at an standard resolution)

Kind regards

**Comment by alexanderbuhler** [comment]
Sounds like a solution, it would be great to have more options for the behaviour.
Looking under the hood the application looks very structured and solid. We made some changes to the search so that users aren't allowed to see and edit entries other users in their group created (This was my last issue opened btw ;-)) - it was 2 lines of code.

In the very nature of a single page application, everything seems to be API-driven. This groundwork is a good starting point to maybe build and implement an UI concept from scratch, since the current interface looks very chaotic/patchworked. I'm willing to help you with that - bringing some deeper concept and frontend code experience to the table.

Another thing to consider is implementing popstates/history, so you can also navigate with your browser. It can be very annoying to land on an empty tab after using backspace ;-)

**Comment by nuxsmin** [comment]
I didn't mean it can be a solution...it can mitigate the behavior but I know that the code can be improved to make things work better. You can take a look to the devel branch and take an idea how it has been improved (PSR4, abstract Datagrid, object caching, etc..)

You are right, there are some features that avoid deep linking and backspace behavior, but I didn't want to use a Router, because it would push the user to make some config on the webserver side, but it would be nice to have friendly URLs.

It would be great to get some feedback/support on UX or whatever you want...

Kind regards

**Comment by nuxsmin** [comment]
The unpacked JS code can be found at https://github.com/nuxsmin/sysPass/blob/master/js/functions.js

**Comment by alexanderbuhler** [comment]
Thanks, but I don't see the mentioned event bindings in there?

**Comment by nuxsmin** [comment]
You're right, I have been pointed there because that is the minified file that contains the search binding logic, but the event bindings takes place in the theme template file https://github.com/nuxsmin/sysPass/blob/master/inc/themes/material-blue/searchbox.inc (I thought that you have already seen it because it wasn't minified)
