### ISSUE TITLE
Logout with backwards navigation browser button

### ISSUE THREAD

**Issue by esmeralda7** [nuxsmin/sysPass#212]
Hello,

I'm using syspass on a debian linux server, i noticed a strange behaviour but maybe i'm wrong.
Every time i hit the backwards navigation button on my browser i log out of syspass. Is this a normal behaviour?

Thanks,

E

**Comment by nuxsmin** [comment]
Hello,

This is a normal behavior, because since sysPass uses a front controller pattern, the content is loaded in a single page via Ajax requests.

The only time that reloads it self is when you perform a logout, because it clears all session variables so I need to tell the app when to perform a logout via GET variables (within the URL) and show a message, because at this time session variables has been cleared.

This behavior pushes a history entry, so if you go back you will get that page with the logout variable at the URL. One way to avoid it is by clearing the tab history (within the code) but it's very ugly....

**Comment by esmeralda7** [comment]
Thanks again! I'll probably have to ask you a question about compatibility issues with internet explorer 11...

**Comment by nuxsmin** [comment]
Shot them ;) (it could be some issues with IE11 because syspass has been poorly tested on it)

**Comment by esmeralda7** [comment]
Ahah ok thx :)
