### ISSUE TITLE
Release of the new version 1.3

### ISSUE THREAD

**Issue by cgriva** [nuxsmin/sysPass#217]
Hi,

When are you out the new version 1.3

Thanks

**Comment by nuxsmin** [comment]
Hi, that is a good question...

I think that I'd would be ready by the end of June, because actually I've too much work.

About the development, it's almost finished but there are some improvements, code testing and translations that need to be done before releasing it.

BTW, I'll launch a testing site to get some feedback about it.

**Comment by cgriva** [comment]
thanks your answer.

see you later

**Comment by MikeyHoef** [comment]
Hi @nuxsmin 

Can you give us a status update? Or is there anything we can help with, testing or something?

See you!

**Comment by nuxsmin** [comment]
Actually, I've been solving some issues related with the 1.2 version, so I'll need to reschedule the 1.3 release.
I'll tell you a date shortly

**Comment by nuxsmin** [comment]
Coming soon  ;)

**Comment by mkola-greenliff** [comment]
Hi,

Any updates regarding release date of 1.3 ?

Thanks,
Mathias

**Comment by nuxsmin** [comment]
1.3 release will upgraded to 2.0 because the major code changes that has been done on it.

It was released yesterday as 2.0-beta
