### ISSUE TITLE
Documentation request: Active Directory integration

### ISSUE THREAD

**Issue by yahalom5776** [nuxsmin/sysPass#228]
Hello,

first of all: Thank you to all contributors for this great software. I would like to setup AD integration but right now I am struggling a bit with that. Is the procedure described here http://wiki.syspass.org/en/ldap (incl. setting up an OpenLDAP server) mandatory? Perhaps you could clarify the documentation in this regard.

Thank you!

Kind regards,
Yahalom

**Comment by nuxsmin** [comment]
Hello! I'm very glad that you found sysPass useful.

About LDAP you can configure it to use AD or openLdap. There isn't a mandatory setup but I wrote that howto to get a decent LDAP authentication by using groups.

Kind regards

**Comment by 48kRAM** [comment]
I encountered an issue with Active Directory mode in the LDAP config. When AD is set to on, the 'ldap server' field is treated differently. In AD mode, the code tries to locate the AD servers via DNS service record lookups, but it fails in my environment. I haven't figured out quite why yet, but simply changing the code to not treat the ldap server differently in AD mode as me connected to AD now.

**Comment by nuxsmin** [comment]
Hi @48kRAM

AD LDAP server is picked from the DNS records because it allows to pick a random sever within the domain for every login, so it enhances the risk to fail because an unreachable DC.

You can avoid this feature by setting a DC IP address, so it means that you want to use one DC server only.

BTW take a look to your domain health because many DNS issues or slowdowns are related to missing DCs or wrong settings.

**Comment by 48kRAM** [comment]
Our DNS is set up correctly for AD. Not sure why the syspass code isn't discovering our DCs. It looks right from reading it and testing the query does return records. Weird...  I'll have to look into it further later.
