### ISSUE TITLE
Personal Passwords

### ISSUE THREAD

**Issue by jcboysha** [nuxsmin/sysPass#229]
Is it possible for a user to have a password saved that is only viewable by that user and no one else in their group or otherwise?

**Comment by nuxsmin** [comment]
At the moment there isn't such feature. This has been discussed a time ago, because if you are using sysPass in a business environment, it means that passwords belongs to the company, so if you let the users to own passwords it wouldn't be recovered unless you get the master key...(think about fired employees).

I think that it's a big security risk, but I'll code some hack to enable personal passwords...

I understand by "no one else" that admin can't also get it, right?

**Comment by jcboysha** [comment]
Correct.

**Comment by MikeyHoef** [comment]
When do you think this feature is enabled??? We prefer this feature too!! :+1:

**Comment by LeDistordu** [comment]
To keep control for this feature I think we should be able to activate or not on profiles

**Comment by nuxsmin** [comment]
Work in progress...

**Comment by nuxsmin** [comment]
Done in sysPass 2.0-beta
