### ISSUE TITLE
backup - export sql database - how to import ?

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#231]
hello

I've a suggestion:
can You implement some sort of scheldued sql backups also in syspass? It woulbe be nice to have backups ready to restore directly from webpasnel

Is there an option to restore sql database directly in syspass ? i'm trying to avoid installing phpmyadmin and so on (it can be done in shell, but we all like point and click systems; also there is export page, and sql import would be great complementary for SYSPASS)

/Thank You/

**Comment by nuxsmin** [comment]
Hello,

A sort of scheduled backup is quite complex because PHP nature, the server code is not executed in background (every piece of code is executed as it's requested) so there isn't such scheduler, so it needs external tools like cron to get it.

You can easily schedule a backup by using mysqldump and cron.

An import option would be nice, but you may think that the sysPass db user doesn't have database admin rights, so you would need to provide an admin username. Also you can't perform the import in the same database...
