### ISSUE TITLE
Import / Export 

### ISSUE THREAD

**Issue by cruggieri** [nuxsmin/sysPass#239]
Could be useful to have a "export / import" functionality, from CSV just for starting.
Import could be on a static standard fields layout.

Whay do you think?

**Comment by nuxsmin** [comment]
Sure, but you can perform a CSV import from the import tab in the config section.

The export function is done in XML format, because it's more flexible and you can import it without any data loss. CSV export can loss some data because the field separator can be a pain with some text fields like notes.

**Comment by cruggieri** [comment]
Ok. Is documented somewhere which fields layout I have to use?
For example: 
"Account Name";"login";"password"; ... and so on.

**Comment by nuxsmin** [comment]
Right, you can read it by pressing the help button on that tab.

**Comment by cruggieri** [comment]
Thank you. I'm really blind! :D

**Comment by nuxsmin** [comment]
You're welcome... don't worry, keep in mind that all basic help data can be get through help buttons. 

If you need more help, take a look to wiki.syspass.org
