### ISSUE TITLE
changed settings to force https, saved setting, page not loading[!]

### ISSUE THREAD

**Issue by akurzawa** [nuxsmin/sysPass#259]
I've changed syspass to force https, saved setting, page not loading
how to fix it? 
how to switch syspass to https and not broke whole system? there is nothing on wiki

why syspass is so poorly documented? wiki literally covers only install procedure, nothing more

apache error log:

```
[Wed Aug 24 04:10:57.342437 2016] [:error] [pid 865] [client 192.168.1.165:59377] PHP Warning:  file_put_contents(/var/www/html/ipm/config/key.pem): failed to open stream: Permission denied in /var/www/html/ipm/inc/CryptPKI.class.php on line 79
[Wed Aug 24 04:10:57.353723 2016] [:error] [pid 865] [client 192.168.1.165:59377] PHP Warning:  file_put_contents(/var/www/html/ipm/config/pubkey.pem): failed to open stream: Permission denied in /var/www/html/ipm/inc/CryptPKI.class.php on line 80
[Wed Aug 24 04:10:57.353768 2016] [:error] [pid 865] [client 192.168.1.165:59377] PHP Warning:  chmod(): No such file or directory in /var/www/html/ipm/inc/CryptPKI.class.php on line 82
[Wed Aug 24 04:10:57.353871 2016] [:error] [pid 865] [client 192.168.1.165:59377] PHP Fatal error:  Uncaught SP\\SPException: [0]: Unable to generate the RSA keys ()\n\n  thrown in /var/www/html/ipm/inc/CryptPKI.class.php on line 46
```

I've changed 'https_enabled' => true, in syspass config to false, still not working, after going to http://192.168.1.32/ipm/ it redirects me to http**s**://192.168.1.32:**80**/ipm/

![!](https://cloud.githubusercontent.com/assets/20043789/17926031/a6f8b6ea-69ef-11e6-8902-354d45eecaef.png)

**Comment by nuxsmin** [comment]
Hello, there are 2 issues.

A directory permission error that avoids to save the PKI certificates for input encryption.

And the HTTPS issue, that seems that your webserver isn't responding to HTTPS requests. The config is saved in user's session, so you would need to clear site cookies to reload it.

About documentation, sysPass is quite simple, and most of the help topics are on the app itself. There are some howtos and a FAQ at the wiki site. I know that some points could be improved, but I haven't so much time for it.

**Comment by akurzawa** [comment]
hello nuxsmin

are you aware that these issues that You mentioned above "happened" after I've just clicked/enabled force https and saved settings? is that ok for You that someone will lost access to own passwords and data ? not mention that while activating this option there was not a single line of warning that everything will stop working

**Comment by nuxsmin** [comment]
Hello @akurzawa,

Sorry but if in doubt, you can request some support about it. Risky actions are warned (ie change master password), but this one only does force the HTTPS protocol for every request, that should be enabled and tested in the webserver config.

Like in development, you would need to have a testing environment, that is another sysPass instance at the same server, so you can make changes without any risk.

There is no issue about that behaviour, because the config (saved in user's session for performance) is refreshed every time you save it though the application, but if you make manual changes it needs to be refreshed manually (ie deleting session cookie).

Kind regards

**Comment by nuxsmin** [comment]
Done
