### ISSUE TITLE
Is there a way prompt for 2FA authentication every 30 days instead of every login?

### ISSUE THREAD

**Issue by jasondark93** [nuxsmin/sysPass#308]
I have recently deployed Syspass which has been great for our organisation. I have had feedback from users that they get tired of having to provide two factor authentication every time they want to log in. Is there a config I can change somewhere so that users only need to provide their 2FA code once every 30 days? Great app and thanks very much!

**Comment by nuxsmin** [comment]
Hi,

I'm very glad that you found sysPass useful.

Actually there isn't any option either to set a trusted seat for 2fa nor request the code every n days.

It would be an useful feature for the next release.

**Comment by akurzawa** [comment]
maybe something different - auto locking account once for 30 days - and admin can unlock it

**Comment by nuxsmin** [comment]
Currently, you can configure the 2FA expiration date, so the user will be warned when the expiration date is coming on (5 days).
I think this is the best approach, because an account lock down can be dangerous (the user won't be able to log in until an admin unlocks it) and even without the 2FA code the account is secured by its password.

**Comment by nuxsmin** [comment]
Added to roadmap #422
