### ISSUE TITLE
New Translation Service

### ISSUE THREAD

**Issue by nuxsmin** [nuxsmin/sysPass#309]
Recently, sysPass translation service has been moved to POEditor, a professional service which would help us to get it easily translated to many languages.

Many thanks to POEditor for offering this great service to the Open Source Community.

Translations are welcome!!...https://poeditor.com/join/project/fmlsBuugyv

**Comment by jnid** [comment]
thx. completed the dutch version. but how can i import it into  syspass? and does it matter which version of syspass i should run (i want to setup a test syspass environment so i can check if i have a correct translation)

**Comment by nuxsmin** [comment]
Thanks for the translation!!

Here you have the file:

[messages.mo.tar.gz](https://github.com/nuxsmin/sysPass/files/542894/messages.mo.tar.gz)

You need to unpack it at "inc/locales/nl_NL/LC_MESSAGES" directory. A webserver restart could be required.

**Comment by nuxsmin** [comment]
Here you have the source file:

[messages.po.tar.gz](https://github.com/nuxsmin/sysPass/files/542900/messages.po.tar.gz)

**Comment by nlmaca** [comment]
that didnt work. i did as you said, and could select the dutch language. after that i get a warning.  i cant use syspass anymore. how do i fix this (im in a testenvironment, so no hurry). but i think i have to reinstall syspass (had quite some issues on the installation on ubuntu 14.04, will address that later).
![syspass-change-language-error](https://cloud.githubusercontent.com/assets/4451455/19610854/f7c1306c-97de-11e6-9c5d-44a197e9cedc.png)

**Comment by nlmaca** [comment]
ok. i kinda fixed it. for the languages. there were closed tickets before on the locales. that was the problem again. i have build a complete installer script(s) that will work on a clean ubuntu 14.04 installation. This include (spread out over 3 files)
- update ubuntu
- install php, mysql, phpmyadmin
- install necessary libraries
- create database and user for syspass
- fix locales problem (install all locales supported by syspass)
- restart apache and mysql several times
- all you have to do than is open the browser and start the installation with the database credentials you have entered in the install scripts.

. (your installation on the wiki isn;t up to date). I will put them on my github page. will let you know about it.

The problem is that the locales are not installed in this case. in my scripts i install the locales first. after that even the installer is in dutch. :)

might be useful to create a warning that when changing the language you have to re login to activate the language you have selected.

i have no clue though what Magyar for language is. and you also need the ISO locale, although you have made it on UTF8.
in my script i have fixed it by running this first 

echo "Install locales supported by syspass"
locale-gen "en_US.UTF-8"
locale-gen "nl_NL.UTF-8"
locale-gen "ru_RU.UTF-8"
locale-gen "ca_ES.UTF-8"
locale-gen "es_ES.UTF-8"
locale-gen "de_DE.UTF-8"
locale-gen "fr_FR.UTF-8"

locale-gen en_US
locale-gen nl_NL
locale-gen ru_RU
locale-gen ca_ES
locale-gen es_ES
locale-gen de_DE
locale-gen fr_FR

update-locale
dpkg-reconfigure locales

i will check if i can update dutch language from this point on.

**Comment by nuxsmin** [comment]
Great! I'm doing some modifications to the sysPass wiki to tell some indications about how to setup the locales correctly.

Thanks for the feedback!

**Comment by Kovah** [comment]
I don't have the same problem like nlmaca but locales do not work for me either. I verified that the locales are present in the `inc/locales/en_US/LC_MESSAGES`, then set the language to 'English' in the Syspass settings and my user settings. However, the language of the interface does not change. It stays at Spanish (or whatever language the default is).

I already tried without any success:
* logging out from the app and login again
* restarting the web server
* verifying the ownership of the directory and the files
* changing the permissions on the directory and the files

**Comment by nuxsmin** [comment]
Hi did you set the locales for the utf8 variant?

It should be en_US-UTF8

**Comment by nuxsmin** [comment]
And you need to install the gettext package.

**Comment by Kovah** [comment]
I solved the problem, it was a permissions problem. The language file themselves need to be set to `755`.
For some reason my first `chmod` didn't set the permissions correctly.

**Comment by nuxsmin** [comment]
Good news!!

Thanks for the feedback!
