### ISSUE TITLE
Remote DB during installation does not work.

### ISSUE THREAD

**Issue by DirtyCajunRice** [nuxsmin/sysPass#329]
Trying to connect to a remote database does not work. 500 server error with correct credentials. 
Bandaid:
1. created the database on localhost.
2. Exported the database
3. Created user/database on remote host
4. imported database
5. edited config file and changed localhost to remote database

this made it work. but not how it should work given that there is an option to state where your db is on install.

**Comment by nuxsmin** [comment]
Did you get any error at the webserver log?

**Comment by DirtyCajunRice** [comment]
No /var/log/apache2/error.log shows nothing relative.

**Comment by piknik** [comment]
My installation uses a remote DB and setup worked for me. I think I ran into the same problem, what fixed it for me was to create a user and database for syspass and enable the "Host Mode" setting on the setup page.

**Comment by nuxsmin** [comment]
Right, the 500 error message is because the app tries to log the error into the db, that is no yet configured.

The db configuration error is because the admin user password which is not strong enough (actually a md5 hashed string) for the auth plugin.

Those issues have been solved in the next release.

**Comment by DirtyCajunRice** [comment]
Just tested, this has not been fixed.

**Comment by nuxsmin** [comment]
Can you give a try to the latest 2.0-beta release?

**Comment by macwinnie** [comment]
Just ran into the same error – with the devel-branch.

– on my database-setum, 127.0.0.1 may not be replaced by localhost as DB-Host
– if "Hosting Mode" is active, the database should not be droped on rollback
– the function `checkConnection` of Installer.class checks `if (!DBUtil::checkDatabaseExist())` – as I read the code, the negotiation shouldn't be there ...
– when fixing the above things with the Installer.class, the function `createAdminAccount` calls the static function `getItem` on the `Group` class ... that method isn't implemented, is it? (I could not find the implementation code)

As I did not understand the logic behind the `getItem`-Method, I could not realize it myself ... probably you could have a look at the installer again =)

This tool does look really nice in the demo and I'm looking forward to test it myself! =)
Thank you!
Cheers.

**Comment by nuxsmin** [comment]
Hi Martin, nice to hear from you

It's really weird, because I've tested it on many environments and get also some feedback from many people. Could you connect through an UNIX socket? If so, you could put "unix:/path/to/socket' in the db host field.

About the "getItem"  method that is so because every item class extends an ItemBase class that is called from the DiFactory class. By this way every time you need to instantiate an Item, you get it from the factory, that ensures you get the same item always and not creating a new one instead.

Hope it works ;)

**Comment by macwinnie** [comment]
HI @nuxsmin,

thanks for your reply – I've tried to set the system up tonight with language "English" selected ... that worked 😁 
So my problem was selecting German as the install language – jet another bug 🙈

Cheers =)

**Comment by nuxsmin** [comment]
Hi @macwinnie , what error did you receive?.
