### ISSUE TITLE
Is it save to save master password as account

### ISSUE THREAD

**Issue by derStephan** [nuxsmin/sysPass#407]
What do you think? I am very interested in your opinions.

**Comment by nuxsmin** [comment]
I think it would be a bit insecure because it will need to be set as private account to avoid other application admins to see it, and in that case an application admin would be able to export the whole database, restore it and then modify the account visibility.

Be aware that the debug mode does reveal the current master key to the application admins. That is so because many people asked for a forgotten master key, so the only way to get it is by log into sysPass as an app admin and enable this mode.

**Comment by derStephan** [comment]
Thanks for your reply. 

>I think it would be a bit insecure because it will need to be set as private account to avoid other application admins to see it

I don't see how this might be a problem, if this is true:

>Be aware that the debug mode does reveal the current master key to the application admins. 

Are there any other objections?

**Comment by nuxsmin** [comment]
No more.

Actually, that debug mode behavior has been disabled, so no one could get the master key without hacking the code to get it from the user's session.

**Comment by derStephan** [comment]
I see. Thank you very much for your great work.
