### ISSUE TITLE
bug: saving settings kicks you back to search. 

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#408]
# Bug report

Hi There, 
Currently we are testing syspass RC4 and Would like to move it into production as soon as it is ready. 

I would like to personally thank the developer for building a solid password manager and commend you on the design.  

I may open another issue in regards to some of the terminology used in syspass. for example. 

Accounts
Groups 
Profiles

as some of my team members would like some further clarification on their usage.  

This is a small bug report on the behaviour of syspass. Currently we are getting redirected to passwords/accounts page when saving settings, more information below.

## System info:

syspass RC4  
Ubuntu 16.04
Apache2
Php7.0
mysql 5.7

## Steps to reproduce:

1. Go to > settings/configuration icon. 
2. Change required field e.g. timeout seconds from 3600 > 900
3. select save button. 
4. syspass redirects to main page.

## Expected behavior:

save settings and redirect to current settings page.

## Actual behavior:

Redirects to Accounts/Search page.

##

Kind Regards 

k.s-dean

**Comment by nuxsmin** [comment]
Hello,
thanks so much for your commends and I'm very glad that you found it useful.

About that behavior, that is so because after saving the config, the application need to be reloaded to make the changes active. Those changes involves, in some cases, to set a new language or add some additional styles to the theme, so the only way to get it is reloading the page.

When the reload is performed, any Javascript object is destroyed so the app doesn't know what the user was doing before. There are some workarounds to get it, but it involves using some techniques that are not fully supported on all the browsers (web storage or indexed DB).

I thought that a reload when config is updated wouldn't hassle too much :)

Kind regards

**Comment by nuxsmin** [comment]
Added to roadmap #422
