### ISSUE TITLE
"Error while updating accounts' passwords"

### ISSUE THREAD

**Issue by macwinnie** [nuxsmin/sysPass#415]
Changing the masterpassword and reencrypting all passwords results in the `Error while updating accounts' passwords`. Maybe something with empty AccountHistory for only blank created accounts without any actions?

`inc/SP/Controller/ConfigActionController.class.php` => row `530`

Cheers!

**Comment by nuxsmin** [comment]
Hi, is there any error in sysPass event log?

**Comment by macwinnie** [comment]
Hi, the event log simply tells me, that the maintenance mode was activated – I think `Parameter: lock, Value: 1` does mean that? ^^
Even the error log of the server doesn't hold more information and the debug mode gives me no valid information, too ...

**Comment by nuxsmin** [comment]
Where did you see the error message pointing to that class/line?. Which version/build are you running?.

The `lock` parameter holds the user id that locked the application, so that user could have an active session. The `maintenance` parameter (in the config file) is used to switch on that mode. The debug mode display some "useful" information and sets the PHP error logging more verbose.

**Comment by macwinnie** [comment]
I'm running the devel-branch of the project. The Error-Message appeared as a red popup at the top of the site and then I just checked the translation file, where this special error is thrown :D

Thanks for explaining ;) ... the Debug-Mode did not help – the error log did not hold any more information after enabling it :(

**Comment by nuxsmin** [comment]
Okay!, that was a good find out ;)

In that point (class/line) the app was decrypting/encrypting the "normal" accounts, so the history had not been processed yet. I've performed several master key changes without any issue, so it would be a bit hard to find out the cause.

**Comment by nuxsmin** [comment]
Hi, did you try it out again?
