### ISSUE TITLE
Active Directory Integration 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass#416]
I'm having a hard time getting sysPass to work with Active Directory. Is it not possible to connect directly to the AD server? I keep getting the following in the event log 
Connection error (BIND)
LDAP ERROR : Can't contact LDAP server (-1)

Any Advice how how to configure it to work with the AD server.

**Comment by nuxsmin** [comment]
Hello,

Did you set a hostname or an IP? If you set a hostname, sysPass will pick an LDAP server from the DNS records that point to your DC servers in a random way.

Which sysPass version are you running?

**Comment by jr-RXcode** [comment]
I tried doing it by hostname and also with a IP. I'm trying out syspass 2.0 RC4. 
I'm also just trying to contact the active directory server directly, I don't have an LDAP server. Is there a wiki doc that explain how to configure it with Active directory?

**Comment by nuxsmin** [comment]
Active directory is an LDAP server. There isn't any documentation about the LDAP config because it is quite simple and there isn't any special needs.

You only need the server either the server IP or hostname and the auth user. The server should be accessible through the 389 port but some servers may require an ldaps connection so you would need the server and CA certificates.
