### ISSUE TITLE
sysPass seems to depend on PHP's mcrypt

### ISSUE THREAD

**Issue by robert-scheck** [nuxsmin/sysPass#425]
sysPass seems to depend with `inc/SP/Core/Crypt.class.php` on PHP's mcrypt rather using e.g. PHP's openssl. Please either use phpseclib (as abstraction layer/wrapper) for really everything or add support for PHP's openssl rather currently mcrypt only. Aside of that, mcrypt IMHO shouldn't be used at all anymore: https://paragonie.com/blog/2015/05/if-you-re-typing-word-mcrypt-into-your-code-you-re-doing-it-wrong

Note: The documentation also refers to PHP mcrypt:
- https://doc.syspass.org/en/installing/centos7.html
- https://doc.syspass.org/en/installing/debian8.html

**Comment by nuxsmin** [comment]
Absolutely right, and that is a planned feature on the 2.1 roadmap #422 . As of PHP 7.1 this module is removed.

**Comment by derStephan** [comment]
May I suggest to take a look at libsodium rather than openssl? Libsodium will be included into PHP's core as of version 7.2. As far as I understand, openssl is and will remain a module which may or may not be available on different hosts. 

Libsodium seems to be state of the art and if it is included in the PHP core, then you can be sure that your application will work on any machine. 

https://dev.to/paragonie/php-72-the-first-programming-language-to-add-modern-cryptography-to-its-standard-library

**Comment by nuxsmin** [comment]
Hello @derStephan 

you're right, libsodium would be nice but currently you would need to compile it trough PEAR and this could hassle a bit.

In a few days I would announce an upgrade that will use a new encryption schema based on Defuse library, which could relies on libsodium if available. 

I'm finishing the upgrading process and **you can take a look on the crypt branch for details.**

There will be also a CVE (CVE-2017-5999) regarding this issue.

**Comment by nuxsmin** [comment]
Hello everyone,

sysPass 2.1 is out and brings many security improvements like OpenSSL encryption and an smoother upgrade process.

**Comment by nuxsmin** [comment]
Solved in the latest version
