### ISSUE TITLE
sysPass behind reverse proxy

### ISSUE THREAD

**Issue by vilure** [nuxsmin/sysPass#433]
I have sysPass served by Nginx on a VM(lets say 192.168.0.1) in my local network and another Nginx, that proxies requests to 192.168.0.1, on another pc(let it be 192.168.0.2) that have access to internet.
When a access sysPass it tries to load logo_icon.png and logo_full_nobg.png from inaccesible 192.168.0.1 instead of 192.168.0.2.
Also when i try to generate password i get this:

> `js.php?f=bootstrap-material-datetimepicker.min.js%2Cmaterial.min.js%2Cmdl-jquery-modal-dialog.min.j…:414 Uncaught ReferenceError: zxcvbn is not defined
>     at h (js.php?f=bootstrap-material-datetimepicker.min.js%2Cmaterial.min.js%2Cmdl-jquery-modal-dialog.min.j…:414)
>     at HTMLLIElement.<anonymous> (js.php?f=bootstrap-material-datetimepicker.min.js%2Cmaterial.min.js%2Cmdl-jquery-modal-dialog.min.j…:421)
>     at HTMLLIElement.dispatch (js.php?v=007f991…:4)
>     at HTMLLIElement.r.handle (js.php?v=007f991…:4)`

**Comment by nuxsmin** [comment]
Umm, that's weird because those resources are loaded by the browser itself, so it will request for any resource to the reverse proxy. Worth to mention, that I'm running a sysPass instance behind a Varnish reverse proxy through https without any issue. My scenario would be:

Client <-- https --> Varnish <-- http --> sysPass (on Apache server) <-- https --> Client (internal)

**Comment by vilure** [comment]
Problem solved, my front Nginx wasn't passing correct Host header so the inner Nginx picked ip of the local machine

**Comment by nuxsmin** [comment]
Great!

Thanks for the feedback ;)
