### ISSUE TITLE
Enhance (end-)user experience by changing look'n'feel

### ISSUE THREAD

**Issue by robert-scheck** [nuxsmin/sysPass#453]
Please enhance the (end-)user experience by changing the look'n'feel, e.g. have a look to the screenshots of https://www.passbolt.com or https://clipperz.is to get an inspiration of what I mean.

**Comment by nuxsmin** [comment]
Hello @robert-scheck 

It would be nice to get a better user experience, but since I'm the only sysPass developer, it's quite difficult to get a balance between user experience and features.

The current release has been a major upgrade on every app component, because there were a bunch of code improvements and new features, and worth to mention that now the app has a responsive layout, without needing native platform apps.

I hope in the near future to get a proper user experience and some more feedback from sysPass users (sadly there isn't too much ones).

Thanks for the feedback!

**Comment by bitking** [comment]
I like the ui it is simple and effective, just my 2 cents.

**Comment by basil-twisleton** [comment]
I also like the general look and feel of the current version. (however I do like the idea of a preview pane for a selected account, as shown in Passbolt, rather than having to load new pages each time)

There are some minor changes that could make the user experience it a little cleaner, but from a free tool by a single dev we should be very happy with what we have. 
eg
* Moving log out and preferences to the top right corner (makes it consistent with most other websites)
* Move search/new/edit links to be more central rather than top right (makes it closer to the input controls on those pages)

All that being said I would rather enhanced features/security over these UI changes.

Thanks,
Basil

**Comment by nuxsmin** [comment]
Hello, this is an interesting thread and I think that UX a key point on an app success.

@basil-twisleton those points could be accomplished in the next releases. The preview pane is very interesting and I thought about it a time ago, but recently I decided to prioritize the security improvements because this is a security focused tool where confidential/important data would be stored, so I left out those UX changes for a later release.

Thanks for the feedback!

**Comment by basil-twisleton** [comment]
@nuxsmin excellent. I think that a number of these little changes will really help in the UX feeling. I will try to get more feedback as I get familiar with v2.1

@robert-scheck  I would suggest you make a list the things that you would like implemented rather than saying "make it look like these other apps".  From a developers perspective this is not very helpful compared to, I would like to see x, y and z implemented. 
Otherwise how with @nuxsmin  know which bits you would actually like implemented??
Plus it opens up effective dialogue between all the users regarding items that may or may not be useful/needed. 

Thanks,
Basil

**Comment by nuxsmin** [comment]
Sure @basil-twisleton those points could be implemented, and mostly the related one to the log out and preferences buttons. The icons centering, would be a hassle on low resolution displays:

![sp_lowres](https://cloud.githubusercontent.com/assets/1775774/23667229/746c84a6-035d-11e7-9adc-4f01269ef5d0.png)

Because by adding the bottom buttons, wouldn't left enough space to the others, so the would overlap with the logo.

**Comment by basil-twisleton** [comment]
That makes sense but would depend of setup of the system I guess. 

For example, we  use a named admin user for User Access management and then LDAP for normal usage. 

The top bar is a lot less crowded (this is the minimum window size before the menu bar replaces the buttons)
![image](https://cloud.githubusercontent.com/assets/2098465/23743222/1acc6520-04b0-11e7-920e-c176ea134713.png)

I also noticed that there are two buttons (top right & bottom left) to show notifications. 

Would you like me to create new issues with some suggestions/screen mockups? or just in here?

Thanks,
Basil

**Comment by nuxsmin** [comment]
Hope that the latest (minor) UI tweaks would improve the UX ;)
