### ISSUE TITLE
Offline Access

### ISSUE THREAD

**Issue by AshHaque** [nuxsmin/sysPass#475]
Hi,

We are very happy with this free software. It has cool features. Soon we are going to replace our current password manager in our business with this awesome tool.

In our current password manager, we have a feature that allows user to access it offline. User just need to download the encrypted passwords text file and put it in his laptop. Then with a offline access tool that is in his laptop and with the required encryption key users are able to get required passwords. Note that we have multiple encryption key based on the category. One user has only those keys that he is allowed to have.

Is there any way in current syspass to achieve this? I am not sure. Any help will be highly appreciable !

Ash

**Comment by nuxsmin** [comment]
Hi @AshHaque 

I'm very glad about your decision and more about you found it useful :)

The offline feature would be a nice and interesting feature and I think it should be done in next releases. I'll give a think about how to implement it in a secure way, because although you protect a category, you should think that the user will have those accounts forever.

Added in ToDo list ;)

Regards

**Comment by AshHaque** [comment]
Thanks nuxsmin.

Is there any ETA for the next release in your plan ?


Ash

**Comment by szg-mw** [comment]
Perhaps there should be an option, that the passwordfile stored in the Client is automatically destroyed after a a time X if the user does not reconnect to the SysPass Server

**Comment by derStephan** [comment]
@nuxsmin 
>The offline feature would be a nice and interesting feature and I think it should be done in next releases. I'll give a think about how to implement it in a secure way, because although you protect a category, you should think that the user will have those accounts forever.

I think, doing this in PHP is not very useful due to the fact that I need a full Webserver and MySQL-Server environment. Yes, you can get that portable but this is still not really user-friendly. 

For being really portable, you need to write a software in C or anything that runs natively on Windows, Linux and Mac. And then there must be a way to synchronize changes from this client to server - including multi-installation-environments. 

I think, that the efford to do so is at least as big as creating syspass in the first place. Do you really want that? 

@AshHaque: 

What do you need the offline-feature for? How often does that happen? Nowadays, your smartphone is always-on and syspass already has a usable mobile interface. Why not running it on a public server and accessing it from everywhere?

@szg-mw 
>Perhaps there should be an option, that the passwordfile stored in the Client is automatically destroyed after a certain time if the user does not reconnect to the SysPass Server

There is no way, you could have control over anything that is done on a remote computer. If you give encrypted data and password to decrypt it out of your hands, your data is decryptable, regardless of any countermeasures done in the original software. 

If I want to decrypt the data and the original software won't allow it, then I will use openSSL directly.

**Comment by nuxsmin** [comment]
@derStephan I'm absolutely agree. I was thinking on a mobile solution based on the Android platform and it could be used also as a Java application, but the fact of having the data on the client side is a big security risk. I'd implement a solution that would get a partial set of data in XML format, so the user would only get the accounts in which he is granted, so the risk of a data leak is related to which permissions have been given to the user on the sysPass server, so it's up to the admin who decides what the user can do/see.

Said that, I'm still thinking on it but any suggestions are welcome.

Thanks for your feedback!

**Comment by nuxsmin** [comment]
Added to roadmap #422
