### ISSUE TITLE
Bug: Logout notification auto-disppear

### ISSUE THREAD

**Issue by basil-twisleton** [nuxsmin/sysPass#485]
Hey,

In version 2.1 when I logout (or session times out) it shows a yellow banner at the top of the page. 
"Warning: Session finished" 

The login fields are not visible until the message disappears. 

The issue is that the box only disappears by clicking the x or by mouse-overing the box and then waiting for the timeout to finish. 

It looks a lot like #423 

Thanks,
Basil

**Comment by nuxsmin** [comment]
Hey,

that is so by design also. Because in that way the user could see that indeed he logged out. In a future the app would log out automatically, so the user could guess what happened to the session...

**Comment by basil-twisleton** [comment]
Could this be added as a label above/below the login fields. That way it is always visible following an auto-logout, but makes it flow better to login again?

**Comment by nuxsmin** [comment]
You're right, but since the log out implies a page reload to clear the session data, the app need to know if the last event was an end of session, so the URL is rewritten to tell that a log out took place. Then a new reload is needed to remove that "ugly" URL and don't let the user to reuse that page, because it will make the app to clear the session data again.

You may think that some stuff could be avoided, but some popular apps (ie Gmail), implements a similar behavior but without the warning message. I just added it to remind the user that he logged out.

**Comment by basil-twisleton** [comment]
Makes sense. 
I guess in this instance it makes more sense to ensure all data is cleared from the session at logout. 

Thanks for the info.
