### ISSUE TITLE
sysPass 2.1.2 - copy to clipboard error

### ISSUE THREAD

**Issue by lukasp2** [nuxsmin/sysPass#500]
Hi,

I can't copy any password to clipboard. I'm getting a error:
> Error copying to clipboard

No entries regarding this in syspass.log available.

**Comment by nuxsmin** [comment]
Hi Lukas,

which browser are you using? (sorry I missed your previous post)

**Comment by lukasp2** [comment]
FireFox latest ESR release

**Comment by nuxsmin** [comment]
Ok, so you told that this issue is related when clicking on the "Copy to Clpboard" icon that is outside the password box. Does the password contain any special char?, Does it work on the demo site?

**Comment by lukasp2** [comment]
On demo site it is working.

One password is -> MaxNCBGLpS

**Comment by lukasp2** [comment]
with Version 2.0 it was working fine...

**Comment by lukasp2** [comment]
Hey Rubén,

I found something out. When I use the "copy to clipboard" button direct on page which shows me my entries, it doesn't work. When I click 1st on "show password" button and press then "copy to clipboard" button, this is working fine.

I hopy you can understand my bad english :)

Br,
Lukas

**Comment by nuxsmin** [comment]
Hey Lukas!

I'm doing some tests. I'll be back shortly.

Your English is quite good...Mine isn't perfect too :)

**Comment by lukasp2** [comment]
Hi Rubén,

i updated to current sysPass version, but the copy to clipboard issue is still present :-(

Br,
Lukas

**Comment by maxdie** [comment]
I have some problem too ! All logs is clean. Debug not show trouble.

**Comment by nuxsmin** [comment]
@maxdie sorry I don't know what you mean :(

**Comment by maxdie** [comment]
Hello. sorry for my English.

I have issue how and lukasp2. CopyPast not work. When I push icon get a message 

![image](https://cloud.githubusercontent.com/assets/26085639/24002319/7c235d80-0a71-11e7-8c43-7ae00262b305.png)

Appache log and sysPass log is empty.

**Comment by nuxsmin** [comment]
Ok @maxdie ...Now I see it's the same issue, the weird thing is that this works on the demo site, does it work for you?

**Comment by maxdie** [comment]
Hello.
I added on demo site in webform customer and category. 
First password is simply and add to clipboard, but one time. 
Second password more strongly but not copy to clipboard and now simply password do not copy too.

**Comment by lukasp2** [comment]
How we can help you Rubén to do some troubleshooting?

**Comment by nuxsmin** [comment]
Now I see the error on the demo site, it's weird because it didn't happen before.

I'll take a deeper look.

**Comment by lukasp2** [comment]
I love your work and your progress ! ;-)

**Comment by nuxsmin** [comment]
Thanks, I've been testing on Firefox and chrome on Windows and Linux and it didn't fail. I could reproduce the issue on Firefox on android.

**Comment by maxdie** [comment]
I try copy paste password from demo syspass site on my android device. Use google chrome. Trouble like in windows os.
![xpsscreenshot_2017-03-19-08-33-22](https://cloud.githubusercontent.com/assets/26085639/24078458/44a1e0ba-0c7f-11e7-8b64-bab078eff421.png)
![screenshot_2017-03-19-08-33-14](https://cloud.githubusercontent.com/assets/26085639/24078467/5c4d9196-0c7f-11e7-9fae-01537b4343a9.png)

**Comment by lukasp2** [comment]
@nuxsmin do you have any idea how to fix this problem?

**Comment by nuxsmin** [comment]
@lukasp2 I've been doing some tests and finally I guessed that some mobile browsers don't implement a feature that is required to run a "text copy" action: https://developer.mozilla.org/en-US/docs/Web/API/document/execCommand

The doc tells that  Safari and Firefox for iOS don't implement the "execCommand" feature, so the "copy-to-clipboard" feature won't work until it will be implemented.

I don't know if you are testing on a mobile device, but if it were the case, now you have the answer. Is it?

BTW, I'm trying to find out why it doesn't work on Android mobile devices using Firefox/Chrome. @maxdie

**Comment by lukasp2** [comment]
@nuxsmin I'm trying it with FireFox ESR 45.6.0, IE 11.0.9600.18537 and Vivaldi 1.6.689.40 running on Windows 7 Enterprise SP1 64bit

**Comment by nuxsmin** [comment]
@lukasp2 the main difference is that the first one (using the direct button) gets the password from an AJAX request, passes it to the Javascript plugin to copy it to the clipboard. The second one, performs an Ajax request, BUT it sets the password in a field that is shown (password box) and then, when you press the "copy" button, it catches the password from the field and copies it to the clipboard.

To get the clipboard working, the action for copying the text (in this case the password), need to be executed in the user space, because there are some security restrictions that avoid to copy any text in a background process. It's a bit complicated :)

From: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard

> You can use the "cut" and "copy" commands without any special permission if you are using them in a short-lived event handler for a user action (for example, a click handler).

**Comment by lukasp2** [comment]
Okay, also my FireFox ESR Release it not up to date. I will try that @Home with current FireFox / Google Chrome releases.

**Comment by lukasp2** [comment]
Update: I tested it on my MacBook (macOS Sierria 10.12.3) with Chrome 57 and FireFox 52....same issue

**Comment by nuxsmin** [comment]
I'm still working on a solution. This is a browser security behavior that is planned to be redesigned to allow asynchronous requests to perform clipboard actions if the user grants permission before using it.

**Comment by ejouvin** [comment]
For me, still have error on my install version 2.1.4
But on demo site, it works fine.

How can we help to debug ?

**Comment by nuxsmin** [comment]
Hello, since this issue occurs in a random way and the current clipboard behavior is a bit restrictive (see a comment above), I could figure out that it happens when the response from the server is delayed, so the password from the Ajax request is not set.

The current behavior is as follows:

1. User clicks the password button
2. A click event is triggered
3. An Ajax request is performed while the click event is waiting
4. The Ajax request finishes and the password is send in the response
5. The password is sent to the clipboard function
6. The clipboard function creates a pseudo-element to copy the password in it
7. The password text is selected and copied
8. A message is displayed

Currently a new clipboard API is being developed (working draft), so Ajax actions will be allowed to send text to the clipboard (https://www.w3.org/TR/clipboard-apis/#integration-with-other-scripts-and-events)

In the meantime, I think that the current session encryption could be the cause of the issue, because it reduces the general performance in terms of speed when performing requests.

**Comment by nuxsmin** [comment]
Could you try out the latest commit in the master branch?

**Comment by lukasp2** [comment]
I'm getting just the error

**Comment by lukasp2** [comment]
When I activate session encryption, then is copy to clipboard working for me with newest Vivaldi Browser.

**Comment by ejouvin** [comment]
Works for me, encryption enabled or not.

So now, I am waiting the new official release.

**Comment by nuxsmin** [comment]
That sounds nice

**Comment by neolinux** [comment]
It's working by me too. 👍

**Comment by nuxsmin** [comment]
Ummm...that sounds to be more likely to a browser update, because there weren't any changes to the clipboard functions code since a few commits ago. The latest commit only implements some new features like enable/disable PHP session encryption and secondary groups accesses.

Thanks for the feedback! 👍

**Comment by neolinux** [comment]
Ok, but i have tested it before and after upgrading from 2.1.1 to 2.1.4 and then to the latest master branch.

I haven't closed my browser or updated it...

**Comment by nuxsmin** [comment]
Ok, in your case, there were some intermediate releases that implemented some fixes to that behavior.

**Comment by nuxsmin** [comment]
Solved.

Thanks to everyone for the feedback!

**Comment by deajan** [comment]
Doesn't work for me, with Opera 47 (lastest) Win x86.
When using the debug console, here's what I get
```
js.php:162 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
```
