### ISSUE TITLE
Bug Report/ and suggested Imporvemnets from my user base

### ISSUE THREAD

**Issue by k-s-dean** [nuxsmin/sysPass#503]
some of the users at my organisation have found the following issues. 

Can't hit copy to clipboard button on Firefox
 - document.execCommand(‘cut’/‘copy’) was denied because it was not called from inside a short running user-generated event handler.

User's group has view permissions on all passwords created by that user, even if permissions are not explicitly given

When edit permission is denied, go to permission denied page after hit save

Users should always be able to edit/delete their own passwords

On main page if you double click star/clear then all cards disappear

Should have list view instead of card view to increase density

Cookies are not marked as Secure. SYSPASS_SK cookie is not marked as HttpOnly

Users should be able to assign an account to a different group to their own which is not seen by their group

Kind Regards

**Comment by k-s-dean** [comment]
version: 2.1.1.17030601

**Comment by nuxsmin** [comment]
Hello,

I think that the clipboard issue is related to a Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1197451

Regarding your points:

> User's group has view permissions on all passwords created by that user, even if permissions are not explicitly given

Right, the main user's group will be able to access to the account. Here is a description about how ACL works: https://doc.syspass.org/en/application/permissions.html

> When edit permission is denied, go to permission denied page after hit save

I'll take a look to this

> Users should always be able to edit/delete their own passwords

It should be granted indeed, but they have to be enabled those permissions in the profile.

> On main page if you double click star/clear then all cards disappear

I'll take a look to this

> Should have list view instead of card view to increase density

You can switch to list view either on user's preferences or global configuration.

> Cookies are not marked as Secure. SYSPASS_SK cookie is not marked as HttpOnly

That is so because some installations are behind a reverse proxy which talks to the sysPass instance in http and https for the client side. BTW, this cookie is encrypted and does not involve any risk to the application if it were leaked, because it only stores a key for the server session encryption (on server side) and not the session itself.

> Users should be able to assign an account to a different group to their own which is not seen by their group

This can be done by setting the "Accesses" option on the user's profile.

I hope this would clarify your questions.

Kind regards

**Comment by nuxsmin** [comment]
Hello, that issues should be fixed in the latest code in the master branch
