### ISSUE TITLE
Secondary Group (getIsUserInGroups) ACL logic

### ISSUE THREAD

**Issue by alexanderbuhler** [nuxsmin/sysPass#514]
Hey there,

finally updated to the 2.1 without any issues during upgrade process. It seems that you missed a fragment of logic which is checking whether the user is in any of the groups which are added to [group permissions] of an account.

In the old version, this code checked for it in Acl.class.php at line 185:

```
        if ($userToGroups === false) {
            foreach ($accountData['groups_id'] as $groupId) {
                $users = Groups::getUsersForGroup($groupId);

                if ($userGroupId === $groupId || in_array($userId, $users)) {
                    $userToGroups = true;
                }
            }
        }

```

Currently I fixed it just by nesting the primary check routine into the secondary check and then using $groupId as the getById parameter, since we don't care at all for the primary group of the account and associated permissions.

```
        // Comprobar si el grupo del usuario está vinculado como grupo secundario de la cuenta
        foreach ($AccountData->getUserGroupsId() as $groupId) {

            if ($groupId === $this->UserData->getUserGroupId()) {
                return true;
            }

        
            // Comprobar si el usuario está vinculado desde un grupo

            foreach (GroupUsers::getItem()->getById($groupId) as $GroupUsersData) {
                if ($GroupUsersData->getUsertogroupUserId() === $this->UserData->getUserId()) {
                    return true;
                }
            }

        }
```

You should have a look at it :-)

Best
Alex

**Comment by nuxsmin** [comment]
Hi @alexanderbuhler 

you're right the old behavior has been changed in the current release so only the users that are listed in the account's main group will be granted to access to the account, so in that way the users that are member of the account secondary groups will be granted if the user's main group matches with the secondary group.

In that way the security access to the account is enforced to only the accounts main group or users main group and the secondary users.

BTW, I'm thinking to implement a switch to enable or disable the users in secondary groups.

Thanks for the feedback!

Kind regards

**Comment by alexanderbuhler** [comment]
Eh, first of all thanks for coming back this quick. Read your answer three times to get even more confused 😃 

So it's a feature and not a bug. What are the secondary groups for at all then? How are you using them?

To get you a better picture here is our use case of syspass, by which I have to still modify some parts of the code after every update:

1. Global search always on, so every user can see the existence of every account (I still have to find out the exact impact of enabling it in the main settings vs enabling in profile permissions, overall this function seems needless)
2. Every user is in the main group "staff" by default [LDAP] (that's why the primary group doesn't matter in terms of access control)
3. We have a bunch of "secondary" groups which hold some selected users (e.g. project or client specific) 
4. Accounts are created by admins or staff, so the primary account group may differ (again, the reason is same as in 2.)
5. Since every user is in the same main/primary group "staff", I alter the code so that a user doesn't automatically get view/edit access just because you share the same main group of the account - everyone without explicit permission just gets to know the existence (see 1.)
6. To provide access for an account we do it almost exclusively with those secondary project or client specific groups (point 3.)

TBH: The single main group defined in the user + secondary groups which hold users are defined logic is really messed up from my point of view. There are ambiguous concepts involved which are hard to understand and also make the acl code really complicated.

It would be a more straightforward practice to allow users to be in multiple groups so you only assign groups to users and not the other way around. That's for the access control of accounts - the permissions themselves are sorted by profiles already.

But still curious about your reasoning behind the currently used approach.

Best
Alex

**Comment by nuxsmin** [comment]
Hey!, Now I can understand your point of view and how you use the groups functionality.

When I started to develop sysPass the groups were the key point in the ACL because there weren't either secondary groups nor users, so you needed to deal with group membership. Some time later, as the features were added and the increasing use of the app, made me think about how to maintain the same functionality and make it powerful by adding more items to the ACL, that is when I decided to implement the secondary groups, BUT they couldn't have the same privileges as the main group, because they would be treated as a "guest", so I thought on the groups behavior, that is the groups will hold users but they will be the accounts' "guest".

Currently the users in secondary groups behavior is like the following example:

- "Account A" has set its **main group** to "Group A"
- You edit the "Group A" and set some users for this group.
- Those users will be granted to access to the "Account A" because the "Group A" is the account main group.

Regarding your last point..

> It would be a more straightforward practice to allow users to be in multiple groups so you only assign groups to users and not the other way around. That's for the access control of accounts - the permissions themselves are sorted by profiles already.

Actually, it would be a more easy way, but all the groups would be treated in the same way, that is you couldn't give more privileges to some users that belong to a group. i.e: the users that have set their main group to the account main group have all privileges like the account's owner.

BTW, I'm thinking on adding a switch that would grant access to the users that are listed in a group which is an account secondary group.

Kind regards

**Comment by alexanderbuhler** [comment]
Got you. Yeah a switch would at least sort that out for me. I'd also be grateful for an option which disables any view or edit rights if account main group and user main group match (see point 5. of my last message).

It's getting late - I'll think over this once again as soon as my thoughts clear up a bit 😄 

Best
Alex

**Comment by nuxsmin** [comment]
Fine, our thoughts will be cleared up after sleeping a few hours :)

**Comment by nuxsmin** [comment]
Hello @alexanderbuhler I've added this feature in the latest commit to the master branch (0e91d4f7cfa052871977431e5e912d76714ca361). Please take a look and let me know if it works as expected.

I missed to mention this issue in the commit and your comments :(

Thanks for the feedback!
