### ISSUE TITLE
Steps to improve performance of syspass 2.1

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#523]
I have noticed after upgrading to 2.1, syspass tool performance has impacted and it takes sometime to get to the first page after providing username,password.(it works fine, but relatively slow)

And the same applicable for navigating through various pages, any help on improving performance would be much appreciated.

Thanks,
Ani K.

**Comment by nuxsmin** [comment]
Unfortunately the performance issue is related to the session encryption, because the session data that is stored in the webserver while the user is logged in, is encrypted to avoid any leak on the webserver side.

The session data is used to store some info like configuration, user preferences, search filters and other data that is used very often and retrieving it every time would be costly.

Regards

**Comment by nuxsmin** [comment]
I'll add an option to disable session encryption, but you need to be aware that security is not related to performance, because every security mechanism adds a new layer that reduces the overall performance.

Regards.

**Comment by nuxsmin** [comment]
Could you try out the latest commit in the master branch?

**Comment by anikarunakaran** [comment]
it works, thanks..

**Comment by nuxsmin** [comment]
Great!, thanks for the feedback!
