### ISSUE TITLE
How to disable http link for syspass

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#526]
Currently,syspass login URL works for http & https, i would like to disable http URL for syspass.
Please let me know how to disable the same..
Also noticed that, if i force enable https from configuration, syspass seems to be not working..
appreciate if you could throw some lights on this.

Thanks,
Anil.

**Comment by nuxsmin** [comment]
Hi,
I'll take a look to the https switch behavior, but it only forces all the http requests to switch over https, BUT be aware that if sysPass is behind an http proxy that "talks" to sysPass in http, it will break the connection, because it will force to the proxy to talk in https.

Anyway, you can force an https connection by configuring some apache options either a virtualhost or ".htaccess" file.

Regards

**Comment by Edtigoza** [comment]
**if apache**
<VirtualHost *:80>
ServerName www.example.com
ServerAdmin info@example.com
Redirect permanent / https://www.example.com/
    TransferLog /var/log/apache2/transfer.example.com.log
</VirtualHost>

**if nginx** 

server {
  listen 80;
  server_name example.com;
  # enforce https
  return 301 https://$server_name$request_uri;
}
