### ISSUE TITLE
Result as cards

### ISSUE THREAD

**Issue by Rikkirt** [nuxsmin/sysPass#528]
Hello Rubén,

Great application, testing it for personal use right now.

When application admin sets the config parameter: Accounts -> results as cards -> true, a user still has the preference setting to view the account results as cards. In the code I saw that the config overrules the user-preference. If the user-preference has no effect, maybe it could be deactived, or perhaps not shown at all in the user preference?

Bug: version 2.1 (2.1.5.17040401)
Accountsearch.class.php line 652 Array is String
I get a Server error because in pickAccountColor(), accountColor  is set as String, but the return value should be an array. I changed it in my local source to make it work.

Rikkirt

**Comment by nuxsmin** [comment]
Hello @Rikkirt 

I'm glad that you liked it :)

You're right, some user prefs could be overridden by the global ones, so it would be fine to disable those set in the global config.

Regarding the color issue, I don't figure out what could be happening, because it doesn't occur on my testing environment, and analyzing the code it should never treat as string because there are some checks before:

```
        $accountColor = Session::getAccountColor();

        if (!is_array($accountColor)
            || !isset($accountColor, $accountColor[$id])
        ) {
            // Se asigna el color de forma aleatoria a cada id
            $color = array_rand(self::$colors);

            $accountColor[$id] = '#' . self::$colors[$color];
            Session::setAccountColor($accountColor);
        }

        return $accountColor[$id];
```
Are you running it on PHP 7.1?

Thanks for the feedback!

**Comment by Rikkirt** [comment]
Hi Ruben,

Correct, for this test I'm running the latest PHP 7.1.3 with Apache2.4 
(I have disabeld/hacked your version check 5.6> & <7.0.... to make it run on 7.1.3)

I've tested it today also with nginx/PHP 5.6. This gives no error.

Hope it helps
