### ISSUE TITLE
Columns width and alignment

### ISSUE THREAD

**Issue by dmaniad** [nuxsmin/sysPass#531]
Regarding columns in the starting page (index.php) I think there is a problem in the alignment. The position of the column headers is not correct: 
Customer    Name    Category    User    URL / IP

Please check:
#
![sys](https://cloud.githubusercontent.com/assets/27197402/24858944/1630d3b0-1df7-11e7-9064-cb92df1d3f56.png)

**Comment by nuxsmin** [comment]
Hello, 

that is so because the filtering headers don't have to match with the columns width, because those headers could have a behavior than the column data holds, e.g. sorting by number of views or other kind of sorting that could be implemented in the future. In addition, in mobile view, those headers won't match either.

Briefly, the filtering couldn't match with the columns in next releases because the data being filtered.

Regards
