### ISSUE TITLE
ERROR Updating From  1.2.0.17 To  2.1.5.17041001

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysPass#532]
I'm tryng to Update from 1.2.0.17 to 2.1.5.17041001 and i see the error attached. 
![error](https://cloud.githubusercontent.com/assets/8935378/24881323/d235cf86-1e13-11e7-8529-ca4799363b43.PNG)

I also tryed to go on and continue the update, and when it finished i cant log in anymore and i get the same error. 

The only error i found at logs is:

2017-04-10 20:28:22 - initError

**Comment by nuxsmin** [comment]
Hello, that issue could because the new Javascript code hasn't been loaded, so you could reload (F5) the browser page to get it.

The initError is not necessarily an error, it's a method that is called when the app initialization is stopped by either an error or a maintenance message or the upgrade process.

**Comment by gabrielsoltz** [comment]
I did F5 and CTRL+F5, and the error continue showing. 
I also tryed with incognito mode to be sure is not a cache issue, and i get the same error.

**Comment by nuxsmin** [comment]
Could you open the JS browser console (F12) and tell me what is displayed in the "console" tab?

**Comment by VexedSyd** [comment]
I have the same issue after upgrading from 2.1.4.
It is complaining about /ajax/ajax_getEnvironment.php, I'm getting a 404 error for this file.
It looks like a permissions issue...

**Comment by Edtigoza** [comment]
I had another type of error not remember but some like this (**Unknown error, the page will be available in a few moments**, but it take more than two hours), in my case restart php service  solve the trouble, 
do you already tried it?

**Comment by VexedSyd** [comment]
I have restarted Apache2 multiple times with no luck.

**Comment by Edtigoza** [comment]
what your version of php and distribution, Apache2 is not the PHP service,
I have Debian 8 jessie, in my case
sudo service php5-fmp restart,

**Comment by VexedSyd** [comment]
I'm running it on Debian 8 Jessie as well, Apache 2.4.10 and PHP 5.6.30.
I haven't tried service php5-fmp restart.
I will try again, as I have reverted to the snapshot before starting the upgrade.

**Comment by VexedSyd** [comment]
php5-fmp doesn't exist as a service on my server.

**Comment by Edtigoza** [comment]
try
**ls /etc/init.d/ | grep -i php**

and  
sudo service **result** restart

**Comment by VexedSyd** [comment]
ls /etc/init.d/ | grep -i php returns nothing at all :)

**Comment by nuxsmin** [comment]
@gabrielsoltz please let me know what is displayed on the Javascript console (F12)

@Edtigoza the maintenance message could be there because the session lifetime, it caches the config data so if the maintenance option was set (automatically set when upgrading), it will be there until browser reload or the PHP session is removed (by garbage collector)

@VexedSyd let me review the code for any existing issue.

This release is currently running on the demo site, so it should work fine on any browser (this issue is most likely related to Javascript), could you log in on the demo site?

Thanks for the feedback an support!

**Comment by nuxsmin** [comment]
Please try out the latest commit in the master branch.

**Comment by gabrielsoltz** [comment]
Hi @nuxsmin, with the last commit, now is working !
Thanks again.

**Comment by VexedSyd** [comment]
@nuxsmin Thanks a lot, the issue has been resolved with the latest commit.

**Comment by nuxsmin** [comment]
@gabrielsoltz @VexedSyd  that sounds great!

Thanks for the feedback!
