### ISSUE TITLE
LDAP warning on sysPass 2.1

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#540]
Hiya, after upgrading to syspass 2 i get the error when i test my ldap connection.

'[Thu Apr 13 17:24:10.693973 2017] [:error] [pid 27522] [client x.x.x.x:42216] PHP Warning:  ldap_error() expects parameter 1 to be resource, boolean given in /var/www/html/syspass2/inc/SP/Auth/Ldap/LdapBase.class.php'

Any clue as to what is going wrong?

**Comment by nuxsmin** [comment]
Hi, did it show any error on the screen?, Is there any error in the sysPass event log?

**Comment by bitking** [comment]
The error i get is:
Unable to connect to the LDAP server
Please check out the event log for more details

The error in the log is: 
 Unable to connect to the LDAP server
Server : prdo-dc01.olvg.nl:3268
LDAP ERROR : (0)

I can tell you the connection to the server is no problem when telnetting and on sysoass 1.2 running on the same server LDAP works fine.

**Comment by nuxsmin** [comment]
Ok, this issue could be because the server name, If you are using ADS, sysPass will pick a random server from your DNS by looking on `_msdcs.` records. This done so because if a DC server is down it will have more probability to pick an active server.

Please, check out your DNS records (if using ADS): https://msdn.microsoft.com/en-us/library/bb727055.aspx

**Comment by bitking** [comment]
Hi Nux, i dont understand why. i put in the Domain Controller fixed i never had this problem with any of my services. Why would i even have to put in a servername then for the domain controller.

**Comment by nuxsmin** [comment]
Hi @bitking 

this is a sysPass behavior, that would increase the chance of picking an active server and not a fixed one. I think it could be switched off by an option in the next release.

This behavior was implemented because sometimes, if the DC that was set is down, the log in process becomes longer while the timeout is reached, so I decided to pick a random server to minimize this issue.

**Comment by bitking** [comment]
I see, can you make it that first it try's to connect to the given ldap server and if thats not reachable it does the DNS thing? now it even seems redundant to ask for a servername since it doesnt use it properly.

**Comment by nuxsmin** [comment]
The server name could set to an IP address, so the random pick behavior will not take place.

The DNS ping will lead to a timeout if the server is not reachable so the log in will be also delayed. Since threading is not possible (really not advisable) on PHP web applications, the main thread will be blocked until the DNS response is received, so the random way would be the best.

However, an ADS DNS misconfiguration will lead in a general performance issue, because every request done to the domain (ie. GPO, login, etc) is balanced through the DC servers in the site, and those servers are got from the DNS.

**Comment by bitking** [comment]
In that case i think something else is the issue. i forgot to mention that ip adress is also not working.

**Comment by nuxsmin** [comment]
Could you give q try to the latest commit to the master branch?. The LDAP port wasn't used at all, so it only uses the default one or the implicitly set for the uri protocol (ldap:// or ldaps://)

**Comment by bitking** [comment]
Thanks i try'd the new commit and it still isnt able to connect. Without the port it connects and says invalid credentials but i know 100% for sure the password is right i even made a new account and on that one it says invalid credentials. Really strange i think.

**Comment by nuxsmin** [comment]
Hello, by enabling sysPass debug mode it will log a lot of messages in the werserver log, so you can get some more info about what could be happening.

As I know you're using a global catalog server for querying, so be aware that the DC synchronization should be done before logging in.

**Comment by bitking** [comment]
I send you the private gist with debug mode on.

**Comment by nuxsmin** [comment]
Sorry for the delay...you can send it to nuxsmin "at" syspass "dot" org

**Comment by nuxsmin** [comment]
Hey, it seems that your LDAP server is throwing DSID-0C0903C8 error (at the end of your gist) which means "Invalid credentials":

https://social.technet.microsoft.com/Forums/windowsserver/en-US/474abb8f-cfc6-4cac-af79-c3e80e80291f/ldap-authentication-error-ldap-error-code-49-80090308-ldaperr-dsid0c090334-comment?forum=winserverDS

**Comment by nuxsmin** [comment]
Another link: http://stackoverflow.com/questions/22112130/ldap-error-code-49-80090308-ldaperr-dsid-0c0903a9-comment-acceptsecuri#22375241

**Comment by nuxsmin** [comment]
![captura_098](https://cloud.githubusercontent.com/assets/1775774/25342897/b67037a0-290d-11e7-8558-92830bd65cbd.png)

**Comment by bitking** [comment]
Yeah and that msg is incorrect! the credentials are 100% correct like i said i even made a new account which is getting rejected with this msg and i dont understand where it is coming from.

**Comment by nuxsmin** [comment]
Sure, but it could be that it requires to change the password or it's expired. It's likely a multipurpose message

**Comment by bitking** [comment]
Yes i understand that and the password is not expired, is set to next expire and i can use it with syspass 1.2 no problem and when authenticating with it against AD it works so clearly it is not a password problem.

I dont have a clue what else it can be, i think i am gonna start a syspass instance from scratch to see if the upgrade has anything to do with it.

**Comment by nuxsmin** [comment]
Did you still receive the error posted in the first message?

**Comment by bitking** [comment]
Yes.

**Comment by nuxsmin** [comment]
Are there any more errors?
