### ISSUE TITLE
@nuxsmin, where's the tool for decrypt password in xml format ?

### ISSUE THREAD

**Issue by NickWoo33** [nuxsmin/sysPass#541]
Hi, 

I search the issues, looks there's a tool for decrypt the xml password ?

Could you please tell me where I can download it ?

Thanks.

**Comment by nuxsmin** [comment]
Sure! Thanks to @julenpardo who developed this nice tool: https://github.com/julenpardo/sysPass-XML-Decrypter

It needs PHP 7.0 and some dependencies that will be got by `composer`

I will integrate this tool in sysPass so you won't need to get the dependencies, because they are already within sysPass

**Comment by akzov** [comment]
Doesn't work
