### ISSUE TITLE
How can I create a new user to manage/view with restrict group/catalogue ? 

### ISSUE THREAD

**Issue by NickWoo33** [nuxsmin/sysPass#547]
I would like to create a new user.

And I want to divide all my user/password into 2 part (group? catalogue?)

I (admin) can manage/view all of them.

But new user(not admin) only can manage/view assigned part(group? catalogue?).

The new users only have permission in assigned category? or customer? 

Is that possible ?

Thanks.

**Comment by nuxsmin** [comment]
Hello, the main restrictions for users are applied to the user and their groups. Neither category nor customer are being used on restrictions.

The ACL is explained on: http://doc.syspass.org/en/application/permissions.html

Kind regards.

**Comment by NickWoo33** [comment]
OH, I see, I can set the Accesses while add a new user/password.

But how can I do the import with these Accesses  settings ?

**Comment by nuxsmin** [comment]
That feature isn't currently available, so you would need to set them after importing.

**Comment by NickWoo33** [comment]
looks it just can set it one by one ? can't by group or cata. 

>_<

**Comment by nuxsmin** [comment]
Unfortunately, currently there is no way to do it, because batch access modification is a time consuming development task, although it's quite interesting I've been focused on day​ to day features rather on one-time ones.

Hopefully it would be available in the next release.

How many accounts do you want to import?
