### ISSUE TITLE
Encoding::hexToBin() input is not a hex string.

### ISSUE THREAD

**Issue by yosugk** [nuxsmin/sysPass#548]
Syspass show this error when I try to show a password after upgrading from 1.2 to 2.1

Encoding::hexToBin() input is not a hex string.

**Comment by yosugk** [comment]
After exporting to xml some keys, old keys format are different from new ones. As example, a key that show encoding error is like:
<pass>eḋỳṗÔTÆñÿÄÄḋãû:ṡîÊFK/Ëg</pass>
and new keys looks like:
<pass>bca50200e1af92386a90b20a75923446f6bff6a9058f5e6dfe407d3b5d3457d8a206db53c6daff217d6f525d952102239e9456e491b057c47d12339e43355438c3ccd163d14819adf1d19ecc3645aff8e191dbb5312fdbd3</pass>

Maybe something goes wrong when upgrading. I reenter password for all accounts again and now there is no encoding error.

**Comment by nuxsmin** [comment]
Sorry, I missed your issue...

The binary key form was used on previous versions, but as of 2.1 a new encryption schema has been implemented, so that binary data tells that the upgrading process went wrong, so there would be some messages in `syspass.log`file within the `config` directory.

Your solution is effective, but reentering all the passwords is pretty tough. Please be aware that custom fields are also encrypted so if you use them, the data could be corrupted.

Thanks for the feedback!
