### ISSUE TITLE
XML import

### ISSUE THREAD

**Issue by roosei** [nuxsmin/sysPass#556]
Hi, is there any special requirements for KBDX databases export? I'm not able to import any data from big KBDX database - when I do an export to XML 2.0 (just one small group), approx 300kB, sysPass doing something for loong time (maybe until timeout) then writes nothing and nothing is imported (log is clean).
When trying to import whole database I get error "file size not allowed" (is there any way how raise this limit?) or "El número de campos es incorrecto (1)" with CSV.
Any ideas? Thank you!

**Comment by nuxsmin** [comment]
Hi, the last error is so weird, because you are trying to import an XML file, not a CSV instead.

Regarding the max file size, this value can be changed on the Files tab under Configuration > Accounts.

I'm trying to figure out what could be happening but it seems that some timeout could being triggered.

Regards.
