### ISSUE TITLE
LDAP Attribute Settings no saved 

### ISSUE THREAD

**Issue by JamesUoM** [nuxsmin/sysPass#572]
Using the docker instance

I set Login attribute = uid and Name attribute = fullName. Click save. Navigate to another tab and back again and they are reset to the default values.

**Comment by nuxsmin** [comment]
It's right, those are attributes for importing users.

Be aware that you don't need to import the LDAP users, because they will be created on the very first log in with the default group and profile set.

And don't worry about the login and name attributes because they will be checked all while logging in..
