### ISSUE TITLE
Estimate PostgreSQL and SQLite DB support

### ISSUE THREAD

**Issue by Kulak** [nuxsmin/sysPass#582]
If I want to use this project for a small self-hosted setup, I'd like to use SQLite because it will fit perfectly.  I already have PostgreSQL installation, so I would like to use that if SQLite is too different.

I identified the following DB specific parts:

1. inc/sql/ contains MySQL schema.  How much of it is MySQL specific?
2. inc/SP/Storage/MySQLHandler.class.php is responsible for creation of DB connection.  It seems that other DB's would be almost identical.  Your design assumes creation of per DB file (PgreSQLHandler and SQLiteHandler).  Is this correct.
3. How DB specific are other files in inc/SP/Storage/?
4. It seems that SQL statements are spread around specific domains (inc/SP/Mgmt/Groupps/GroupAccounts.class.php, inc/SP/Core/Upgrade/Profile.class.php). How much of it is DB specific?

This is not a work item to create support for either of DBs.

**Comment by derStephan** [comment]
I think, the first problem with SQLite is that is not type-safe. So whenever syspass relies on type checking within the database, this has to be rewritten in PHP.

The second problem is the lack of constraint checks in SQLite. Foreign keys can be defined but the database does not check anything. This has to be rewritten in PHP as well. 

And the third problem is, that the whole database is locked in SQLite as soon as one operation is done. So if you have concurrent workloads (e.g. many users) then you will probably see random timeouts for some of them. 

Just my 2 cents.

**Comment by nuxsmin** [comment]
Good points @derStephan, Thanks!!

I think that SQLite wouldn't fit sysPass requirements.

@Kulak Let me take a look to your points and I'll be back with some thoughts.

Kind regards

**Comment by nuxsmin** [comment]
@Kulak as you could see in the sysPass code, it uses PDO for the database management, so every query is done through this API. By this way, any database operation is sent to the DB driver in a normalized way. The only API that would change could be that related to the connection, so there is a DI (Dependency Injection) that will pick the right database connection class in `inc/SP/Storage/`.

Regarding your points:

> inc/sql/ contains MySQL schema. How much of it is MySQL specific?

There are some datatypes that won't fit on the PG schema and the engine type will need to be changed/removed.

> inc/SP/Storage/MySQLHandler.class.php is responsible for creation of DB connection. It seems that other DB's would be almost identical. Your design assumes creation of per DB file (PgreSQLHandler and SQLiteHandler). Is this correct.

Right.

> How DB specific are other files in `inc/SP/Storage/`?

This namespace is used to contain every storage related class, so there are some interfaces that need be implemented to make use of any specific storage.

> It seems that SQL statements are spread around specific domains (inc/SP/Mgmt/Groupps/GroupAccounts.class.php, inc/SP/Core/Upgrade/Profile.class.php). How much of it is DB specific?

Right, every SQL query is implemented in its own method/domain, because I haven't found yet any suitable way to store the queries and get them easily.

Finally, I think that it wouldn't be tough to implement a PG storage schema, because sysPass doesn't rely on any special functions or procedures (only views and constraints).

Regards

**Comment by Kulak** [comment]
Thank you

While concurrency on small loads is of no concern on SQLite, key integrity is (I assume for this design).

My conclusion: SQLite does not fit the model and PG does.  

This has been most informative.
