### ISSUE TITLE
Event "checkTempMasterPass" does not have a pretty name in the event log

### ISSUE THREAD

**Issue by Nadermane** [nuxsmin/sysPass#585]
Just a very quick report; in the event log, nearly all events have a pretty name. However, "checkTempMasterPass" doesn't have a nice name like "Check Temporary Master Password", or more correct in the event log case, "Temporary Master Password", as the event description is "Temporary password expired".

**Comment by nuxsmin** [comment]
It's done so because the large version of the action name would be very large to fit in the table cell, so I decided to return the function name instead of an alias. 

Some action names aren't aliased because it would provide the function name which triggered the event, so code debugging would be easier.
