### ISSUE TITLE
LDAP User Import Not Working

### ISSUE THREAD

**Issue by nikhilc89** [nuxsmin/sysPass#591]
Hi,

I'm trying to import users from openLDAP (using FusionDirectory) and when trying to import, it shows:
LDAP users import finished
Imported users : 0/75
Errors : 0

Checked this link already: https://github.com/nuxsmin/sysPass/issues/544
But didn't help.

Trying to import with:
Login Attribute: uid
Name Attribute: cn

When clicking on the 'Check' button, it shows the accurate number of entries in LDAP.
When logging in, it works fine and the user is then imported into the system.

Any suggestions on what can be done to import the entries?
Version: sysPass 2.1

**Comment by vvascautan** [comment]
Hello All,

The same on my side, I left "Group" parameter emty, syspass detects users but doesn't import them.
Tried with Group name but no luck. Also tried with * also no luck.

Additional suggestion is to include multiple option for Login and Name attributes or left them editable.

One more suggestion is to add possibility to add multiple LDAP configs, thus I will be able to add the same LDAP server with multiple LDA groups with different Profiles and Groups privileges. This could be related to https://github.com/nuxsmin/sysPass/issues/339

Thank you!

**Comment by Libeccio84** [comment]
Not sure, but this might help you https://github.com/nuxsmin/sysPass/issues/571

**Comment by nuxsmin** [comment]
@Libeccio84 thanks for your point!

I've modified an old gist that could be useful to debug the LDAP info retrieved. Please take a look to it (https://gist.github.com/nuxsmin/a6b2f2701ce8b78ceadd835adc26756a) and set your params, then save it in the sysPass root and point your browser to that URL.

Be aware that this script will output some LDAP info that you wouldn't like to be publicly available, so the only stuff I need to know is if the import attributes are being retrieved from the LDAP, because if either login or name attributes are blank, the import won't work.

Regards

**Comment by nikhilc89** [comment]
@Libeccio84 nope, #571 didn't help. I'm keeping the group part empty. It shows 0/75 users imported so it is able to search but not sure what exactly is it missing. The LDAP entries have both the uid and CN in place.
@nuxsmin anything else that the import script requires?
I used the above link you suggested and seems data is shown accurately.

Example of what is shown:

`
## User Filter: 
(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))
## User Entries: 
Array
(
    [1] => Array
        (
            [cn] => Array
                (
                    [count] => 1
                    [0] => Nikhil xxxxx
                )

            [0] => cn
            [sn] => Array
                (
                    [count] => 1
                    [0] => xxxxx
                )

            [1] => sn
            [givenname] => Array
                (
                    [count] => 1
                    [0] => Nikhil
                )

            [2] => givenname
            [uid] => Array
                (
                    [count] => 1
                    [0] => nikhil
                )

            [3] => uid
            [displayname] => Array
                (
                    [count] => 1
                    [0] => Nikhil xxxxx
                )

            [4] => displayname
            [count] => 5
            [dn] => uid=nikhil,xxxxxxx 
        )

`

**Comment by vvascautan** [comment]
Hello,

I think the problem is with filtering, as I get error when syspass try to filter by memberOf attribute which mostly is used in Active Directory while in my LDAP attribute is memberUid.
" LDAP FILTER : (&(|(memberOf=*****"

This is why filtering attributes would be great to be adjustable.

**Comment by nuxsmin** [comment]
@vvascautan you're right, the group filtering is being done using memberOf attribute, but don't worry about the implementation, because each schema (ADS and "others") has its own implementation, so new filters could be easily implemented:

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapMsAds.class.php#L46

https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapStd.class.php#L46

> This is why filtering attributes would be great to be adjustable.

I don't want to bother to he people to deal with LDAP stuff since it's a very common source of issues, because of building an LDAP filter could be a bit tough.

**Comment by nuxsmin** [comment]
@nikhilc89 Right, it seems ok. Let me figure out what could be happening...

Thanks for testing!

**Comment by nuxsmin** [comment]
@nikhilc89 sorry for the late response, I've been very busy for last two weeks...which is the sysPass full version number you are running?

**Comment by nikhilc89** [comment]
@nuxsmin no worries. The full version number is: sysPass-2.1.9.17050401

**Comment by nikhilc89** [comment]
@nuxsmin The new release 2.1.10.17053003 fixes the LDAP import. Thank you.

**Comment by nuxsmin** [comment]
@nikhilc89 that's really weird because the only issue solved that was related to was #561.

Thanks for the feedback!

**Comment by H4ndl3** [comment]
@nuxsmin the issue still persists for me. In the LDAP configuration everything works just fine (except for group filtering, that seems to be broken) but importing users doesn't work. Same error as @nikhilc89 had.
