### ISSUE TITLE
Wrong login after enabling LDAP

### ISSUE THREAD

**Issue by tiagosleal** [nuxsmin/sysPass#601]
Hello,
After I've enabled LDAP, I can't login as Admin user. Displays wrong password every time.

I use version 2.1.9.17050401.

I've reinstalled the application and the database several times and the problem persists.

Despite the reported problem, I found the tool very useful and I'm trying to deploy it on the production network.

Thank you in advance.

**Comment by nuxsmin** [comment]
Hello,

please be aware that if there is an "admin" user login in LDAP, it'll take precedence over the sysPass "admin" user. If you need to access to sysPass, you can disable LDAP in the config file (`inc/config.xml`)

Regards

**Comment by tiagosleal** [comment]
Hello,

It was just that! There was an admin user at freeipa.

Sorry for the issue

I'd like to know if you're going to have any features that allow to export accounts offline.

Thank You

**Comment by nuxsmin** [comment]
No worries ;)

Yes, I'm thinking about how to implement such feature (on a mobile app), because it need some security requirements. BTW there is an exporting tool for sysPass XML files. It has been developed by a contributor: https://github.com/julenpardo/sysPass-XML-Decrypter

I'll integrate it into sysPass, so you won't need to get additional dependencies.

Regards
