### ISSUE TITLE
How can I generate a secondary (one-time) master password? Is it needed for any new login/device (mobile)?

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#619]
Please tag this "documentation" - I couldn't figure this out in a quick docs review.

[Here](https://www.reddit.com/r/selfhosted/comments/57g09i/syspass_is_a_web_password_manager_written_in_php/dcxozxf/) there is mention that a secondary (one-time) master password can be generated so a new user logs in the first time on  a new system or environment (mobile, etc.) can authenticate. How can this be done from the web UI?

Is this also needed for every single new device or environment that a new user will be needing?

For IT staff this is already hard to explain to junior colleagues, it's borderline unpractical and defeats the purpose of centralized password management for other non-IT employees. I wish there was a way to abstract this out of the UI, in the meantime if it can be documented in detailed I'd love to help and test the result.

**Comment by nuxsmin** [comment]
You're right, some features could be not well documented because I thought that the UI "let you learn" about them. Actually I need some time to document every function/feature, so I prefer to build a better UI/UX that gives the information that the user needs.

Regarding the master key, it¡s generated for a period of time, so the users can use it until the expiration time is over. This key is set per-user (but many users can use it when logging in), so there is no need to generate it on every new device.

Be aware that the master key should be managed by the admin staff.

Regards

**Comment by nuxsmin** [comment]
Done https://doc.syspass.org/en/application/encryption.html#clave-maestra-temporal
