### ISSUE TITLE
problem with email recipient

### ISSUE THREAD

**Issue by dmaniad** [nuxsmin/sysPass#622]
Hello,
I am using sysPass 2.1.9. I think that there is a problem with email notifications.
Or maybe I have misunderstood the email notifications process. Who should receive notification emails? The admin? The users? Please help!
Specifically, whatever I fill in the field " Recipient email address" is accepted but is not taken into account.
It will finally regard as email recipient the same user account I put as sender.
I always get the email notifications at the sender email address and not at the recipient email address.
Maybe an error in inc/SP/Log/Email.class.php  ?
$mailTo is always set as '' (empty) so it sends to the sender(!).

**Comment by nuxsmin** [comment]
Hello, email notifications are sent whenever either  an account or the configuration is modified, and the recipient will be the email address which is set in Cc field. The "To" field is dynamically set, because some notifications will be sent to the users (eg. when requesting an account access -sent to owner and lastest editor-).

Regards

**Comment by sksksksk** [comment]
The basic problem is the following:
If the "User" field (for email sending authentication) is different than the "Recipient email address" no notifications are sent at all.

Setting as "User" the same email address as the "Recipient email address", we get notifications for e.g. changes in syspass settings to this email address.

So the question is: how can we get notifications to a different email address than the one used for SMTP authentication?

**Comment by nuxsmin** [comment]
Sorry about my explanation, since "recipient" address is not so accurate, because it's intended to be used as "From" field, so every email sent from sysPass will have set this sender address, instead of the auth user.

> If the "User" field (for email sending authentication) is different than the "Recipient email address" no notifications are sent at all.

It could be happening because your server does not allow to send emails from an address that doesn't match with the auth user.

> So the question is: how can we get notifications to a different email address than the one used for SMTP authentication?

Currently there isn't such feature, but it will be implemented in next version.

Regards.
