### ISSUE TITLE
Change login attr for LDAP users

### ISSUE THREAD

**Issue by marawu** [nuxsmin/sysPass#627]
Hi, how to change login attr? I write:

`  <ldapUserattr>mail</ldapUserattr>`

but it not work.

I want use mail for login.

**Comment by nuxsmin** [comment]
Unfortunately the login attribute cannot be changed by the moment, but it will be possible in future releases.

The LDAP login will look up for several attributes like: `samaccountname`, `cn` and `uid`

BTW, you can tweak https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapStd.class.php#L74 or https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Auth/Ldap/LdapMsAds.class.php#L102 files to get it.

Regards

**Comment by marawu** [comment]
Hmmm...i add attr, but he has not appeared:

```
# grep mail {inc/SP/Auth/Ldap/LdapStd.class.php,inc/SP/Auth/Ldap/LdapMsAds.class.php}
inc/SP/Auth/Ldap/LdapStd.class.php:        return '(&(|(samaccountname=' . $this->userLogin . ')(cn=' . $this->userLogin . ')(uid=' . $this->userLogin . ')(mail=' . $this->userLogin . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject)))';
inc/SP/Auth/Ldap/LdapMsAds.class.php:        return '(&(|(samaccountname=' . $this->userLogin . ')(cn=' . $this->userLogin . ')(uid=' . $this->userLogin . ')(mail=' . $this->userLogin . '))(|(objectClass=inetOrgPerson)(objectClass=person)(objectClass=simpleSecurityObject))(objectCategory=person))';
```

**Comment by nuxsmin** [comment]
By adding the mail attribute it will be available to log in using the user's email, so the newly created users will have the login field set to their email. Be aware that if an already created user changes his login (by logging in using his email), it will create another user, because the unique identifier is the user's login.

I know it's a bit confusing, so please make some tests on a replicated environment.

**Comment by marawu** [comment]
I try login uses email, but i see baner "Internal error". Log file empty:(

**Comment by nuxsmin** [comment]
Added to roadmap #422
