### ISSUE TITLE
Question about export XML and item restore

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#629]
Hello.
How can i use the exported XML file? Have some software to open it and show the passwords?
Maybe if you can add a feature to export as Keepass format would be nice.

And, how restore a deleted item (or user)? Can't find it, just the logs...
Also, an option to encrypt username would be good too, for people that don't will use search fuctions for users...

Ah, can i use modsecurity on the server? Some problem with it?

Thanks for this good project.

**Comment by nuxsmin** [comment]
Hello,

There is a tool (sysPass XML decrypter) to export the sysPass XML file, but you will need to tweak it a bit, because it will export the data for importing on lastpass.

I'll improve this tool to allow to perform queries, so you won't need to decrypt all the data.

Regarding the items deleted, the only items that can be restored are the accounts, but currently there isn't such function, so you can only restore them from a modification. BTW those deleted accounts are stored in a db table.

Regards.

**Comment by ortizleo** [comment]
Teampass have a good export feature, he create one html file encrypted.
Its cool, take a look.

About modsecurity, can i use it with your tool?

**Comment by nuxsmin** [comment]
I think so, modsecurity would enhance your webserver security and sysPass doesn't require any special URL handling.

I'll take a look to that html feature.

Thanks for the feedback!
