### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by KevendeOliveira** [nuxsmin/sysPass#646]
Hello!
I'm starting to use this application and I have a question: what is the status of the Portuguese translation?
Because I tried to compile the .mo and put it in the same .po folder and the translation did not automatically appear in the selection list of the web interface. Do I have to edit any more files?
Sorry for English, I'm Brazilian and had to use some Google Translator.

**Comment by nuxsmin** [comment]
Hello @Kevendeaoliveira,

Currently, the Portuguese translation is pending for completing, because they're many mistakes in the translations (I've told them 2 times to the translators a time ago). Those mistakes are related to the letters case (upper or lower), which aren't correctly set from the original source. There are also some missed spaces (added or removed).

When those issues were solved I'll add the language to the selection list (it isn't dynamic).

Please check out for the translations on poeditor website. I'll kindly add you as a translator (if you weren't added yet)

Regards

**Comment by KevendeOliveira** [comment]
Hello! I have sent a request to contribute the translation through the POEditor site. You can verify?

**Comment by nuxsmin** [comment]
Accepted
