### ISSUE TITLE
Attempts exceeded  message while connecting to syspass

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#647]
Hi,

I am getting "Attempts exceeded" error message while logging into syspass tool.
please let me know how to fix this issue.. also, please let me know how to reset master password?.

Thanks,
Anil.

**Comment by nuxsmin** [comment]
Hi, the attempts exceed behaviour is because you entered either a wrong username or password for 5 times within 10 minutes, so the application will block you.

I'm sorry to tell that the only way to change the master password is logging in with a valid user and then perform a master password change.

Regards

**Comment by anikarunakaran** [comment]
ok, i had an admin user created and i'm able to login with that user..  when we go to configuration option, encryption tab, its asking for current master password.. please advise how to change master password in this case?.

**Comment by anikarunakaran** [comment]
appreciate your help to resolve this issue as we have all accounts details entered in syspass and now we are in a position that, we cannot add any user without master password.
please help us to resolve this issue..

thanks,
Anil.

**Comment by nuxsmin** [comment]
Please, replace this file https://gist.github.com/ca59f3754312fb6d54b2cf45283bf754 and then activate the debug mode in the site config tab.

The file is placed in 'themes/material-blue/views/common' directory
