### ISSUE TITLE
Authentication via Active Directory

### ISSUE THREAD

**Issue by yh113** [nuxsmin/sysPass#661]
Hello,
 I installed PHP7.0 on CentOS 7 and installed sysPass 2.1.11.17061503. I would like to thank you to such a great software.

 I have an issue regarding Active Directory integration. I configured LDAP as attached but cannot import users. Do you have any idea how to rectify the configuration? Honestly I am new to LDAP.

 I am translating it into Japanese via POEditor (now 11% done), and after completing translation I will write a technical article to spread this software into Japan. Thanks a lot!
![log2](https://user-images.githubusercontent.com/29861930/27864448-94364fcc-61c9-11e7-85fc-f65a87356044.png)
![log1](https://user-images.githubusercontent.com/29861930/27864447-9435ae32-61c9-11e7-99ba-f2a99e17852f.png)
![conf2](https://user-images.githubusercontent.com/29861930/27864449-94367e98-61c9-11e7-9b3b-34c2da048bc0.png)
![conf1](https://user-images.githubusercontent.com/29861930/27864450-943bf238-61c9-11e7-8e34-81ddb32fdb52.png)

**Comment by robpac** [comment]
Hello,

I have exactly the same versions installed and have made several tests with AD authentication.
Just using Search base is sufficient for allowing users to log in.
As far as I understand it, when adding a group then only users in that group are allowed to login otherwise all users in Search base.
I haven't been able to test it thoroughly because my AD admin mentioned that groups and users are managed in different OUs. And furthermore he uses nested groups in AD which is from his point of view best practice in AD management.
I have two additional questions which might be helpful in this thread:
Is it possible to have users and groups in different OUs ?
Will syspass support nested groups ?

Great software ! Thx, Rob

**Comment by nuxsmin** [comment]
@yh113 it's nice to know that you're interested on spreading sysPass

Regarding the LDAP integration, you need to know which LDAP attributes are being used for username and login, but if you checked out LDAP connection and users were found, you don't need to import them, because sysPass will add every user on his very first login. Default group and profile will be used when adding them.

@robpac, I'm glad to know that you found sysPass useful. The nested groups is already implemented, so you only need to set a search base on top of those OUs

Regards
