### ISSUE TITLE
Questions on syspass

### ISSUE THREAD

**Issue by anikarunakaran** [nuxsmin/sysPass#671]
1. We have observed that, syspass does not work properly in Internet Explorer 11(works fine in google chrome), what is the supported version of internet explorer.

2. Copy password to clipboard option does not seems to working and it shows "Error while copying to clipboard" error.

please let us know how to resolve this issue.

Thanks,
Anil.

**Comment by ortizleo** [comment]
Problem 2 here too, if you try 3 times it works, i think that is something in the session.
Also, @nuxsmin, im using syspass for 1 month with more 5 users, we are loving your software, very good work! 
Below some things that our team pointed, you should take a look:
1. Option to "Copy password to clipboard" for others users on home screen (without need to enter in item and copy password from custom field).
2. Custom field for more users, something like: "text field" "Password field" using a react code, or like
This field will play with 1.
3. Force 2FA and easy way to disable if user lose his gauthenticator..
4. Favorite stay checked if user logoff/logon
5. More clean  home screen, maybe option to results be the categories..
6. Hide categories if user haven't access..
7. Posibility to set a custom field for specific custumer or categories, today one custom field apply for all itens...
8. Password expiry disable
9. Mail to admin, group or specific user when an account is accessed 
10. a recycle bin

Bugs
1.  2 from OP
2. Why custumer colors change when logoff/logon?
3. When we try recover user password, syspass ask for the old password..

**Comment by nuxsmin** [comment]
@anikarunakaran regarding your points:

> We have observed that, syspass does not work properly in Internet Explorer 11(works fine in google chrome), what is the supported version of internet explorer.

Unfortunately, sysPass hasn't been well tested on IE 11 because a lack of time :(

> Copy password to clipboard option does not seems to working and it shows "Error while copying to clipboard" error.

This is a known issue on some environments that is related to browser's security, because it doesn't allow to copy to clipboard when data is retrieved from an async request without user interaction (it's a complex behavior).

@ortizleo I'm very glad to know that you found sysPass useful :)

Regarding your points:

> Option to "Copy password to clipboard" for others users on home screen (without need to enter in item and copy password from custom field).

I'll study how it could be achieved.

> Custom field for more users, something like: "text field" "Password field" using a react code, or like. This field will play with 1.

Sorry, I didn't understand this point.

> Force 2FA and easy way to disable if user lose his gauthenticator..

Planned in roadmap #422 

> Favorite stay checked if user logoff/logon

If I understood well, you request to save user filtering between logins, don't you?

> More clean home screen, maybe option to results be the categories..

Because it's an UI request, the easy and fast way is to make your own theme based on the existing one. Just clone it, setup "index.php" file and modify the search views.

> Hide categories if user haven't access.

Currently the category access option is related to categories management, but users should be allowed to filter by.

> Posibility to set a custom field for specific custumer or categories, today one custom field apply for all itens.

Planned in roadmap #422 
> Password expiry disable

Planned in roadmap #422 

> Mail to admin, group or specific user when an account is accessed

Nice feature. Will be planned :)

> a recycle bin

This is already implemented for accounts, since other items are easily "trackable" by searching in the event log. It doesn't mean that it wouldn't be useful, but I need to prioritize some -tough- features than others because a matter of time...

Bugs

> Why custumer colors change when logoff/logon?

Actually it's inspired in GMail / Inbox behavior, but it's planned to implement an option to set an static color.

> When we try recover user password, syspass ask for the old password..

Solved in latest commit :)

Thanks for your feedback!!

Regards
