### ISSUE TITLE
Restrict Public account

### ISSUE THREAD

**Issue by shobhangev7** [nuxsmin/sysPass#683]
Hello Team,

you are developing an amazing product.

I have a questions,
I have installed sysPass latest version.

I Want only Private and Private for group account.
I don't want user to add the public account

How would I restrict to add public account for all user and admin.
 
Thanks

**Comment by nuxsmin** [comment]
Hello @shobhangev7 

I'm glad that you found sysPass useful.

Unfortunately, app wide private-only accounts are not implemented, because the app purpose is to be a collaborative multi-user password manager, so making them private means no collaboration.

You could achieve it by setting an unique main group for every user, so if the user creates a public account, it will only be visible by its main group and the owner (the admin would see it). 

Regards

**Comment by shobhangev7** [comment]
Hello nuxsmin,

Thanks for your support.

I have already integrated the syspass with AD/LDAP  
I am working in an organization where more than 1500 employees work so I think practically it is not possible to make that.

Can you please suggest another solution?

Regards,
Vidhyabhushan.

**Comment by nuxsmin** [comment]
Umm, the only way without too much hassle would be by editing https://github.com/nuxsmin/sysPass/blob/master/inc/SP/Forms/AccountForm.class.php#L94 file and replace `Request::analyze('privateEnabled', 0, false, 1)` to 1, so every account will be always private.

Be aware that a sysPass update (manually done) will replace that file.

Regards.

**Comment by nuxsmin** [comment]
Added to roadmap #422
