### ISSUE TITLE
Syspass db replication

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#685]
Hi.
We are setup syspass in a master-slave replication with mariadb, at rowlevel.
As a good pratice, i want set mariadb as read only on slave db, so this syspass server will only for read access (will replicate syspass folder too but with scp weekly)..
But when i set mariadb as read only, can't login with any user, get 404 "The requested URL /undefined was not found on this server.". Maybe i can make mariadb ignore some table, but dont know which and the risks...
Can you help me?

**Comment by nuxsmin** [comment]
Hi,

unfortunately sysPass won't work in read-only mode because it stores some data on every login and :

- Tracking of login attempts (`track` table)
- Login events (`log` table)
- Update of user's data like last login date, password (if using LDAP). (`usrData` table)
- Update of accounts' counters for views and decryptions (`accounts` table)

Kind regards

**Comment by ortizleo** [comment]
And just for login? to test the slave server...
Track, log and usrData tables can be ignored on mysql replication...

**Comment by nuxsmin** [comment]
Those tables need to be replicated, so whenever the slave is active, they can't be in read only mode because the app will fail.

**Comment by ortizleo** [comment]
Hmm. Fine. Thanks.
