### ISSUE TITLE
mail not working

### ISSUE THREAD

**Issue by shobhangev7** [nuxsmin/sysPass#691]
Hello Team,

I have installed syspass 2.1
when I click Lost your password for LDAP user it opens Request password change page but after entering username and mail-id it shows error "Solicitud no enviada Compruebe datos de usuario o consulte con el administrador"

**Comment by nuxsmin** [comment]
Hello!

This issue could be related to either the user hasn't set its email, he's an LDAP user, the reset attempts are exceeded or the user is disabled.

It doesn't display a more accurate message because it would tell some valuable information to an attacker.

Kind regards

**Comment by shobhangev7** [comment]
I checked email has been set already and for reset attempts it shown me even at first time when I try to reset password

**Comment by nuxsmin** [comment]
Umm, sorry I didn't notice that you are trying to reset an LDAP user pass, it is not possible since LDAP credentials are managed by the LDAP server, so sysPass will not let you change it.

**Comment by shobhangev7** [comment]
hmmm..is it possible to change the password of user for only the sysPass dashboard and not to LDAP?

**Comment by nuxsmin** [comment]
Since sysPass is connected to LDAP, it will firstly check the user and password in LDAP, so if it fails, the user won't be granted to log in.

If you are using an LDAP group for filtering, you could remove the user from that group and then LDAP won't be mandatory for that user, BUT you would need to unset the LDAP flag in the user data record in sysPass DB (`usrData` table).
