### ISSUE TITLE
 Columns are not aligned with information

### ISSUE THREAD

**Issue by ArkaineHeinlein** [nuxsmin/sysPass#697]
Hello,
First, thank you to the whole team and the community for the work provided for this password manager.
I have an alignment problem with the Name, Category, User and IP columns.
Do you have a solution ?
Thank you.
Best regards,
David
![2017-08-14_16h46_51](https://user-images.githubusercontent.com/30461640/29276925-6ff148d6-8110-11e7-830e-76051dd8ce34.png)

**Comment by nuxsmin** [comment]
Hello,

I'm glad to know that you found sysPass useful :)

Regarding your issue, it has been discussed a few times and such behaviour is because the filtering fields are not related to the records displayed, since there will be more filtering fields in a future, which won't have a matching record's data, eg. Number of views, expiry date, favourites, ...

Thanks for the feedback!

Regards
