### ISSUE TITLE
When running a backup from the GUI i get the following error

### ISSUE THREAD

**Issue by bitking** [nuxsmin/sysPass#701]
Hi there,

When running a backup from configuration -> backup -> perform i get the following error.

Iterator RecursiveIteratorIterator returned a file that could not be opened "/var/www/html/syspass/config/config.php.backup-13042017"

Any clue as to what this is causing?

Ubuntu 14.04.5
Syspass 1.2.0.21
PHP 5.5.9-1ubuntu4.22

And the config directory has the permission 750 and the owner is www-data.

**Comment by nuxsmin** [comment]
Hi,

It seems that you created that file 'config.php.backup'  with another user that the webserver one, so sysPass backup will fail because of that.

I have noticed that you're running sysPass 1.2 version, but 2.1 has been rolled out since a long time ago, so you could give a try to the latest which has a bunch of new features, security improvements (stronger encryption among others) and a nice look.

Kind regards

**Comment by bitking** [comment]
Thanks Nux, i am aware of 2.1. 
Problem is when migrating that performance was decreased significantly (its really slow, is that because of php session encryption?) and i still have problems with ldap not working whatever i am trying to do it cant retreive ldap users for a very strange reason so when i feel like i had a good nights rest and a lot of patience im gonna give 2.1 a new try.

**Comment by nuxsmin** [comment]
@bitking some LDAP issues have been fixed since 2.1 was released, so you could give a try to the latest version on the master branch (not rolled out yet as a release).
Regarding the session encryption, you can disable it on the configuration, since it's a security improvement and not needed on a standard environment.

Regards
