### ISSUE TITLE
Support for Accounts without username/password

### ISSUE THREAD

**Issue by joerg** [nuxsmin/sysPass#712]
Some accounts don't have a username/password combination but other means, like a private key or so. Amazon machines, for example, have a key deployed and even the username varies depending on the image used (ec2user for rhel/centos machines, ubuntu for ubuntu machines ...).
Currently username and password are required which means we have to fill in fake data just to have the file (private key) attached as file. Trying to use the private key as a password in syspass does not work as it is multiple lines long I guess.

**Comment by nuxsmin** [comment]
You're right, since it need to implemented by changing the database DDL, this feature is planned to be ready in next release.

Thanks for the feedback!

**Comment by vmario89** [comment]
Hello,
this issue is still a problem that syspass forces the user to enter a username. It should allow to use the filed with blank input too.

It is also buggy because the following input leads to error:
![grafik](https://user-images.githubusercontent.com/5631071/44260009-78d36b80-a213-11e8-869f-3497c1ae56b8.png)

It does not recognize the "<>"

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3. Thanks for the feedback!

Regards
