### ISSUE TITLE
showpass icon does nothing

### ISSUE THREAD

**Issue by DanielRuf** [nuxsmin/sysPass#715]
When creating a new login the eye icon does not toggle the type of the input. Even if it would change it, the value of the password input is the encrypted password.

So we get something like `t0d+Y8IVqjxSZ7wFYAyGt3ScyYkrNGm7s/geWt7Fw4vvHRqAYbKLSGVu9vKQUn5tSKQbtgvoCSpZgZJaaay21ZqVc5Eqa9nqKkvc0x0rYgzlIriRmS5qeByeom97DLB6o7/XmK7IZsy1mPIBdceO1O45BbDdmPDi/l238+tXMhk=` for `Password` and `Password (repeat)`.

Generated passwords can not be shown because of this.

**Comment by nuxsmin** [comment]
Hello, that's the correct behavior, since the password is encrypted using PKI after changing the cursor from the password box, so if you enter or generate a password you can only view it by moving the mouse over the eye icon (do not click on the screen).

Regarding the encryption, this encryption is only used to send the password to the server (client > server), once there it will be re-encrypted using the master key.

Regards

**Comment by DanielRuf** [comment]
Well, but how should that work in combination with the "generate password" function?

**Comment by nuxsmin** [comment]
It should work indeed (using FF 55 on linux):

![captura_022](https://user-images.githubusercontent.com/1775774/29920166-8be37944-8e4c-11e7-8cc6-9dbc3741f09d.png)

**Comment by DanielRuf** [comment]
Ah. It was not clear that it is a native title. It takes a while here in Chrome until it is shown. Would be better to toggle the password field itself. The UX is not optimal imho.

Also when you move outside of the password input it gets populated with the encrypted and encoded data. The next time you try to hover over the eye icon it shows the encrypted text, not the current password.

**Comment by nuxsmin** [comment]
You're right, but it's the only way to encrypt the password, because the browser does not allow to let it clear and then encrypt it when the form is submitted, since the javascript function cannot read a password field when submitting. That's a security behaviour....

**Comment by DanielRuf** [comment]
And how can we write down the generated password? Because it is very tricky to even get the generated one.

Did not yet take a closer look but I do not fully understand why the same JS function can not catch the submit event (preventDefault), encrypt the password and programmatically submit it.

So far this feature is hard to use. Either copy the generated password to the clipboard, use some data-attribute to toggle the password input, implement a tooltip with selectable text or something else.

Writing it down in another application (= focus is lost = just encrypted string in the title) or on paper (not a great idea) is not an effective or good solution =(

I think it can be solved and the UX greatly improved.

**Comment by nuxsmin** [comment]
You're right, there are many ways to get it but this behaviour is for security reasons, because I think that the passwords shouldn't be exposed for many time.

You can take a look to the overall application behaviour and take notice that passwords aren't exposed if they aren't needed, so everytime you need to view a password is will be retrieved from the server.

I know it could be a hassle, but it was developed with security in mind.

BTW, I'll try to find out a better solution.

Regards.

**Comment by ClemensSahs** [comment]
@nuxsmin 
reopen?

If generate a password it will be nice to open a overlay like "passComplexity" or/and "lock_open" (account-list)

And the next movement can be a "regenerate" and "use this"

So we have a ideal behaviour for user
