### ISSUE TITLE
Ask for previous password when LDAP password has been changed

### ISSUE THREAD

**Issue by PxReaz** [nuxsmin/sysPass#724]
Hi, 
is it possible to disable the field that ask previous password when a user has changed his LDAP password?
Because if he forgot the last password how would he recover his syspass account?

Thanks

**Comment by nuxsmin** [comment]
Hi,

The previous password is asked whenever the app detects that the user is entering a correct password and doesn't match with the previous one. This procedure avoids to require the master password, since if the user enters the previous password it will allow to get the encrypted master password.

If he doesn't enter any previous password, the master password will be requested.

Be aware that the app doesn't know anything about the password state, so if a user loses its password, that field should be skipped.

Regards.

**Comment by madboyprice** [comment]
Hi

I know this issue was closed but it does present a challenge. Today, with more emphasis on security, the use of OTP is more common. This means that every time I want to login to sysPass I am going to be challenged to enter my previous password, which I will probably not remember. I don't want all users to have to enter the master password, as that is on conflict with the security model that you have.

The configuration I have is using LDAP with OTP. Using LDAP with OTP is fine, unless I forget my previous password.

If I was to make changes to sysPass where would you suggest these be made.

Cheers
