### ISSUE TITLE
Make sysPass customizable

### ISSUE THREAD

**Issue by aeimer** [nuxsmin/sysPass#743]
Hi,
I would like to suggest an option to put a customizable logo somewhere on the page.
In Portainer it's possible to define an url which contains a logo. This logo will replace the original logo.
I know this is an absolutly nice to have feature, on the other hand it should be done quick.

Maybe this is possible with the new plugin-system?

Regards

**Comment by nuxsmin** [comment]
Hi,

since there are 3 logo images in the app layout (login, header and favicon), it's a bit though to implement such feature, because it will need to check and resize every image uploaded, so I think the best way is to upload the images directly.

Currently plugins system implements some app events (https://doc.syspass.org/en/application/plugins.html#eventos), but there isn't any event to load the main layout.

You can also achieve it by creating a new theme and then overriding the app images. Every theme within `themes` directory will be listed in the themes selector. You need to keep the theme structure.

Regards.
