### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by aurora** [nuxsmin/sysPass#749]
As #582 is closed, i would like to officially ask for PostgreSQL support. As far as i understand that should be possible and even not be that much of work to implement (?). I could probably do this myself, however, the spanish(?) source-code comments do not make it easy to understand what's going on ... :( ...

**Comment by nuxsmin** [comment]
Hello, since sysPass isn't using any MySQL specific functions, you can change the dsn and connection behaviour by implementing a new database connection class wrapper and then use it in 'DiFactory' class.

Please let me know if it worked for you and if it needs any specific changes in SQL queries.

Regards
