### ISSUE TITLE
Missing language strings at POEditor.com

### ISSUE THREAD

**Issue by davidpsc** [nuxsmin/sysPass#755]
Hi,

not a major thing this time, but there are a few Spanish language strings displayed in sysPass. Here are a few examples:

![image](https://user-images.githubusercontent.com/5638975/31115332-30b11532-a822-11e7-94c8-6b43f538ff3a.png)

![image](https://user-images.githubusercontent.com/5638975/31115536-1084f9b2-a823-11e7-9f41-c723d247e4bc.png)

![image](https://user-images.githubusercontent.com/5638975/31115554-2367a890-a823-11e7-8721-d124e2e07dbe.png)

I couldn't find any untranslated strings at POEditor.com so they seem to be missing there. Please add them so that they can be translated (to German for example).

Thanks, David

**Comment by nuxsmin** [comment]
Hmm, you're right some string are still untranslated, but they're listed on POEditor, but marked as fuzzy instead:

![captura_071](https://user-images.githubusercontent.com/1775774/31116830-c2262d2c-a827-11e7-9606-e23c364686a7.png)
![captura_070](https://user-images.githubusercontent.com/1775774/31116832-c538c74a-a827-11e7-88f2-d6a723b5f161.png)

Thanks for the feedback!

**Comment by davidpsc** [comment]
So fuzzy ones are not exported to sysPass? Because I came across a few entries which were translated correctly but have the status "fuzzy"

**Comment by nuxsmin** [comment]
Let me check it out, because I perform an export from POEditor and then it's saved into sysPass locales folder, so I don't know which strings are being compiled.

**Comment by davidpsc** [comment]
Hi,

any news on this issue?

Regards, David

**Comment by nuxsmin** [comment]
Hi David,

Sorry, I missed this issue (I've been a bit busy during last weeks)...

Looking at .po file the some strings are translated into English, but it could be that the compiled file does not include them because they are marked as fuzzy:

![captura_123](https://user-images.githubusercontent.com/1775774/31533394-47e0d04e-aff2-11e7-821a-2f6f1566d520.png)

Could you check out the fuzzy translations and translate them if they aren't.

Regards.
