### ISSUE TITLE
RC 1.1 Force password change broken

### ISSUE THREAD

**Issue by twantrd** [nuxsmin/sysPass#76]
Hi there, 

This is actually a very good piece of software. Thanks for that! I'm trying the latest RC 1.1 and having a problem with forcing a password change for a user. When the user tries to log in, they get "Option Unavailable" as shown below:

![image](https://cloud.githubusercontent.com/assets/10468339/5686275/68e9327a-97f6-11e4-8e96-d23bcd371e60.png)

I'm not seeing any errors in apache's error log. I'm running CentOS 6.5 64bit, Apache 2.2.15, MySQL 5.1, and PHP 5.4. I'm accessing the site using Chrome on Win7. Is this a known bug?

**Comment by nuxsmin** [comment]
Hi!!, thank you for your support ;)

About the issue, do you have email notifications enabled?. They are needed in order to send the change password link to the user.

Actually, the user password reset is implemented to give users the ability to reset their passwords, and the forced password reset is based on that template, so email notifications are needed.

I'll fix it in order to leave only forced password reset to run without email notifications.

Kind regards

**Comment by twantrd** [comment]
Ah, I'll try that out then. I was under the impression that the user would log in with the password that I set for him and then they'll be prompted to enter a new one. Thanks for the quick response!

**Comment by nuxsmin** [comment]
Fixed on latest commit ;)
