### ISSUE TITLE
Allow superadmin to change owner of deleted user

### ISSUE THREAD

**Issue by bodkov** [nuxsmin/sysPass#760]
I have a feature request for the current version of SysPass:

Whenever a user e.g. leaves the company and gets deleted from the LDAP the creator of the password remains the same. As superadmin you cannot change the owner of the password of the user that has left the company.

This is an issue, because the responsibility for the password changes and we cannot change the owner without tinkering with the database itself, which we probably shouldn't do.

Can you add a feature to enable superadmins to change the owner of a password? Or to give the owner of the password the permission to transfer the ownership to someone else?

**Comment by vmario89** [comment]
I think this belongs to the question/remarks of @deajan in issue https://github.com/nuxsmin/sysPass/issues/1148. In my eyes a sysPass user always should work in a way that the accounts he creates are created in a controlled way. If a single user creates an important account storing an ultra-important password something went wrong (from the company perspective). Because thats a matter of sharing accounts to privileged groups, or assigning it to the correct admin user from the beginning.

If a user leaves you may break his privacy.

I think the only well-suited case for this request is: if a user shares an account to one or more groups and he leaves the company in this case an admin should be able to change to ownership to somebody else of the group which the account was shared to. Or: only allow it for accounts which were not explicitely set to isPrivate=true

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3 (accounts bulk edit).

@vmario89 He's discussing about taking the ownership of the accounts when an user leaves the company, but might be related to an user who set the wrong permissions (or not set at all) when creating the account, so nobody can get access to it unless an application admin changes the ownership.

Thanks for the feedback!
