### ISSUE TITLE
Generate Random Password Not Working

### ISSUE THREAD

**Issue by muthu0792** [nuxsmin/sysPass#77]
When i create a New Account, i cannot use "Generate Random Password" option. Clicking on Generate Random Password Icon gives zero response and no password is filled in the password field. No log report seen for this.

Is this a bug or i missed any configuration. mcrypt is enabled for apache. Any other configuration needed other than that said in http://wiki.syspass.org/doku.php/en:install 

Syspass v1.0.9 Ubuntu server 14.04.1

Thanks.

**Comment by nuxsmin** [comment]
Hi, I could be a browswr behavior, because that version is a bit old and some JavaScript functionalities can be broken. Can you test it with other browser?

You can install the upcoming version 1.1 that is on RC status and can be used on production systems (actually I use it every day). This version has a lot of improvements and fixes many bugs.

Kind regards

**Comment by nuxsmin** [comment]
Hi there, does it work?

**Comment by muthu0792** [comment]
Hi thanks, yes it works with firefox... Sorry for delayed response....
I also tries your newer version 1.1 and it too works great.
I have a query can i ask here or as a new issue ?
The question is, can we add default group and profile to LDAP login users so that administrators will have less job to do....??

**Comment by nuxsmin** [comment]
Great, nice to hear that it worked fine!!

Answering the question, yes, default LDAP group and profile can be set in LDAP config options since a few commits back.
