### ISSUE TITLE
Change device password, URL Error

### ISSUE THREAD

**Issue by IlCarlett81** [nuxsmin/sysPass#772]
Hi, 
I report this:
- device alreadi existing
- URL already existing
1) Modify password > OK
2) update url > error (contact admin)

**Comment by nuxsmin** [comment]
Hi, I've just tested the steps you pointed:

- Generate link > View link > Update Password > View link (first password is already shown -that's right-)
- Refresh link (latest password is shown -that's right-)

If 'contact to the administrator' message is shown on public link page, it could be so because either the link is expired or max attempts has been reached.

Regards.
