### ISSUE TITLE
suggestions: clipboard buttons

### ISSUE THREAD

**Issue by pcmediapear** [nuxsmin/sysPass#79]
- "copy password to clipboard" button is great but it would be perfect to have this button available direct without clicking to "more options"
- and what about button "copy user to clipboard"?

**Comment by nuxsmin** [comment]
Hi, thank you for the feedback!

These features are suited to be coded, but I prefer to give them as an option, because putting more icons in the actions bar can break visual aspect on low resolution displays.

The 1.1 version is closed and now it is coming to be stable after rc, so I can develop that code in the next release 1.2, where I have planned to give more customizable options like that.

Kind regards

**Comment by pcmediapear** [comment]
ok, and do you think it is possible to create new switch in settings which allow to see all icons by default?

**Comment by nuxsmin** [comment]
Sure, let me some time and it will be added soon.

Kind regards

**Comment by danislav** [comment]
Please, can we also log the copy to clipboard action?
I think every password action should be logged: view, copy, edit, add.

**Comment by nuxsmin** [comment]
Hi @danislav, I need to review that code because there is many restrictions about how flash works and password data is retrieved. Every time you move the mouse over a copy icon it triggers an event which requests for the account password, so if it's being logged, you can see many "view password" events in the log. I'll give a think about how to improve it.

About the ability to log more event actions, it can be possible, but I need to code a kind of action logging panel to those people who don't want to log everything.

**Comment by danislav** [comment]
After the password copy there is a message: "Password copied to clipboard"
I would add an action/ajax query/ which will log to history the password copy somewhere in the function which shows the message.
