### ISSUE TITLE
RFE: Ability to unlock user login after too many attempts

### ISSUE THREAD

**Issue by MagicFab** [nuxsmin/sysPass#790]
It would be useful to be able to unlock a user account manually, after they have exceeded their login attempts (5 attempts if I remember correctly).

**Comment by nuxsmin** [comment]
Hello!

Yes, that feature could be implemented in next version.

Thanks for the feedback!

**Comment by MagicFab** [comment]
What is the delay? I am locked out again and needing this feature. :)

**Comment by nuxsmin** [comment]
Hello! I'm currently working hard on next version (https://github.com/nuxsmin/sysPass/commits/devel-3.0), it's a tough work, since I'm building automated tests for every unit of work, so it will improve code confidence and version releasing times.

The only way to get it is by deleting the records from the tracking table.

Be aware that the tracking system does rely on client IP address to track login attempts, so you would need to know it for unlocking.

The ETA for 3.0 release is by mid-July.

Regards

**Comment by MagicFab** [comment]
Sorry I wasn't clear, I wasn't asking for ETA for this feature, just what is the lockout delay.

Thanks for your hard work!

**Comment by nuxsmin** [comment]
Ohh, sorry I misunderstood you. The lockout delay is set in 5 attempts in 10 minutes, so it will check how many attempts did you do in last 10 minutes on every login.

**Comment by nuxsmin** [comment]
Hello, this feature has been implemented in v3.

Regards.

**Comment by evangelina-compucorp** [comment]
Hello @nuxsmin, we are using v3.1 and I cant find the option to unblock the users, can you point out where is it? I cant find it on the documentation either.
Thanks!
