### ISSUE TITLE
Import XML syspass v1.2 to 2.1

### ISSUE THREAD

**Issue by CleemL** [nuxsmin/sysPass#794]
Hi,

I've a syspass 1.2 in production.
It works actually on CentOs with docker. But we wanted it on a Debian, with docker.

So, I installed the latest version on a Debian (2.1)

For import all accounts, I tried to export XML and import it.
When I don't paste the old master password, all pass are **encrypted** (normal!)
When i paste the old master password during the import, all passwords are **empty**!
I'm not comfortable with docker, so can't migrate all the db or the container, (and maybe some version problems?)

Anyone know what can I do for migrate all my accounts? (like 500 accounts...)

Thanks,

**Comment by nuxsmin** [comment]
Hi, 

The sysPass upgrade process could be done in-place, that is you don't need to export/import all the data, because it will upgrade all your data. Please take a look to: https://doc.syspass.org/en/updating/v2_1.html

Regards

**Comment by CleemL** [comment]
Thanks for your answer!

That is the thing, it's in production in my company, used by 30 users almost, and I can't down the service..

So, is it an obligation to upgrade before migrate ?

**Comment by nuxsmin** [comment]
In that case, the good way would be creating a new sysPass instance by using a copy of the database.

Some steps to follow;

- Download current sysPass version
- Export your production database
- Import your production database into a newly created
- Copy `config/*` files (listed in the doc pointed).
- Edit database connection data to the newly created/imported.
- Start the upgrade process by pointing to the new sysPass instance URL.

Upgrade process is actually a migrate process, since data structures (database, config, etc) need to be migrated to the new one.

Regards.

**Comment by axldd** [comment]
Trying the same steps at the moment (updating from 1 to 2/3), but unfortunately the link is not working anymore. How can I update from the config.php to the xml version?
