### ISSUE TITLE
New customer groups visible for all users until customer group is linked to password account

### ISSUE THREAD

**Issue by Nickske157** [nuxsmin/sysPass#799]
Hi,

I add multiple users in my syspass.
Admin
User A
User B
User C
Then I added multiple groups, each for every customer.
Group A
Group B
Group C
I linked each user and the admin to the relevant group.
Group A - User A - Admin
Group B - User B - Admin
Group C - User C - Admin
Finally I added multiple customer groups, each for every customer.
Customer A
Customer B
Customer C
But when a customer logs in, he can see every customer group added after I added his account in the customer filter of his dashboard.
Admin sees all customer groups in the filter -> correct
User A sees Customer A, Customer B and Customer C on the dashboard -> not correct, needs only able to filter on Customer A
User B sees Customer B and Customer C on the dashboard -> not correct, needs only able to filter on Customer B
User C sees Customer C on the dashboard -> correct

Is this a bug, or how to solve?

Kind Regards
Nick Geoffroy

**Comment by Nickske157** [comment]
I noticed when I make one password account with a customer group, that the other users don't see this customer group, only the one having the specific account.

**Comment by nuxsmin** [comment]
Hello,

Please be aware that customers are only used for filtering purposes. A customer will be always visible by all the users until it's assigned to an account (next version will implement global customers).

As far I understand, you need to group some users to be able to access to their accounts, isn't it?

Kind regards,

Rubén D.

**Comment by Nickske157** [comment]
Hi Ruben,
Yes, for example.
I want to give some employees access to all customers, but some employees access to specific customers.
Also the customer filter is only visible when there is no account linked to it.
When I added it to an password account, the filter property disappeared on all other accounts who don't have access to the password account.
So for now I have fixed this issue by creating a customer, then assign a test password account to that customer group until I have time to populate the passwords for that customer.
Kind Regards
Nick Geoffroy

**Comment by nuxsmin** [comment]
Hi Nick,

That is the right behaviour, since customers are visible until they're assigned to an account.

It will be improved in next version, by setting global and private customers for groups.

Kind regards.

**Comment by nuxsmin** [comment]
Hi,

So sorry for the late reply, I missed your issue among others  and answered the easy ones first.

It's seems an UI issue, since you noticed that users who are granted to edit can do it by entering in the account details, but you said that after restarting MariaDB, you can't edit anymore. Is it still facing?

Kind regards

**Comment by steevegldev** [comment]
I used sysPass few year ago. To day, I reinstalled and I noticed few behavior change. The one in this question give me some trouble.

Version 2.1.15.17101701

The OP talk about Customer Group. I only found User Group. What is Customer Group?

I don't really understand why the Customer should disappear from the list because someone use it in a Account. It's not really the behavior I wish, can I disable it and use Custom Field instead?

Probably I was using 1.2 version, and I used Customer as External Service. E.g. Customer: Google, Amazon, etc

**Comment by nuxsmin** [comment]
Hello @steevegldev 

As I said before, this behavior is right, since customers should be visible by all the users who have access to the accounts in which the customer is used on. 

Next release implements global clients (more accurate than customers) which will be visible by anyone regardless the accounts permissions. Please take a look to beta version under GitHub releases.

Regards

**Comment by nuxsmin** [comment]
Implemented in 3.0-beta version: https://github.com/nuxsmin/sysPass/releases
