### ISSUE TITLE
How to prevent admin from viewing all passwords

### ISSUE THREAD

**Issue by muthu0792** [nuxsmin/sysPass#80]
Hi, is there any feature to prevent administrator from viewing the password of other users in other groups ? Is that possible to be like that...??

Thanks.

**Comment by muthu0792** [comment]
I think i am insane with what i asked for. I don't like the way every passwords are shown in Admin's search. Probably  there will be way to see any password somehow for admin i think. But i just though it would be nice if users have some personal account passwords.

**Comment by nuxsmin** [comment]
Hi, the idea is good and can be coded with a bit of time, but I need to think about the convenience for the application purpose, that is because this app is  developed for a collaborative multiuser password manager and the final goal is to keep passwords in a safe place where business or personal users can make use of it, but I won't mix that environments because personal passwords shouldn't be stored in a business one.

I know about security concerns but keeping in mind the application context purpose.

What do you think?

Kind regards

**Comment by muthu0792** [comment]
Hey, what you said is fine just i think about a point why an admin should view all the passwords of all the  peoples which may also become a security risk. I am quite lame in saying how to accomplish that.

I think it can be nice to have no password view option for Admin login other than admin's password.

**Comment by sirnone** [comment]
Hello,
as an Admin i can give you one idea why this feature is usefull in an company...
one of our users just infomed us that he will not come back to work (personal reasons). So we hire a new one - so we had 2 days work, just to recover all the Passwords that he used in the years in the company.
with the possibility that the admin can see the passwords this could be solved in some minutes.

**Comment by nuxsmin** [comment]
Hi, 

Thank you @muthu0792 and @Simone for the points of view.

I'm a sys admin too and the reason for which I decided to develop this application is just for keep safe and accessible the passwords in a business environment and avoid to let sensible data in users hands, but I now that admin is one user too, but we should think about the security target level and minimize risks.

We can protect passwords from admins, but always there will be a "super" admin that must know the master password in a business environment, because app and data belongs to the company and not users.

Hide passwords to admins is controversial, because they can get them by other methods, so it would be a false security feeling.

**Comment by Tekcraft** [comment]
Hi you all,
I think this feature is fundamental if you want to use syspass in a firm.  One of the most important security compliance rules is the administrator cannot see the passwords but only change them.  
It's a decision of the final user if a password can be visible or not, sharing it

I would like to know if you want to implement it or not.

Thank you in advance

**Comment by Tekcraft** [comment]
One word more: I think it's not a false security feeling because an administrator should intentionally try to decrypt passwords, instead now no attempt is needed, you see them all

**Comment by nuxsmin** [comment]
Hi there,

some thoughts about that question...

If you are the "super" admin, you know the master pass, don't you?, although anyone must know it...

You may think that the master password should be stored anywhere, but that approach isn't secure, because the password need to be accessed from the webserver, so this scenario gives you a false security concern.

By restricting the admin to not see the passwords only can lead him to try to decrypt them by other ways like: direct db access, backup, export, joining groups....

I'd protect the db access, because all the accounts actions are being logged.

This is an open discussion, so I don't have any problem to put a switch button that restricts to the admin from viewing passwords (fast and easy)

**Comment by Tekcraft** [comment]
I think restricting the admin is the first step for a more secure environment: trying to decrypt becomes an act of hacking (and maybe traceable on the server), instead easily seeing the passwords in clear is a too striking security gap

**Comment by danielneubert** [comment]
Hi there. I currently setting up sysPass for our company and the management wants to save some data locked for everyone else, also the admin. I think this is a reasonable request.

My idea to prevent the master password decryption ist to encrypt the management-passwords with a group specific password before they get normally encrypted with the master password.
So every time, the password should be displayed, a small prompt to enter the group specific password could appear, requesting the access. 🤔

**Comment by nuxsmin** [comment]
Hi @danielneubert,

That is a nice point of view, but if so, some users would encrypt some passwords with a key that no one knows.

I'm considering some alternatives to keep the master password more safe.

BTW, in the next version there will be private accounts so no one except the owner itself would get access to it from sysPass.

**Comment by nuxsmin** [comment]
### UPDATE
Private accounts are now available in sysPass v2

Other types of restrictions would be discussed in a new FR issue
