### ISSUE TITLE
[Feature Request] Improve UI around viewing new user password

### ISSUE THREAD

**Issue by RussellAult** [nuxsmin/sysPass#826]
I nearly filed this as a bug report instead of as a feature request, because it took me about five minutes to figure out that the little "eye" icon under the new user password textbox displays the password as a tool tip. I was trying to click on it, which of course doesn't work (and clicking outside of the textbox obfuscates the password in question, so it *really* doesn't work).

While I understand the security value of taking this approach, it would be nice if there was some indication of this functionality in the UI. As it is, the "eye" icon is a functional button in every other context in the app, so making it not a button in this one context is confusing. (It's especially non-obvious when using a random password, since it makes the "eye" button look extra broken: it doesn't do anything, and it has a gibberish tooltip!) :-)

**Comment by vmario89** [comment]
you talking about this menu i guess. in regular circumstances the admin should need to know the password from the user.

![grafik](https://user-images.githubusercontent.com/5631071/34894055-2a53115a-f7e0-11e7-9854-5d37e52eab4f.png)

**Comment by nuxsmin** [comment]
@RussellAult you're right it should be a functional button and it doesn't, so I'll think about what icon would be suitable on this context.

**Comment by nuxsmin** [comment]
@vmario89 every html form password is encrypted using PKI, so it will be encrypted on the client side and then decrypted on the server one, but the admin will be able to get it.

**Comment by RussellAult** [comment]
@vmario89 That's the one. The same thing shows up for every user when they try to change their own password.

**Comment by RussellAult** [comment]
@nuxsmin I have a few suggestions for icons that just came to mind:
- A binoculars icon
- An unlocked padlock icon
- A locked padlock icon with a slash through it
- The key icon from the login page with a slash through it

I'd also suggest the icon appear "greyed out" as compared to surrounding icons to discourage people from clicking on it.

Thanks!

**Comment by vmario89** [comment]
sorry i meant
you talking about this menu i guess. in regular circumstances the admin should **not** need to know the password from the user.

> you talking about this menu i guess. in regular circumstances the admin should need to know the password from the user.

**Comment by nuxsmin** [comment]
@vmario89 right, I misunderstood your point, since I thought that you were talking about the accounts password field...

**Comment by nuxsmin** [comment]
@RussellAult nice suggestions, it could be implemented in a minor release.

I think that triggering that behavior on field's blur event could be a hassle, but there was no way to encrypt those kind of fields before submitting the form. I'll analyze if current JS API let us to do it in another way.

Thanks for the feedback!

**Comment by vmario89** [comment]
i am with you @RussellAult. This function should be improved. Generating a new password by the button "Generate random password" is painful because the only possible way to note down the password is hovering on they eye and write the password to paper. There's no way to copy the password to clipboard and no possiblity to get back the password after unfocusing the field because it gets encrypted directly :(

**Comment by nuxsmin** [comment]
@vmario89 right, be aware that it was thought to be secure, since the password is generated and then encrypted, so you will only have to copy to clipboard or reveal it. Don't write down passwords! ;)

**Comment by vmario89** [comment]
hello @nuxsmin,
the problem here is: you cannot copy the password to clipboard when **creating new user passwords**. There is no button to do this? 

For account passwords there is a button 
![grafik](https://user-images.githubusercontent.com/5631071/35152810-3219b148-fd24-11e7-8e78-90a3da527add.png)
![grafik](https://user-images.githubusercontent.com/5631071/35152818-3d31a568-fd24-11e7-9d8a-a8d9acd3807f.png)
![grafik](https://user-images.githubusercontent.com/5631071/35152850-6512a564-fd24-11e7-946f-3b37f7251f72.png)

as you can see creating new user and save his pw is using pen and paper or do a screenshot of the tooltip hovering


____________________
the user view:
![grafik](https://user-images.githubusercontent.com/5631071/35152835-51660056-fd24-11e7-90d5-0a3a19ca3dfa.png)
![grafik](https://user-images.githubusercontent.com/5631071/35152840-56d306d8-fd24-11e7-8ead-752fc4104f6f.png)

there is missing the copy to clipboard

**Comment by nuxsmin** [comment]
@vmario89 I'm totally agree. I will think about how to improve this behavior.

Thanks!

**Comment by nuxsmin** [comment]
Some thoughts on this behavior:

- Form element must be avoided, since this will send a plaintext password through the network (if no using SSL or behind a reverse proxy).
- Creation of DOM elements (div, span, etc) should be avoided: it will add extra useless elements.
- Store in javascript object (memory): plaintext or encrypted?

**Comment by nuxsmin** [comment]
Done in latest 3.0-beta version: See on: https://github.com/nuxsmin/sysPass/releases

**Comment by vmario89** [comment]
hey,
works like charm now :)
