### ISSUE TITLE
[Improvement] Prevent user at first login from typing data twice

### ISSUE THREAD

**Issue by vmario89** [nuxsmin/sysPass#830]
Hey,

as i recognized its a little bit tedious to create new users in syspass and let them login in. At the first login they require the master password. The problem is that the user goes to the syspass login page and types in his user and password. After pressing the login button an error occurres which tells him to to type in the master password. The form gets resetted and the user has to type in user and password again + additional field for the master password now. So he types in his login twice. It's just a small thing but it really doesnt look pretty good for a new user who does not know the software until now.

maybe you could implement a way that typed data will stay or another way of let pop in the masterpassword field which does not require to reload the page. maybe with some ajax

regards, Mario

**Comment by nuxsmin** [comment]
Hey there!

The fields are intentionally reset because a security reason. In the first step the app checks whether the user has set the master password and if it's correct, then it returns a 'wrong master password' response back to the browser, so it shows up the additional fields.

The same behavior is triggered when the given master password is wrong, so I thought to reduce the use cases within the code by always resetting these fields.... thus not controlling whether the master password is not set or the provided one is wrong.

Regards.
