### ISSUE TITLE
LDAP and multiple email addresses (again)

### ISSUE THREAD

**Issue by dvdfabian** [nuxsmin/sysPass#855]
Hello,

we've also experienced the same error as in #278. We have a Fedora DS directory and almost all of our user accounts have multiple mail attributes. Syspass tries to store the resulting PHP array() form the LDAP search query into the database and produces a PHP warning - array conversion to string. All emails for such LDAP accounts are stored as "array()" in the DB. This brings problems to user management because the UI refuses a pre-filled value "array()" as an invalid email address. One has to manually change the email every time one needs to change e.g. a group membership. My solution to the problem was to add the following code to DB.class.php on line 212. It's not the nicest fix but it works.

```
if (is_array($value))
   $value = $value[0];
```

Best regards,
David Fabian

**Comment by nuxsmin** [comment]
Hello @dvdfabian ,

It seems that there is some missing behavior in https://github.com/nuxsmin/sysPass/blob/54d7ed1950207910cebd3644fc23b3265a267960/inc/SP/Auth/Ldap/LdapBase.class.php#L517 since LDAP attributes which have more than one value should be managed in this piece of code.

Let me review what could be happening.

Thanks for the feedback!

Regards

**Comment by nuxsmin** [comment]
Hello, this issue was fixed in v2. Thanks for the feedback!

Regards
