### ISSUE TITLE
AD user groups linking with syspass groups

### ISSUE THREAD

**Issue by arturaslayerv** [nuxsmin/sysPass#867]
We are looking into syspass and at the moment this project seems to be missing couple of key features. 
To blur the lines - will it be possible to link AD groups with syspass groups? For example if user in AD have a group "L1" can it be linked with the same group in Syspass?

**Comment by nuxsmin** [comment]
Hello, 

This is a planned feature for next release.

Thanks for the feedback!

**Comment by arturaslayerv** [comment]
Thanks for quick response. That's great!

**Comment by nuxsmin** [comment]
Hello, this feature has been partially implemented in latest 3.0-beta. It means that you could import LDAP users OR groups, and the link (manually) every user with any imported group. That is so because complexity, since every LDAP user could be listed in many groups and sysPass won't know how many of these groups should be imported. Although there were a group selector on the import process, it would be a tough task to pair every imported user with a group.

I've been analyzing some apps with LDAP integration and none of thme give the ability to link the imported users with their groups, they always look for a group membership for authorization.

Please take a look to next release: https://github.com/nuxsmin/sysPass/releases

Thanks for the feedback!

Kind regards.
