### ISSUE TITLE
No valid  login password if it has special characters

### ISSUE THREAD

**Issue by yosugk** [nuxsmin/sysPass#879]
If I setup a login password to Syspass with special characters like ñ, next time I logon, Syspass always tells me wrong password.

**Comment by D3luxee** [comment]
I've setup the latest version 2.1.16 and i can confirm issues with one or more of those characters:
`_+@|^:/`

I've created new users with a password and enforced the password change, one used a password which included the characters above and could not login afterwards.

**Comment by nuxsmin** [comment]
Hello, it's really weird, since password fields are sent encrypted, and then hashed using bcrypt for storing in the database, so no character stripping is done at all.

I'll need to do some tests about it in v2 .

Thanks for the feedback!

**Comment by D3luxee** [comment]
Hi, to be exactly the password which caused the conflict was `_8W+@Tw=5anFD'U8@Q56a7$0pDjl=03p\s3p[^|N7]#lCRz'x:ly30I/`

I've done some more research, its not about the special characters its about the length.

The create user and change password mask, does truncate the password to 51 characters. You can see this behavior with the show password function in the dialog.

The frontend passes the truncated password (51 chars) to the password_hash function and uses it as password for the user.
The login mask does use the entire 57 characters of the password above.

FYI, the password_hash function itself will truncate passwords to 72 bytes due to the bcrypt limitations.
http://php.net/manual/en/function.password-hash.php

I hope this will help you.

**Comment by nuxsmin** [comment]
Solved as pointed in #1038
