### ISSUE TITLE
Customer with single private account becomes invisible to other users

### ISSUE THREAD

**Issue by tsbatista** [nuxsmin/sysPass#880]
This happened to us with a 2.1 syspass version:

steps by user A (can create customers):
1. create a new private account (as in, only self can see it)
1.a create a new customer while creating the account (lets say costumer C)

steps by user B a few hours later (cannot create costumers):
1. Create a new account
2. realises he cant create a custumer at all and requests the system admin to create a custumer called C

Steps by system admin:
1. try to create costumer C
 - Receive a message claiming the custumer already exists.
2. checks costumer list - costumer indeed exists
3. tries to create account associated with that costumer - costumer is nowhere to be found in the dropdown

In this case, in order to allow other users to create accounts associated to costumer C, we had to ask user A to create a dummy account on that costumer with a wider set of permissions.

While I may accept (not agree with) the design decision to hide costumers that only have a private account from the other users, I would kindly ask you to allow the administrators to at least unlock this situation without the need to ask user A to act.

**Comment by nuxsmin** [comment]
Hello, that behavior is right, since customers are only visible by those users who have been granted to the accounts in which the customer has been set. It isn't a private account behavior, it is a security one instead.

Next release will implement global customers/clients so everyone would be able to use it regardless the accounts permissions.

Thanks for the feedback! (and sorry for the inconvenience)

Regards.

**Comment by tsbatista** [comment]
No problem, I just created this because me as an admin could not solve this issue without asking for help from a regular user. Good to know this is in your  roadmap. Keep up the good work
