### ISSUE TITLE
Backup syspass

### ISSUE THREAD

**Issue by vivalasvegan** [nuxsmin/sysPass#889]
Hi everyone !

Can you tell me how can we make a backup of syspass for each user account? 
and how to make a backup  for the server ?

Thank you

**Comment by nuxsmin** [comment]
Hi, you can do it either through sysPass (Backup/Export tab in config section) or by using external utilities like mysqldump and tar/zip.

Regards

**Comment by vivalasvegan** [comment]
Hi,
Thank you for your help !  
I did an account export (.xml) from a syspass to another syspass. I note that i don't have the permissions to see or copy the passwords on the second syspass. Is this normal ? At this point, i just can modify the account informations. 

Ragards

**Comment by nuxsmin** [comment]
Hi, that's right, permissions won't be imported using an XML file, since they aren't exported indeed. You need to assign the new permissions again.

Be aware that an XML exporting is a way to carry out your sysPass data to another instance, but recreating the whole structure would be very dangerous.

Regards
