### ISSUE TITLE
query MySQL take 165 seconds for syspass

### ISSUE THREAD

**Issue by tmedtcom** [nuxsmin/sysPass#905]
Hello,

For password change operations, changing the syspass configuration settings takes a long time.

I search in sql requests in my cpanel I find that a simple activation of a simple config in laste passes it remains 165 seconds until the request ends.

See this print screen: [](https://prnt.sc/ixg415)
https://prnt.sc/ixg415
Best regards,

**Comment by nuxsmin** [comment]
Hello, these are the first news about SQL performance issues. There are some actions that will take a long time like changing master password, and that is so because the encryption/decryption task.

Please let me know which tasks had you been performing during the issue.

Kind regards.

**Comment by tmedtcom** [comment]
Hello,
Thank You for your reply.

I have just try to add a new account.
And I have try to change password for a user.

The query always takes 165 seconds.
I migrated the installation to another server, and even problem got stuck.
Best regrad,

**Comment by nuxsmin** [comment]
Do you have email notifications enabled?.

The account creation process shouldn't take more than 1 second long. You could take a look to the demo sites (stable and beta).

Regards

**Comment by tmedtcom** [comment]
Yes I noticed that in the demo, it's very fast.
Yes I have Notifications enabled by mail, I have now disabled all option in "Email notification"
And SysPass iw now very very fast.
Thank you very much ! 👍 
What was the problem ? why it does not accept the configuration of the notifications by mail?
Regards

**Comment by nuxsmin** [comment]
Be aware that PHP sends emails in a synchronous way, so if the mail server take too long processing the request, the web page will stuck after creating the account or every operation that sends an email (configuration, change password, etc).

In order to process emails in an asynchronous way, it would need to use a message queue service, but this kind of architecture is a bit complex to implement and maintain.

Regards
