### ISSUE TITLE
Header Alignment

### ISSUE THREAD

**Issue by nblount** [nuxsmin/sysPass#907]
We are having issues that the headers do not align with the col. 

![image](https://user-images.githubusercontent.com/29442164/38509963-62c0a9a6-3c1b-11e8-85b0-c562b478d088.png)

Problem seems to exist across browsers as it happens in Chrome, IE, Edge, Opera and Firefox for us.

Any quick fix or which file I need to have a look at?

**Comment by nuxsmin** [comment]
Hello, this behavior is normal since filtering headers couldn't match with displayed fields for restricted users and in future releases there would be more filtering fields. There have been some discussion about it before.

I've done some tweaks in next 3.0-beta release, but as said before, more headers could be added and the alignment will be broken so.

Thanks for the feedback!

Regards.

**Comment by nuxsmin** [comment]
Please, see #605
