### ISSUE TITLE
Password / profile segmentation / ldap vs AD

### ISSUE THREAD

**Issue by Canada514** [nuxsmin/sysPass#911]
Hello

 For a while, we have been facing two issues that we can not solve.
The first and not least is related to the change of password:

- Indeed we have a colleague whose password has expired, he made the change, but this change also does not work on syspass even if it is related to Ldap. I have opted to opt for "force password change" and despite that when it puts this information it does not work at all. He then tried to request a reset via the syspass platform but here is the error he receives: IMG-1
![img-1](https://user-images.githubusercontent.com/29872454/38701426-56fa3474-3e8d-11e8-94fb-d3001d7b4f9e.JPG)
 
What should I do in this case since I am the administrator taking into account the message?
Note that 3 other colleagues changed their password the same week and their new password worked without problems on the syspass.

The other question concerns the segmentation of profiles. Indeed despite the fact that we have 3 levels of employees: level 1, level 2 and level 3, when we register the data each level sees the data of the other while in our model we want level 3 is access all codes, but level 2 can not see level 3 codes and level 1 can not see level 2 and 3 codes.
Here is a sample profile : IMG-2
![img-2](https://user-images.githubusercontent.com/29872454/38701427-5754b494-3e8d-11e8-84ea-96a089e53284.JPG)

Which option or configuration should I apply for this segmentation to be real?

3- What is the difference between enabled LDAP option versus Active Directory option? I'm asking because we've enabled the LDAP option, but I'm wondering if I turn on the active directory option the interaction with the platform would be different or if it would fix my password problem linking to a colleague ? IMG-3

![img-3](https://user-images.githubusercontent.com/29872454/38701428-578805e2-3e8d-11e8-837e-c8d6076d8ffe.JPG)

**Comment by nuxsmin** [comment]
Hello,

Regarding the user password change issue, is there any logged message into sysPass event log?. The reset password feature will only work for non LDAP users, since it should be reset on LDAP instead. That confusing message does not give too much information because a security behaviour, but sysPass shouldn't have let to turn this option on.

About profiles implementation, it would be partially achieved by using groups, but it will be tough to assign a bunch of users to each group. Next version will implement nested groups for a better security management.

The LDAP ads option will set a different behaviour when searching for users and groups, since some schema objectclass are only available in ads and nested group membership too.

Kind regards

**Comment by Canada514** [comment]
1- At the level of the ldap, he mentions not found the person in the directory but yet he is present. The change of password is always done directly either in our ldap or via a central password change platform. The problem seems really random because there are accounts that have changed their password in the ldap and it works but this account does not work. 

the error message is : Error while searching for the user in the LDAP directory

2- Ok as I understand it so that the person can request a password change via syspass, it would be necessary that his account is created locally in syspass even and not that it comes from ldap?

3- I am at syspass version 2.1 and will upgrade to sysPass version 2.1.15 this week, will the problem of the account segmentation be included in it or you refer to the next update beyond sysPass 2.1. 15?

So does this mean that to date if I import someone into the syspass, can not I just restrict them to just seeing the information of their group or profile?

4- ok i will test in another virtual machine the synchronization by Active directory and i will keep you informed if it works as much as the ldap

**Comment by nuxsmin** [comment]
Hello, I'm sorry for the late reply...

Regarding your points:

> 1- At the level of the ldap, he mentions not found the person in the directory but yet he is present. The change of password is always done directly either in our ldap or via a central password change platform. The problem seems really random because there are accounts that have changed their password in the ldap and it works but this account does not work.

Some LDAP errors are caused by duplicated entries. Please lookup the user and group in LDAP and checkout they are unique. BTW, I've implemented some LDAP improvements in latest release.

> 2- Ok as I understand it so that the person can request a password change via syspass, it would be necessary that his account is created locally in syspass even and not that it comes from ldap?

An LDAP user account is always created in sysPass on the very first login. That is so because sysPass need to store some user's data like permissions, preferences and other stuff (LDAP fallback, etc).

> 3- I am at syspass version 2.1 and will upgrade to sysPass version 2.1.15 this week, will the problem of the account segmentation be included in it or you refer to the next update beyond sysPass 2.1. 15?

Yes, it would be implemented in sysPass 3.0

> 4- ok i will test in another virtual machine the synchronization by Active directory and i will keep you informed if it works as much as the ldap

Fine, please let me know the progress.

Kind regards
