### ISSUE TITLE
Master Password 1st connection

### ISSUE THREAD

**Issue by lduriez** [nuxsmin/sysPass#913]
Hello

Is there a way to don't ask for master password to the users who connect by ldap the 1st time ?

**Comment by nuxsmin** [comment]
Hello,

I think this couldn't be achieved since the master password is encrypted by using a derivated key from the user's data (login and password) and a seed, so you need to know the user's own data.

This is the currently implemented schema, but I would need to think if there would be a better approach. You need to be aware that the master password need to be retrieved on every login since the accounts passwords, among other items, are encrypted using it, so the users will need to be able to get it in a secure way. This implementation allows to store the master password securely and doesn't bother the user by asking for it on every login (besides it would be a security leak).

Let me know if you have any thoughts about it.

Kind regards.
