### ISSUE TITLE
sysPass-3.00.18040302-beta fails to install or launch

### ISSUE THREAD

**Issue by YesThat** [nuxsmin/sysPass#915]
I'm uncertain what happened in your release process, but the vendor directory is missing from the release.  I'm seeing an error in my ssl_error_log 

PHP Warning:  require(/var/www/html/syspass/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/syspass/lib/Base.php on line 63

That file was not pulled in as part of the release tarball and is missing in the master branch.

**Comment by nuxsmin** [comment]
Hello,

I'm glad to know you're testing sysPass 3.0 version!

The vendor directory shouldn't be bundled within sysPass, since it would be set up on the target system. Please think about a big sysPass bundle including dependencies that could be outdated till next release comes out. This and other reasons makes more necessary an on-target based set up.

I'll post some info about installing this version.

Thanks for the feedback!

Kind regards.

**Comment by YesThat** [comment]
Haha, really only testing because I was unable to get 2.1 to properly setup ;). 

As for notes on setting up this release, please do share.  I'll look forward to it.

**Comment by nuxsmin** [comment]
Please, let me know which issues are you facing installing sysPass.

As for setting up 3.0 you only need to download composer and install dependencies. You may take a look to https://github.com/nuxsmin/docker-syspass/blob/master/sysPass-dev-php7/entrypoint.sh

Packages needed are the same as for 2.1 (more info on https://doc.syspass.org)

**Comment by nuxsmin** [comment]
@ricardostm hello, please take a look to web server log for any error messages.

**Comment by ricardostm** [comment]
![image](https://user-images.githubusercontent.com/46932311/51645194-de115280-1f51-11e9-85a4-714c8d4b6c02.png)
Good night,

I applied all the permissions, but it persists in not rolling.

**Comment by ricardostm** [comment]
Good Morning

After a lot of work I was able to perform the installation!

Thank you!
