### ISSUE TITLE
Major issue with installer when no root privilages

### ISSUE THREAD

**Issue by tsmgeek** [nuxsmin/sysPass#931]
It would be best that no rollback is done as it ends up dropping a database and removing user. It is far safer to just give an error than be destructive.
We found this as 'isHostingMode' in the GUI was not clear what it meant nor the outcome if there was a PDO error.

**Comment by nuxsmin** [comment]
I know that though hosting mode isn't quite clear, you could take a look to http://doc.syspass.org/en/installing/hostingmode.html where there's a better explanation.

Regarding the rollback behavior, it's done so because most of the installation issues are caused by wrong permissions, so the installer fails while creating the structure.

Regards
