### ISSUE TITLE
Change Front Page/Header Banner?

### ISSUE THREAD

**Issue by DCWNZ** [nuxsmin/sysPass#934]
Is it/can it be possible to change the front page & header banner to a corporate logo? Or an option to Add a corporate logo?

Forgive me if its already possible, I cant see any easy way of doing so.

Thanks!

**Comment by nuxsmin** [comment]
Hello, sorry for the late reply, I've been a bit busy on these weeks.

Actually there is no "easy" way to change either the banner or logo, but could clone the current theme (within `inc/themes' directory) and then modify whatever you need.

Why it does not provide a way to change it from the UI?. Because it will take a considerable amount of time to implement a decent UI for upload/resize the logo image and edit the banner/footer.

Regards

**Comment by DCWNZ** [comment]
Fair enough. I tried to modify what images I could find but had no luck. If there was an easy way that would be great, but not a major I guess.
