### ISSUE TITLE
2FA code expiry without notification

### ISSUE THREAD

**Issue by ortizleo** [nuxsmin/sysPass#935]
Hello.
We are using sysPass for 1 year now and our 2FA codes are expiring, the problem is that no one notification is displayed and after 2FA code expiry the user can login normal without the codes....

Can you add some message or block user when 2FA code expery?

**Comment by nuxsmin** [comment]
Hello, this is a normal behavior, since restricting further accesses from the expired date would be a major hassle, because there is no way to reset the 2FA auth (it would need to add a recovery way by using SMS or such like).

The Authenticator plugin creates a notification through the in-app notification feature when the 2FA is about to expire: https://github.com/nuxsmin/sysPass-Plugins/blob/231ad2c4e3fc16c7fa8af1a723d95288e95b6611/Authenticator/LoginController.class.php#L120

Thanks for the feedback!

Regards

**Comment by ortizleo** [comment]
Hello, @nuxsmin 
How I can find the expiration remain time for the 2FA in Database?
I want to send e-mail when the 2FA is far to expiry.

**Comment by nuxsmin** [comment]
Hello @ortizleo , plugins data are stored using serialized PHP objects, so there is no easy way to get them.

sysPass v3 implements event based notifications, so it can be implemented on the plugin side.

Regards

**Comment by ortizleo** [comment]
Fine.
About 2FA, What you think about block users when 2FA code is expired, but administrators (or a specific account) can unblock this users? sysPass will send emails and alerts before block the users of course.
