### ISSUE TITLE
User login Issues

### ISSUE THREAD

**Issue by DCWNZ** [nuxsmin/sysPass#950]
Issues with AD Auth & user password change:
User changes AD Password (as forced by policy).
User attempts to use new password on SysPass. SysPass doesnt recognise it, field pops up for old password. 
Nothing works in these fields, keeps alerting for "Wrong Login" (Event log confirms).
Eventually get user authenticated by setting the "Password Change" radio button to "On", and issuing a Temp Master Password to the user.

Then, I try to login to my Local Admin (non-AD) account, it tells me wrong login. I try again (Password is Definitely correct), get the same error.
I login to my AD admin account = works fine. I create a NEW local Admin account, not able to login.

Question 1: Whenever a user changes their AD Password, syspass should register the change and allow them to login with it, since it is bound to the directory. I realise they may need a new master pass, but do I need to check the "Password Change" radio button each time?

Question 2: Im assuming my local admin accounts dont work because I am using AD LDAP Auth. Am I able to allow both, so I can keep a local admin account operational at all times?

Apologies if im missing something obvious. Happy to post/send/email config file if required.

**Comment by nuxsmin** [comment]
Hello, 

This a weird behaviour, since sysPass requests a bind process to the LDAP server, so it pass the login data as is. New user password in LDAP means that sysPass will ask for the previous one since it needs it for decrypting the master password. If you don't provide the previous one, it will ask for the master password instead.

Regarding the internal users authentication, you need to take into account, that LDAP is mandatory, this means that if a user login exist in LDAP the LDAP response is processed and no further action will be taken. The only case in which internal users will be used, is when there is an LDAP timeout, that is so because it acts as a fallback authentication, so the user can log in using its saved data.

Regards

**Comment by Fizard** [comment]
Hi @nuxsmin, I don't know if this is the same LDAP problem, but I saw something today on v3 beta. I've successfully configured the LDAP and when I first login with an LDAP account it works ok and at USERS configuration it shows correctly as an LDAP user:
![image](https://user-images.githubusercontent.com/7660657/41253753-bacddabc-6d97-11e8-9a84-c4b32c109c0d.png)
The problem is, if I change this user's group and profile in this form:
![image](https://user-images.githubusercontent.com/7660657/41253477-dc411d18-6d96-11e8-9fd7-4fdafe4ce18a.png)
it seems it lose the LDAP User configuration:
![image](https://user-images.githubusercontent.com/7660657/41253666-7245dd44-6d97-11e8-9a57-8a227d698c2d.png)

As you can see in the last image it lets you change the password in the application, different when it's in LDAP, so it loses the LDAP User. Maybe that's why there is a problem when changing password in LDAP too.

**Comment by Fizard** [comment]
After this commit it I can edit the profile and the user keeps the attribute. @DCWNZ, try to apply those changes and see if it resolves your issues. (sorry for my poor english).

**Comment by nuxsmin** [comment]
Thanks for the notice @Fizard 

I'm not sure it would solve this issue, but as you pointed, it fixes the wrong behaviour when saving an LDAP user. It didn't set the LDAP flag indeed.

Regards

**Comment by DCWNZ** [comment]
Have updated my code and issued a reset on one account - confirmed that after entering old password the new password is updated and confirmed. This is much much better behavior. So now, when my users update their AD passwords, they should only have to enter their old password once in order to confirm their identity.
I will report back if there are any further issues with this, I need to reset my own password shortly so will test then.

**Comment by nuxsmin** [comment]
@DCWNZ sure, this behavior has been implemented since 2.1 version but some weird issue was facing in current version.

Thanks for the feedback!

**Comment by nuxsmin** [comment]
@DCWNZ be aware that the old password request is due to the fact that sysPass needs to decrypt the master password and then encrypt using the new password, so it isn't related to an identity verification ;)
