### ISSUE TITLE
Export Accounts Feature

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#956]
I have a question and a feature request for the Export Account.

The question is: It is said that "The exported items are accounts, customers, categories and tags.", does this includes the Custom Fields? Cause if there aren't custom fields what will happen to the accounts imported with those custom fields?

Now the feature request, could you add an option to filter per client or all clients? This way I could export everything of just one client and give that client the backup, without having the accounts of the other client.

Thanks!

**Comment by nuxsmin** [comment]
Yes, this feature will be implemented by giving an option to set which accounts should be exported and which users can perform it.

You need to be aware that exporting accounts is way to carry out your data to another application and not a backup method, so custom fields won't fit in other apps. Since it is the main purpose of this feature, I didn't implement such option, but would be useful in those cases in which you need to load a partial dataset in another sysPass instance.

Thanks for the feedback!
