### ISSUE TITLE
Tag List problem

### ISSUE THREAD

**Issue by Fizard** [nuxsmin/sysPass#963]
In sysPass 3, when you have more then 12 tags in "Items and Customization" -> "Tags" it just shows the first 12 without pagination. I've seen in TagRepository.php and the select is bringing all the columns, but I didn't find on the code where it is filtering. (not using any IDE, just notepad)

**Comment by nuxsmin** [comment]
Hello, 

It that it doesn't count the total items retrieved, but it's weird, since it shares the same code for displaying items in the grid (eg. Accounts history).

The code involved goes from controllers to helpers, services and repositories. I'll check out what could be wrong there.

Thanks for the feedback!

**Comment by Fizard** [comment]
That's great. Thank you.
