### ISSUE TITLE
Forget master password. How do I reset the password master password?

### ISSUE THREAD

**Issue by kmohan1985** [nuxsmin/sysPass#97]
I did installed the program, and i accidently i forget the master password. Can any one help me out to reset master password through mysql db ?

I can't reset master password from the admin console on web. It says old master password not match.

**Comment by nuxsmin** [comment]
Hi, do you still have access to sysPass as admin??

**Comment by kmohan1985** [comment]
Yes. I have the access.

**Comment by nuxsmin** [comment]
You can patch the ajax/ajax_getContent.php file and enable debug mode in sysPass configuration, so you will be able to see the master password in the debug data shown on the screen.

Here you have the patched file: https://gist.github.com/nuxsmin/5edb05f9f5a340e44f78

**Comment by fwilly** [comment]
It is possible to get the patch or patched file again?

A possibility to check the master password in admin area would be great. The master password must be input and system says it is correct or not.

**Comment by nuxsmin** [comment]
What version are you running on?

**Comment by fwilly** [comment]
1.2-rc5

**Comment by nuxsmin** [comment]
Great, you can get it by enabling debug info.

**Comment by fwilly** [comment]
I have. But the displayed value does contain non printable characters. It certainly was not the master password. Maybe he was still encrypted.

**Comment by nuxsmin** [comment]
Can you see the accounts' passwords?

**Comment by fwilly** [comment]
Where exactly?

In the default account view (not debug output) no longer. I'm sure in version 1.1 I could see it.
Now I have checked my saved accounts. And noooo, I could not see any passwords any more.
=> The master password isn't correct.

After upgrade to version 1.2-rc4 I was once again asked for the master password. My correct master password wasn't accepted. Somehow it has found my session and let me in without login.
=> The new version (1.2) cannot handle master password from older version (1.1)

**Comment by nuxsmin** [comment]
Sure, 1.2-RC4 has a new master password implementation as said at 1.2-RC2 release, where the master password need to be reentered to migrate to the new format, so if you didn't, it is required.

However, don't worry about that, neither your accounts nor your password (the master password is never stored on the server, only the hash) have not been changed.

What happens if you performs a log out?

**Comment by fwilly** [comment]
I can log out. But when I login the master password is not queried again and no account passwords are shown.

**Comment by nuxsmin** [comment]
Can you create a new user and try to login with it?

The master password hash should be regenerated again.

**Comment by fwilly** [comment]
I have, but the master password will be not accepted.

**Comment by nuxsmin** [comment]
Another option is to restore the app and db backups in order to get log into the last version and then upgrade again.

The master password is never stored, so we cannot recover it without decrypting with an user pass.

Can you send me the 6 first characters of the master password hash that is stored in the db config table?

Don't worry about security, it isn't the pass only a hash.

**Comment by fwilly** [comment]
here any more characters:
$2y$07$18d82d82fa79f45069b4f0d001265ddf979942a54e811d

**Comment by fwilly** [comment]
I have no database backup from version 1.1

**Comment by nuxsmin** [comment]
It seems that the master password hash has been upgraded so it won't ask for it until next change.

The only option is to recover it from backup.

**Comment by nuxsmin** [comment]
Let me think in a hack to reenter it again

**Comment by fwilly** [comment]
I have an account backup as xml. Saved with v1.2. There are passwords for accounts. But they are encrypted.

**Comment by nuxsmin** [comment]
Great, then you can perform a fresh 1.2 install (changing the db name) and import the exported xml.

**Comment by nuxsmin** [comment]
Hi, after some test I've found out where is the issue: the master password hash has not been set rightly, because it has been set as if it was blank.

**This does not affect to the accounts, only for the master password checking on login**

It's needed to log into the DB and let empty the value of field "config_value" for the record "masterPwd" in the "config" table:

``UPDATE config SET config_value = '' WHERE config_parameter = 'masterPwd';``

I've uploaded a new update (not release) at https://github.com/nuxsmin/sysPass, so the next login it will request for the master password (check it is the right one) and the hash will be fixed. After that, it would be possible to view the accounts passwords.

**Comment by fwilly** [comment]
Okay, that has worked. Thanks.

**Comment by pydubreucq** [comment]
Hi,
I've lost my Master Password too.
I've tried to change it in the backend, but my change was not applied.
I've tried your request:
```
UPDATE config SET config_value = '' WHERE config_parameter = 'masterPwd';
```
And now, I can't log into syspass :(

I don't have real password so I didn't do a backup

Is it possible to solve that or I have to reinstall syspass ?

Best Regards
Pierre-Yves

**Comment by nuxsmin** [comment]
Sorry @pydubreucq , but master password cannot be recovered because it is not stored anywhere.

The query that you issued only resets the master password hash, so the app will request for the master pass (during login) and you should provide the real one, because it will let you log in but your accounts' password won't be readable.

**Comment by pydubreucq** [comment]
Ok thanks.
I will reinstall syspass
Best Regards

2016-01-13 12:33 GMT+01:00 nuxsmin <notifications@github.com>:
