### ISSUE TITLE
Forgot Master Password

### ISSUE THREAD

**Issue by LordSchnaps** [nuxsmin/sysPass#979]
I accidently lost the master password and can't find it anymore. I tried it with this post https://github.com/nuxsmin/sysPass/issues/97, but the patched file isn't available anymore and also tried this one: https://github.com/nuxsmin/sysPass/issues/621 but I think, it's for newer versions and I'm a bit scared to upgrade it without having the master password.
I'm using syspass 1.2.0.12 (Server Version:  5.5.55-0ubuntu0.14.04.1). Is there any possibility to restore the master password or change it? 

Many thanks in advance

**Comment by nuxsmin** [comment]
Hi, are you able to log into the current sysPass instance using an app admin user?

Regards

**Comment by LordSchnaps** [comment]
Yes, I can log in into sysPass as an admin user. Also I have root access on the OS and also root access on the database.

Regards

**Comment by nuxsmin** [comment]
Fine, I've checked out your version files and it should reveal the master password by turning on the debug mode on sysPass settings (https://github.com/nuxsmin/sysPass/blob/1.2.0.12/inc/themes/material-blue/debug.inc). Sorry about not to explain a more detailed instructions, but this version is quite old and I haven't any working environment running this version.

I really encourage you to upgrade your current version, because there are a lot of issues and security advisories that make it insecure.

Regards

**Comment by nuxsmin** [comment]
> I'm a bit scared to upgrade it without having the master password.

Right, you won't be able to upgrade to 2.1 version without the master password.

P.S: Please make always database and application backup before any procedure
