### ISSUE TITLE
download backup files failed

### ISSUE THREAD

**Issue by Famku** [nuxsmin/sysPass#980]
Hi,

how can I grant permissions to allow download backup files in docker?

**Comment by nuxsmin** [comment]
Hi,

since Docker nature is to run several containers using the same configuration, you should edit the 000-default.conf Apache file (https://github.com/nuxsmin/docker-syspass/blob/master/sysPass/000-default.conf) and modify the directory ACL, and then build a new Docker image, BUT you could also either edit this file from the container itself (`docker exec -it sypass-app bash`) or bind an external file to the container (`docker .... -v /external_dir/000-default.conf:/etc/apache2/sites-avaliable/000-default.conf nuxsmin/syspass`)

**Comment by Famku** [comment]
Thanks for your quick help

**Comment by Famku** [comment]
Sorry, but what I need to change here? 
"Require all denied" to?

**Comment by nuxsmin** [comment]
`Require all granted`

**Comment by Famku** [comment]
thanks

**Comment by Famku** [comment]
I changed the entry to "Require all granted" and restarted the container but the problem still exist.

Any idea

**Comment by nuxsmin** [comment]
Hmm, it's weird. Please, let it as before and remove `|backup` from the previous line.

**Comment by Famku** [comment]
Same

**Comment by Famku** [comment]
It works with http, that's enough for me 

Thanks

**Comment by nuxsmin** [comment]
Please, use Https... editing this 
https://github.com/nuxsmin/docker-syspass/blob/master/sysPass/default-ssl.conf  file you'll get the same behaviour.
